### ISSUE TITLE
Making run_erl use of -daemon optional

### ISSUE THREAD

**Issue by yrashk** [bitwalker/exrm#100]
In order to make it much easier to use upstart (no dancing around `expect` stanza), it would have been great if I can (for example) set a shell variable that would disable the use of the -daemon flag for run_erl.

**Comment by bitwalker** [comment]
That should be doable, have you tested modifying the boot script to remove the flag by any chance? I'd be interested to know if it's as simple as that.

**Comment by yrashk** [comment]
I've only tested removing the flag from `release_name` shell script and it works wonderfully with upstart.

**Comment by eproxus** [comment]
Should you not use the `foreground` target instead?
