### ISSUE TITLE
Adding exrm to mix.exs breaks ex_doc

### ISSUE THREAD

**Issue by cjimison** [bitwalker/exrm#105]
Not sure if this is a bug with exrm or with ex_doc but I just thought I would put it out there:

Reproduction steps:

1) create a new mix project
mix new sandbox --sup

2) Update mix.exs to include ex_doc

defp deps do
    [
        {:earmark,  "~> 0.1",                                           only: :dev},
        {:ex_doc,   "~> 0.7",                                           only: :dev}
    ]

3) Gen Docs
mix deps.get
mix deps.compile
mix compile
mix docs

output:
> Docs successfully generated.
> View them at "doc/index.html".

4) Add exrm to the mix.exs deps

  defp deps do
    [
        {:earmark,  "~> 0.1",                                           only: :dev},
        {:ex_doc,   "~> 0.7",                                           only: :dev},
        {:exrm,     git: "https://github.com/bitwalker/exrm.git",   branch: "master"}
    ]
  end

5) Regen docs
mix deps.get
mix deps.compile
mix compile
mix docs

output:
Command just returns with no output or docs generated.

Given that ex_docs is kind of the standard doc gen tool for elixir right now, it would be awesome if they could play nice together :)

Thanks,

-Chris

**Comment by bitwalker** [comment]
@cjimison I've pushed a fix for this to master, there was an old docs task still in the repo. Sorry for the trouble!

**Comment by cjimison** [comment]
Not a problem and thanks so much!

-Chris
