### ISSUE TITLE
Missing beam file elf_format on generating release

### ISSUE THREAD

**Issue by shankardevy** [bitwalker/exrm#107]
I am getting this message while generating release on a new phoenix project (v0.9)

```
===> Missing beam file elf_format <<"/usr/lib/erlang/lib/hipe-3.11.2/ebin/elf_format.beam">>
```

Release file works fine. So I am not sure if this a warning that I can ignore or is it something that I have to resolve. 

I am using ubuntu 12.04. On my mac, I do not see these error messages.

**Comment by shankardevy** [comment]
as suggested by fishcakez__ on irc, replacing erlang-base with erlang-base-hype resolves this issue. 

```
sudo apt-get install erlang-base-hipe
```

Since this error occurs only on ubuntu and not on mac, I am still leaving this issue open for others to comment on.

**Comment by bitwalker** [comment]
Oh interesting, yeah I've seen this before, it's simply a warning, not an error though. I'm not sure what the specific consequences of this being missing are, can you speak to that at all?

**Comment by shankardevy** [comment]
I am not sure of any "specific consequences". The erlang website says https://www.erlang-solutions.com/downloads/download-erlang-otp (click on ubuntu and read the last faq.)

>HiPE stands for High-Performance Erlang Project. **It is a native code compiler for Erlang. In most cases, it positively affects performance.** If you want to download it, call the following:

>sudo apt-get install erlang-base-hipe
>This will replace the Erlang/OTP runtime with a HiPE supported version. Other Erlang applications do not need to be reinstalled. To return to the standard runtime, call:

>sudo apt-get install erlang-base

**It is a native code compiler for Erlang. In most cases, it positively affects performance.** Not sure what are the edge cases where hipe affects negatively. Can someone with Erlang experience speak about this?

**Comment by shankardevy** [comment]
@bitwalker on another note, can a better message be shown to users while release is generated without hipe? I was confused when I saw the error, here is one another http://stackoverflow.com/questions/28935984/elixir-phoenix-missing-beam-file-elf-format-usr-lib-erlang-lib-hipe-3-11-2 .  I am sure there are many out there having the same question.
