### ISSUE TITLE
How to replace the code with new version?

### ISSUE THREAD

**Issue by shankardevy** [bitwalker/exrm#112]
I have a project online at http://irc.programmingelixir.com and I deployed it using exrm. Now, whenever I make any new changes to the app in my dev machine, how do I update the live site without taking it down?

Right now,  I do this
* Copy the release tar to the server
* Stop the app
* extract and replace the app files
* start the app

I read a lot about hot code swapping in erlang and elixir but not sure what it means in practice? I assume that is related to deploying new releases without any downtime. But how do I do it with exrm?

**Comment by bitwalker** [comment]
The README file has a walkthrough on doing a hot upgrade. Let me know if it doesn't cover some portion of the process well enough.
