### ISSUE TITLE
Advantages of using release vs compiling on server?

### ISSUE THREAD

**Issue by shankardevy** [bitwalker/exrm#113]
I understand that a release contains a full runtime bundled with it and there is no need installing erlang or elixir to run the app when deployed using exrm releases. However, doing a lot of small changes to an app and constantly deploying, it takes a lot of time to copy the tar file everytime to the server. 

Wouldn't it be good to have a src copied to server somewhere and a command either on server or local machine compiles the server code and starts it? Any new changes in the code is just a 'git pull' away and doesn't take too much time.

Am I missing any real advantage of release or missing to see any problem compiling on the server?

**Comment by bitwalker** [comment]
I think this question is better suited for the mailing list as a general question about releases. My personal thought on this is that releases are not for every application, exrm makes it easy to get started with them, so they become more appealing, but there is still a lot of thought that must go in to how you will manage releases. Will you do hot upgrades, or just use the release package as a convenient deployment artifact? How is your deployment environment setup, should you be installing your development tooling on those servers, or is it irrelevant? I think there are a lot of questions you should ask yourself before you choose one or the other, my goal with exrm is to make it as simple as possible to get started with releases, but it doesn't attempt to answer those questions for you.
