### ISSUE TITLE
Getting {error,{enoent,"/app/releases/0.0.1/relup"}} when trying to do bin/app upgrade "0.0.2"

### ISSUE THREAD

**Issue by hahuang65** [bitwalker/exrm#117]
I noticed danmcclain having a similar issue in this gist:

https://gist.github.com/danmcclain/6a4c58ebee1e26fa895b

I basically just did a

`MIX_ENV=prod mix release`
then scp'd the file over, copied the tar into the /app/releases/0.0.2 folder, renamed it to just "app.tar.gz"
then ran `bin/app upgrade "0.0.2"`

**Comment by bitwalker** [comment]
@hahuang65 What OS, Erlang and Elixir versions are you building and deploying to? And could you gist your relx.config as well? I'll have to do some poking around, but something must be different than my test environment because I can't seem to reproduce this error locally.

**Comment by hahuang65** [comment]
I'm on Ubuntu, 17.5 and 1.0.4.

I think this is because I'm building different releases on different machines. I'll let you know if this happens again.
