### ISSUE TITLE
[RFC] Reusing of existing cuttlefish <app>.schema

### ISSUE THREAD

**Issue by liveforeverx** [bitwalker/exrm#120]
Is it possible? (Or may be planned) to have some support for reusing existing cuttlefish schema?
For example, if release-app dependes on app2, which have cuttlefish schema.
For example, if release uses bitcask, is there a possibility for adding to .conf, [bitcask schema example](https://github.com/basho/bitcask/blob/develop/priv/bitcask.schema).

**Comment by bitwalker** [comment]
I think it's worth looking into, but offhand I'd guess that it won't be feasible without rewriting conform to be compatible with cuttlefish schema/conf files. Perhaps it is worthwhile, but it would be a fairly large undertaking, and a backwards incompatible one at that. I initially modeled conform after cuttlefish, but with a focus on Elixir syntax for the schemas, but it's by no means as robust as cuttlefish at this point, though it addresses a large portion of the typical use cases.

I unfortunately am swamped right now, and don't have time to experiment with this, but I welcome any conversation, PRs, or code reviews people bring to the table. I'm certainly open to considering the change.

**Comment by liveforeverx** [comment]
Many thanks for answer!

We are planning to use existing erlang libraries with elixir releases, and for not to rewrite all existing schemas for erlang applications, that would be good to support it(at least from this point), the cuttlefish configuration. It would be good to mix erlang + cuttlefish with elixir + conform configuration files, to build the release configuration. 

I think, I'll tackle this somewhere end of May or somewhere in June.

**Comment by bitwalker** [comment]
I think it's a good goal to be sure, so I'm super interested to see how we could make this happen. I'm open to discussing ways to tackle this whenever you are ready to dive in.

**Comment by liveforeverx** [comment]
Hi, ok, I'll ping you, when I'll start. Will you be accessible on irc for discussion?

**Comment by bitwalker** [comment]
I'll try and make myself more regularly available on IRC, but comments here and/or emails are the most reliable way to get in touch with me currently.

**Comment by hwinkel** [comment]
+1 for that, we should not fragment the Erlang/Elixir Ecosystems as people will run and configure Erlang and Elixir Apps in parallel

**Comment by bitwalker** [comment]
@hwinkel While I agree in general, the complexity of supporting two schema formats/semantics is not worth it to me. There is a lot of crossover currently, but conform may ultimately end up supporting more features, or a divergent set of features, and maintaining compatibility is asking for trouble. 

It's my opinion that if you are currently using cuttlefish and introducing Elixir to your stack, you may as well continue using cuttlefish. If you are starting fresh with Elixir, conform is probably the better option (integration with exrm/releases, schema defined in Elixir terms, etc.). If you need features of conform and are currently using cuttlefish, I would argue that things are semantically close enough right now to make a fairly trivial transition to conform. Would it be nice to share schemas? Probably, but I honestly don't think the feature would see enough demand/use to really justify the effort.

**Comment by bitwalker** [comment]
I'm closing this for now, as after more thought, I don't see this really being a feasible addition. This also belongs in the `conform` issue tracker rather than here, so if everyone would like to continue discussion there, that's fine.
