### ISSUE TITLE
mix release fails with "No releases exist in the system for 'my_app':0.0.1!"

### ISSUE THREAD

**Issue by D1plo1d** [bitwalker/exrm#122]
There don't appear to be any errors but it looks like the release isn't being created.

Here's what I get when I run `mix release --verbosity=verbose`:

https://gist.github.com/D1plo1d/de88d8f8325ce6493e8c

**Comment by bitwalker** [comment]
This appears to be an issue with the pascal-cased application name as I was able to reproduce this with my `exrm-test` app, and just changing the app name to be capitalized. I don't yet know where this is taking place, but the convention for application names in the Erlang/Elixir world is all lowercase, so there may be assumptions baked into relx which this bumps up against. Could you adjust that and try again just for the sake of confirmation?

**Comment by D1plo1d** [comment]
@bitwalker Renaming app in mix.exs to a lowercase/underscored name totally fixed it. Thanks!

**Comment by liveforeverx** [comment]
I've have a question, how generally define the version of a release? I have a 0.0.1 version, it works, after to triing define the version 1.0.0 like it: {release, {my_app, "1.0.0"}, [my_app]} in relx.config. It failed: 

No releases exist in the system for my_app:0.0.1!
==> Failed to build release. Please fix any errors and try again.

What can be wrong? Or how to define the version properly with?

**Comment by bitwalker** [comment]
Hey Dmitry,

The problem here (I'm assuming, I'd need to test my assumption) is likely
that you are adding release definitions manually to the relx.config. exrm
will handle that for you transparently. I'd be interested to hear if it
works if you let exrm define the release for you.

Paul
