### ISSUE TITLE
Error when doing mix.release

### ISSUE THREAD

**Issue by houshuang** [bitwalker/exrm#123]
I'm trying to use exrm to package a Phoenix app. Weirdly, it worked the first time, however I needed to make a small change, and now it doesn't work at all. Unfortunately, I can't even begin to understand the error message.

```erlang
==> Building release with MIX_ENV=prod.
==> Generating relx configuration...
==> Generating sys.config...
==> Generating boot script...
==> Performing protocol consolidation...
==> Conform: Loading schema...
==> Conform: No schema found, conform will not be packaged in this release!
==> Generating release...

=ERROR REPORT==== 22-May-2015::21:17:32 ===
Error in process <0.8158.0> with exit value: {function_clause,[{rlx_dscv_util,discover_dir,[#Fun<rlx_app_discovery.4.75857726>,<<89 bytes>>,undefined],[{file,"src/rlx_dscv_util.erl"},{line,81}]},{lists,map,2,[{file,"lists.erl"},{line,1237}]},{ec_plists,'-local_runmany/3-fun-0-',3,[{file,"src/ec_plists.erl"},{line,753}]}]}


=ERROR REPORT==== 22-May-2015::21:17:32 ===
Error in process <0.8159.0> with exit value: {function_clause,[{rlx_dscv_util,discover_dir,[#Fun<rlx_app_discovery.4.75857726>,<<89 bytes>>,undefined],[{file,"src/rlx_dscv_util.erl"},{line,81}]},{lists,map,2,[{file,"lists.erl"},{line,1237}]},{ec_plists,'-local_runmany/3-fun-0-',3,[{file,"src/ec_plists.erl"},{line,753}]}]}

escript: exception exit: {function_clause,
                    [{rlx_dscv_util,discover_dir,
                         [#Fun<rlx_app_discovery.4.75857726>,
                          <<"/Users/stian/src/inquirymooc/survey/rel/survey/0.0.1/tmp/erl_pipes/survey/erlang.pipe.1.r">>,
                          undefined],
                         [{file,"src/rlx_dscv_util.erl"},{line,81}]},
                     {lists,map,2,[{file,"lists.erl"},{line,1237}]},
                     {ec_plists,'-local_runmany/3-fun-0-',3,
                         [{file,"src/ec_plists.erl"},{line,753}]}]}
  in function  ec_plists:handle_error/3 (src/ec_plists.erl, line 900)
  in call from ec_plists:local_runmany/3 (src/ec_plists.erl, line 764)
  in call from rlx_dscv_util:do/2 (src/rlx_dscv_util.erl, line 52)
  in call from rlx_app_discovery:resolve_app_metadata/2 (src/rlx_app_discovery.erl, line 103)
  in call from rlx_prv_app_discover:do/1 (src/rlx_prv_app_discover.erl, line 59)
  in call from providers:run_all/2 (src/providers.erl, line 82)
  in call from relx:run_provider/2 (src/relx.erl, line 286)
  in call from lists:foldl/3 (lists.erl, line 1261)
==> Failed to build release. Please fix any errors and try again.
```

**Comment by citizenparker** [comment]
I had a very similar experience just now. I was adding applications to `:included_applications` in mix.exs and started getting this error. I reverted my changes and continued to receive it. I finally blew away my `rel/` directory at which point I was able to compile releases again, no changes to my code needed.

**Comment by liveforeverx** [comment]
@houshuang if you still have a problem or want know, what is a problem, you can try to ask it by relx, if the bug/known or fixed. If it fixed, all, what exrm needs, is update to actual relx.

**Comment by bitwalker** [comment]
I can update the relx binary currently bundled with exrm ASAP. What's really needed is a way to bundle relx as a library for exrm, which is more maintainable moving forward, but because of build issues due to the use of `erly_dtl`, I've held off on that. I was working on a pure Erlang templating library which could replace `erly_dtl`, but I've had to put it on standby since work has me swamped for the time being.

**Comment by bitwalker** [comment]
Well it looks like Tristan updated relx to remove that dependency, so I've pushed a new release of exrm (0.17.0) which transitions from using the relx binary to consuming relx as a library. You'll need to make sure you add `{:relx, github: "erlware/relx"}` to your mix.exs when moving to the new version, but it should be much faster now.

**Comment by tsloughter** [comment]
:)

And I plan to publish relx to hex, but currently blocked by the mustache app name conflicts with another already published app.

**Comment by bitwalker** [comment]
Since we've updated to relx via hex, I'm closing this for now :)
