### ISSUE TITLE
Possible to redefine location of configuration?

### ISSUE THREAD

**Issue by liveforeverx** [bitwalker/exrm#124]
Is it possible to redefine with some variable or something like it?

**Comment by liveforeverx** [comment]
The objective for it, is, if you install release as OS package, you want to have configuration somewhere in /etc/...., and do not override it.

Because of this, it would be nice to have configuration at /etc/..., that it didn't overrides per default. Or there would be a cleaner solution for it?

**Comment by tsloughter** [comment]
In relx there isn't right now. You'd have to set `{generate_start_script, false}` and supply your own start script.

**Comment by liveforeverx** [comment]
@tsloughter : thats, what exrm do `{generate_start_script, false}`, but should it be generally possible with exrm, like https://github.com/bitwalker/exrm/pull/127 ? Make it sense to have a general solution for the problem?

**Comment by bitwalker** [comment]
It's possible to do this, I see there is a PR for it, but I'll have to spend some time reviewing it since it looks like the CI build failed for some reason.

**Comment by umatomba** [comment]
i'll check the CI tests

**Comment by bitwalker** [comment]
All of the PRs relevant for this issue have been merged (either automatically or manually). Could you guys test the new 0.17.2 release and let me know if things work as expected?

**Comment by bitwalker** [comment]
This is now handled via the `RELEASE_MUTABLE_DIR` environment variable. Closing for now.
