### ISSUE TITLE
Possible to trigger runtime reconfiguration?

### ISSUE THREAD

**Issue by liveforeverx** [bitwalker/exrm#125]
Something like <app> reconfigure exists?

**Comment by bitwalker** [comment]
Reloading the application will reload the configuration, but other than that, one would have to load the config manually and call `Application.set_env` for each config setting in order to mimic reloading the configuration. So in theory it's possible to write such a feature, but one doesn't exist in the standard library as far as I'm aware.

**Comment by liveforeverx** [comment]
@bitwalker, that how it works from application_controller(that is a part of how release_handler using application_controller for doing it), to do it, I simple plan to port this [code](https://github.com/travelping/enit/blob/master/src/enit_remote.erl#L227-L231) to exrm directly. Only one thing stays, if we want to suspend/resume processes for the update.

**Comment by bitwalker** [comment]
@liveforeverx Nice! The other thing would be that exrm is not bundled with releases generally (at least I don't know why someone would be including a compile-time release tool with their release), it seems to me that this might be a good candidate for an external lib perhaps?

**Comment by liveforeverx** [comment]
application_controller is in kernel, and we need only application_controller for making reconfigure.

**Comment by liveforeverx** [comment]
Missed part of first message, yes, it is something, to mimic manually.

**Comment by surik** [comment]
HI!

I see it like that:
1) Add possibility to set node arguments for `config schema file` and `conform config file` on exrm
2) Create a plugin for exrm, which called `exrm_reload`. The plugin will have a method `run` which will generate new sys.config via conform (using the arguments from first step) and apply this config for all applications via `application_controller`. The `exrm_reload` will be runtime dependency.

**Comment by surik** [comment]
If you don't mind I'll do it

**Comment by bitwalker** [comment]
@surik Go for it! Just a quick question though: how is the plugin executed? I'm also assuming it's not a plugin for exrm, but rather an extension of exrm that can be called via RPC to a node?

**Comment by surik** [comment]
@bitwalker You're right, It's just application which we able to call via RPC. I called it plugin because it uses some configuration from `exrm` (1st step) but actually it doesn't depend on `exrm`.

I'm thinking can I call it `exrm_reload` or i should use other name.

**Comment by bitwalker** [comment]
@surik `exrm_reload` sounds fine to me!
