### ISSUE TITLE
Release fails when xmerl is a dependency 

### ISSUE THREAD

**Issue by hexedpackets** [bitwalker/exrm#130]
I have an application which makes use of xmerl, but exrm fails to find it. The error message is 

```
Failed to solve release:
 Dependency xmerl is specified as a dependency but is not reachable by the system.

==> Failed to build release. Please fix any errors and try again.
```

Regardless of whether I have "xmerl" in my list of applications, the release fails since I'm also using erlcloud which in turn has xmerl in its applications. I saw that this had happened in #8 with unicode and tried removing xmerl from erlcloud's application list but xmerl is apparently not part of the stdlib so it isn't included.

The xmerl directory (`/usr/lib/erlang/lib/xmerl-1.3.7/` for me) has an "include" subdirectory but no "ebin". Not sure if that might be the cause?

**Comment by liveforeverx** [comment]
It is a definitely a cause. It is something wrong with you erlang installation. ebin should exists.

```
ls xmerl-1.3.7
ebin/    include/ src/
```

**Comment by hexedpackets** [comment]
I'm using Debian and switching the apt source from wheezy to jessie fixed this (although I then had to compile Elixir from source, but oh well).

**Comment by koudelka** [comment]
On ubuntu, I solved it with an `apt-get install erlang-xmerl`
