### ISSUE TITLE
/usr/local/bin/mix:2: syntax error before: Mix

### ISSUE THREAD

**Issue by olgeni** [bitwalker/exrm#145]
Hi,

I'm testing "mix release" with the sample exrm-test project under FreeBSD (R18, Elixir 1.0.5, exrm 0.17.1).

Everything seems to work fine, but I get a syntax error about Mix:

    % mix release
    ==> Building release with MIX_ENV=dev.
    ==> Generating relx configuration...
    ==> Generating sys.config...
    ==> Generating boot script...
    ==> Conform: Loading schema...
    ==> Conform: Schema succesfully loaded!
    ==> Conform: Generating escript..
    ==> Conform: Adding overlays to relx.config...
    ==> Conform: Done!
    ==> Performing protocol consolidation...
    ==> Generating release...
    /usr/local/bin/mix:2: syntax error before: Mix
    /usr/local/bin/mix:2: syntax error before: Mix
    /usr/local/bin/mix:2: syntax error before: Mix
    /usr/local/bin/mix:2: syntax error before: Mix
    /usr/local/bin/mix:2: syntax error before: Mix
    /usr/local/bin/mix:2: syntax error before: Mix
    /usr/local/bin/mix:2: syntax error before: Mix
    /usr/local/bin/mix:2: syntax error before: Mix
    /usr/local/bin/mix:2: syntax error before: Mix
    ==> Generating nodetool...
    ==> Packaging release...
    ==> The release for test-0.0.1 is ready!

There's not much to see in mix itself:

    % cat /usr/local/bin/mix
    #!/usr/bin/env elixir
    Mix.start
    Mix.CLI.main

Any idea about how to track this down would be welcome :)

**Comment by bitwalker** [comment]
This is something being output by relx, I'm still not sure specifically what is causing it, but @tsloughter and I got near to the bottom of it the other day, he/I/we still need to come up with some kind of solution for it though. In the meantime, you can safely ignore it, as it doesn't seem to actually affect the generated release at all. I'll be updating the relx dependency once a fix is ready :)

**Comment by olgeni** [comment]
:+1:

**Comment by bitwalker** [comment]
@olgeni This was fixed in the last release of exrm by the way :)
