### ISSUE TITLE
Cannot find tar.gz file to upgrade

### ISSUE THREAD

**Issue by HashNuke** [bitwalker/exrm#152]
Tried upgrading with: `rel/firebrick/bin/firebrick upgrade "0.0.2"`

It looks for the tar.gz file in `rel/firebrick/releases/0.0.2/firebrick.tar.gz`, but the file is instead at `rel/firebrick/firebrick-0.0.2.tar.gz`.
![screen shot 2015-07-02 at 2 45 10 pm](https://cloud.githubusercontent.com/assets/84005/8474729/cfa58bc8-20cf-11e5-9920-3005702b8334.png)

**Comment by bitwalker** [comment]
@HashNuke this is expected, but perhaps should be changed so that by default it puts it in the appropriate release directory.

**Comment by HashNuke** [comment]
@bitwalker is there anything that should be changed in exrm to fix this or is there some config option?

**Comment by bitwalker** [comment]
@HashNuke I found where this can be changed, I'll push this to master here shortly :)

**Comment by bitwalker** [comment]
@HashNuke I've published version 0.18.0 on hex which now dumps those tarballs in the `releases/<version>` directory. I don't see it being a significant change, but since it's backwards-incompatible in terms of any automated build tools, I've bumped the minor version for this release.
