### ISSUE TITLE
Build of Phoenix 0.13.1 application fails with no guidance as to why

### ISSUE THREAD

**Issue by midas** [bitwalker/exrm#154]
Everything compiles fine and then all of a sudden, exrm reports a failure with no details, thus I do not know how to begin tracking the issue down.

```
==> Building release with MIX_ENV=prod.
==> Generating relx configuration...
==> Generating sys.config...
==> Generating boot script...
==> Performing protocol consolidation...
==> Conform: Loading schema...
==> Conform: No schema found, conform will not be packaged in this release!
==> Generating release...
==> Failed to build release. Please fix any errors and try again.
```

Following are the contents of my apps mix.exs file.

```
 ...

    def project do
      [app: :some_app,
       version: "0.1.0",
       elixir: "~> 1.0",
       elixirc_paths: elixirc_paths(Mix.env),
       compilers: [:phoenix] ++ Mix.compilers,
       build_embedded: Mix.env == :prod,
       start_permanent: Mix.env == :prod,
       preferred_cli_env: [espec: :test],
       deps: deps]
    end

    # Configuration for the OTP application
    #
    # Type `mix help compile.app` for more information
    def application do
      [
        mod: {SomeApp, []},
        applications: [
          :phoenix,
          :phoenix_html,
          :cowboy,
          :logger,
          :phoenix_ecto,
          :postgrex,
          :erlzmq,
          :dotenv
        ]
      ]
    end

    # Specifies which paths to compile per environment
    defp elixirc_paths(:test), do: ["lib", "web", "test/support"]
    defp elixirc_paths(_),     do: ["lib", "web"]

    # Specifies your project dependencies
    #
    # Type `mix help deps` for examples and options
    defp deps do
      [{:phoenix, "~> 0.13"},
       {:phoenix_ecto, "~> 0.4"},
       {:postgrex, ">= 0.0.0"},
       {:phoenix_html, "~> 1.0"},
       {:phoenix_live_reload, "~> 0.4", only: :dev},
       {:cowboy, "~> 1.0"},
       {:erlzmq, github: "zeromq/erlzmq2"},
       {:uuid, "~> 1.0"},
       {:good_times, "~> 1.0.0"},
       {:espec_phoenix, "~> 0.1", only: :test, app: false},
       {:apex, "~>0.3.2", only: :dev},
       {:dotenv, "~> 1.0"},
       {:logger_file_backend, github: "onkel-dirtus/logger_file_backend"},
       {:exrm, "~> 0.18"},
       {:rebar3_hex, "~> 0.8"},
       {:timex, "~> 0.13"}]
    end

  ...
```

**Comment by bitwalker** [comment]
Could you post the output of running `mix release --verbosity=verbose`? This outputs the debug log and can help us track down the issue.

I think I'm going to update the error handling to suggest this on failure, I put documentation in the task docs for `mix release`, but I don't think that's very helpful currently.

**Comment by midas** [comment]
No need to post, your hint gave me what I needed to fix this myself.  

I apologize, but I am fairly new to Erlang/Elixir and I do not have a great understanding of the toolset, etc yet.  I am sure you will have more and more newbies rolling though due to Elixir's lower barrier of entry, so putting that message into the error would probably save you lots of interruptions, like me :).

Anyways, thanks for your quick response and thanks for all of the hard work you have done on this project!  Take care.

**Comment by bitwalker** [comment]
@midas No worries, I'm glad you were able to get it sorted :). These questions are definitely not an interruption so don't worry about that, it helps guide me towards ways to make the tooling better!
