### ISSUE TITLE
Cannot parse version

### ISSUE THREAD

**Issue by mguillemot** [bitwalker/exrm#156]
I don't seem to be able to generate a release w/ Elixir 1.0.5 & Erlang 18.0.

Just adding `{:exrm, "~> 0.18.1"}` to an empty Mix project and doing `MIX_ENV=prod mix release`, I get the following error:

```
==> Generating release...

18:51:53.777 [error] Process #PID<0.1861.0> raised an exception
** (FunctionClauseError) no function clause matching in :rlx_app_info.parse_version/1
    src/rlx_app_info.erl:197: :rlx_app_info.parse_version({1, 14})
    src/rlx_app_info.erl:98: :rlx_app_info.new/6
    src/rlx_app_discovery.erl:298: :rlx_app_discovery.get_vsn/3
    src/rlx_dscv_util.erl:97: :rlx_dscv_util.discover_dir/3
    (stdlib) lists.erl:1238: :lists.map/2
    src/ec_plists.erl:753: anonymous fn/3 in :ec_plists.local_runmany/3

** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in :rlx_app_info.parse_version/1
        src/rlx_app_info.erl:197: :rlx_app_info.parse_version({1, 14})
        src/rlx_app_info.erl:98: :rlx_app_info.new/6
        src/rlx_app_discovery.erl:298: :rlx_app_discovery.get_vsn/3
        src/rlx_dscv_util.erl:97: :rlx_dscv_util.discover_dir/3
        (stdlib) lists.erl:1238: :lists.map/2
        src/ec_plists.erl:753: anonymous fn/3 in :ec_plists.local_runmany/3
    src/ec_plists.erl:900: :ec_plists.handle_error/3
    src/ec_plists.erl:764: :ec_plists.local_runmany/3
    src/rlx_dscv_util.erl:52: :rlx_dscv_util.do/2
    src/rlx_app_discovery.erl:103: :rlx_app_discovery.resolve_app_metadata/2
    src/rlx_prv_app_discover.erl:54: :rlx_prv_app_discover.do/1
    src/relx.erl:286: :relx.run_provider/2
    (stdlib) lists.erl:1262: :lists.foldl/3
    src/relx.erl:266: :relx.run_providers/1
```

OS is Ubuntu Server 15.04 64 bit with a fresh install of Elixir 1.0.5 and Erlang 18.0. Glancing through rlx source code, it seems :rlx_app_info.parse_version is expecting either a list or a {_, {_, _}} tuple, but I don't really get where the {1, 14} is coming from...

**Comment by bitwalker** [comment]
@mguillemot Can you post your `mix.exs`? That may help. I would guess some version of an application, either yours or a dependency's, is using a version number in a scheme relx isn't supporting (could be a bug too).

/cc @tsloughter

**Comment by tsloughter** [comment]
Right, relx expects a string or something already parsed by its semver parser which returns `{Vsn, BuildVersion}`.

**Comment by mguillemot** [comment]
This was a empty new application generated by `mix new`. So only dependency is `{:exrm, "~> 0.18.1"}`, and application version was the default `"0.0.1"`.

**Comment by mguillemot** [comment]
I don't seem to be able to reproduce the issue on either my Windows machine, or a Ubuntu Server 14.09 64bit, with the same versions of Erlang/Elixir installed. I'll try to reproduce on another Ubuntu Server 15.04... (Issue was consistent on my test machine, I generated a dozen projects with various configuration changes, and always had the same error...)

**Comment by bitwalker** [comment]
I'm installing R18 to test on my machine as well.

**Comment by bitwalker** [comment]
@mguillemot Can't reproduce on OSX (10.10.2) either :(. I don't have a 15.04 VM handy to test with, but when I get some time I'll try to spin one up. If you are able to reproduce on another server, there's probably a bug somewhere, if you can't, I wonder if maybe something is up with the Erlang/Elixir install on that server?

**Comment by mguillemot** [comment]
This was on a brand-new install of Ubuntu Server 15.04 in a VM, using the official erlang-solutions packages for both Erlang and Elixir (`apt-get install erlang elixir`). I'll try again on a new image tomorrow at work...

**Comment by tsloughter** [comment]
Which erlang-solutions packages? "Enterprise" or "Standard"?

**Comment by mguillemot** [comment]
Just using the install instructions from the Elixir website at http://elixir-lang.org/install.html, so:

wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb && sudo dpkg -i erlang-solutions_1.0_all.deb

This seem to install the `contrib` branch of their apt repo, which is "standard" I guess?

**Comment by tsloughter** [comment]
Argh, no, I think that now gets the "enterprise" one. Can you check if you have random stuff like rebar, rebar3, cowboy (in libs)?

**Comment by bitwalker** [comment]
@mguillemot I'm unable to reproduce using the Ubuntu 15.04 VirtualBox image [located here](http://virtualboxes.org/images/ubuntu/#ubuntu1504). Here are the steps I took to initialize the VM with Erlang/Elixir:

```
$ sudo apt-get upgrade
$ wget http://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
$ sudo dpkg -i erlang-solutions_1.0_all.deb
$ sudo vim /etc/apt/sources.list # per the instructions on https://packages.erlang-solutions.com/erlang/ under Ubuntu
$ wget http://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
$ sudo apt-key add erlang_solutions.asc
$ sudo apt-get update
$ sudo apt-get install erlang
$ sudo apt-get install elixir
$ mkdir Repositories && cd Repositories
$ mix new test
$ vim mix.exs # add exrm dep
$ mix local.hex
$ mix do deps.get, compile
$ mix release
```
There has to be something funky with either the system you were on, or maybe your installation process was different? I see that there is a Vivid tab on the Erlang Solutions site, but I just went with the usual Ubuntu installation instructions, maybe that's where there was a hiccup?

**Comment by mguillemot** [comment]
After being unable to reproduce on 2 different machines, I went back to the original erroneous VM, forced the re-installation of both Erlang and Elixir packages, and the error is now gone.

Sorry for the false alert, and many thanks for helping on debugging the issue. I'm always super-impressed by the reactivity and helpfulness of the Erlang/Elixir community!

**Comment by bitwalker** [comment]
No problem! Issues like these are super frustrating, wish we knew what happened here exactly, but sometimes that's how it goes :(

**Comment by mguillemot** [comment]
Yeah, me too, I'm not really satisfied by the lack of answer to "why"... But difficult to diagnose non-reproductible bugs...
