### ISSUE TITLE
Set tar name maybe error

### ISSUE THREAD

**Issue by jsvisa** [bitwalker/exrm#159]
You just removed the tarball [L356-L357](https://github.com/bitwalker/exrm/blob/master/lib%2Fmix%2Ftasks%2Frelease.ex#L356-L357),
but you reset the value [L380](https://github.com/bitwalker/exrm/blob/master/lib%2Fmix%2Ftasks%2Frelease.ex#L380), 
Shouldn't it be [release_tarball] ?(https://github.com/bitwalker/exrm/blob/master/lib%2Fmix%2Ftasks%2Frelease.ex#L373)

**Comment by bitwalker** [comment]
Oh my, you are exactly correct, I overlooked that reference. I'll push a fix in a few minutes. Thanks!
