### ISSUE TITLE
Upgrade does not use proper config.

### ISSUE THREAD

**Issue by vishnevskiy** [bitwalker/exrm#162]
I am making this ticket because maybe I am doing something wrong.

I tried making a release and then upgrading and what was happening was that the code was reloaded but the configs were all set to the defaults from my config.exs file and not what is in my .conf fine after the upgrade.

So I tried using unpack first and making sure that in the 0.0.2 folder the conf file was updated accordingly. Still no dice.

I finally tried to unpack and then copy sys.config from running-config to releases/0.0.2 and then upgrade. Worked like a charm.

Is this intended, bug or am I doing this completely wrong?

**Comment by bitwalker** [comment]
Fixed in 0615313, released in 0.18.7
