### ISSUE TITLE
cross compiling issue

### ISSUE THREAD

**Issue by mpahrens** [bitwalker/exrm#163]
Hello! I am having an issue trying to cross compile ala the instructions in #99 for my project blockytalky: https://github.com/tufts-LPC/blockytalky_elixir
My: `/rel/relx.config` looks like this:
<pre><code>
{include_erts, "/vagrant/erlang"}.
{system_libs, "/vagrant/erlang/lib"}.
</code></pre>
and in that erlang folder is an arm build of erlang with `erts-6.1`

When I compile with `mix release --verbosity=verbose`, I get the following error
<pre><code>
...Everything is good up until this point...
===> Running provider overlay
===> Provider successfully run: overlay
===> Running provider release
===> Including Erts from /vagrant/erlang
===> release successfully created!
===> Provider successfully run: release
===> Running provider tar
===> tarball /vagrant/blockytalky/rel/blockytalky/blockytalky-0.1.3.tar.gz successfully created!
===> Provider successfully run: tar
==> Generating nodetool...
==> Packaging release...
** (MatchError) no match of right hand side value: {:error, {'/vagrant/blockytalky/rel/blockytalky/erts-6.4', :enoent}}
    lib/mix/tasks/release.ex:366: Mix.Tasks.Release.update_release_package/1
    lib/mix/tasks/release.ex:73: Mix.Tasks.Release.do_run/1
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2
    (elixir) lib/code.ex:307: Code.require_file/2
</code></pre>

In the run script it generated `/re/blockytalky/bin/blockytalky`, it has the ERTS_VSN as 6.4 (the same as my development environment), and not the 6.1 that I am telling it to point to, as well as the above error. Any ideas?

update: fixed markdown formatting, sorry!

**Comment by bitwalker** [comment]
@mpahrens The name of the config file for relx is actually `relx.config`, so it's location should be `rel/relx.config`. Was that just a typo?

**Comment by mpahrens** [comment]
yes it was just a typo, the filename is correct in my repo

**Comment by bitwalker** [comment]
Ah I think I see the bug here, one second and I should have a fix in master for you to test with.

**Comment by mpahrens** [comment]
Thanks! :+1: :)

**Comment by bitwalker** [comment]
@mpahrens Ok found the issue and pushed a new release 0.18.4 with the fix.

**NOTE:** It's important that your path in `{include_erts, <path>}` is pointing to the correct place. To validate the path, just run `$ ls <path>` and you should see a folder called `erts-X.X`. So for example, on my OSX machine, my homebrew-installed Erlang path which I could use with `include_erts` is `/usr/local/Cellar/erlang/17.5/lib/erlang`.

**Comment by mpahrens** [comment]
Let me give it a try! and my include_erts path passes that test! :) You might have looked though my commits and saw I didn't exactly know what to put there (I didn't and was trying stuff to see if the issue was my stupidity).

**Comment by mpahrens** [comment]
So, I pulled your latest and used it. it did not error out this time, but in `/rel/blockytalky/bin/blockytalky` and `/rel/blockytalky/bin/blockytalky.bat` The first few lines of the boot script are like:
<pre><code>
#!/bin/sh

set -e

SCRIPT_DIR="$(dirname "$0")"
RELEASE_ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REL_NAME="blockytalky"
REL_VSN="0.1.3"
ERTS_VSN="6.4"
RELEASES_DIR="$RELEASE_ROOT_DIR/releases"
REL_DIR="$RELEASES_DIR/$REL_VSN"
REL_LIB_DIR="$RELEASE_ROOT_DIR/lib"
ERL_OPTS=""
PIPE_DIR="$RELEASE_ROOT_DIR/tmp/erl_pipes/blockytalky/"
ERTS_DIR=""
ROOTDIR=""
...etc...etc
</pre></code>

and my verbose also prints out 6.4:
 <pre><code>
==> Conform: Loading schema...
==> Conform: No schema found, conform will not be packaged in this release!
==> Generating release...
===> Starting relx build process ...
===> state(api):
          log: (3:debug),
          config file: /vagrant/blockytalky/rel/files/relx.config
          goals:
          output_dir: /vagrant/blockytalky/_rel
          lib_dirs:
          providers:
               tar,
               relup,
               release,
               resolve_release,
               overlay,
               rel_discover,
               app_discover,
          provider config values:
               {overlay_vars,[]},
               {system_libs,true},
               {default_libs,true},
[..compiling, compiling....]
===> Running provider app_discover
===> Resolving OTP Applications from directories:
          /opt/elixir/1.0.4/bin/../lib
          /vagrant/blockytalky/_build/prod
          /vagrant/blockytalky/lib
          /vagrant/blockytalky/deps
          /vagrant/erlang/lib
          /vagrant/blockytalky/rel
===> Missing beam file elf_format <<"/vagrant/erlang/lib/hipe-3.11/ebin/elf_format.beam">>
===> Resolved the following OTP Applications from the system:
[....mix, logger, etc. etc. ....]
===> Provider successfully run: app_discover
===> Running provider rel_discover
===> Resolving available OTP Releases from directories:
          /opt/elixir/1.0.4/bin/../lib
          /vagrant/blockytalky/_build/prod
          /vagrant/blockytalky/rel
===> Resolved the following OTP Releases from the system:

===> Provider successfully run: rel_discover
===> Running provider resolve_release
===> Solving Release blockytalky-0.1.3
===> Resolved blockytalky-0.1.3
===> release: blockytalky-0.1.3
           erts-6.4, realized = true

</code></pre>

The ERTS being included now is 6.1(the one I want), though. so yay!  Is my {system_libs} wrong? the result of `ls /vagrant/erlang` is:
`bin  erts-6.1  lib  man  releases  usr`

I am going to try and see if that release works though on the rpi (arm) or if that erts_vsn matters.

**Comment by bitwalker** [comment]
@mpahrens Yeah that's a related bug I'll need to fix, I'll keep this open for now while I address it :)

**Comment by mpahrens** [comment]
Thanks! (especially for your hard work). If I wasn't trying to get a release out for a summer camp with kids to use my school's project, I'd dig and help fix these kinds of things myself. Thanks again!

**Comment by mpahrens** [comment]
even with that script version being mislabeled, it runs with the correct version. So, I'm happy :)

**Comment by bitwalker** [comment]
@mpahrens Awesome :), I pushed an update to master which correctly populates `ERTS_VSN` now as well. So I'll close this out. Feel free to reopen it if something with this pops up again!
