### ISSUE TITLE
tar.gz that is created for specific version accumulates previous tar.gzs, making filesize grow each time

### ISSUE THREAD

**Issue by mpahrens** [bitwalker/exrm#164]
Hello!
This may be the intended behavior, but I wanted to ask in case there is something I could do.
When a make a release (which has been going very smoothly now, thank you :) ) it generates the 
tar ball  at:
`rel/blockytalky/releases/0.1.4/blockytalky.tar.gz` or whatever version number I am on.
I noticed that each time I make a release, this file gets a lot bigger (it was ~40MB the first time, now it is 100MB the second time). I see it has inside of it the tarballs for its own version and the previous versions. This results in the large increase in size each time (I am just worried about sustaining that level of redundancy 5-6 builds in.) I was wondering:
What is the proper thing for me to do if I just want the 0.1.4 tarball and not the history for deployment purposes? I would like to be able to drop the simple, 40MB tarball on my raspberry pis without the history unpacking with it. 

Should I get the inner tarball from this one? or is there another way to disable the accumulation?

Thanks!

Edit: I renamed the tar file manually. I changed the question to reflect the tarball name that is generated by mix release

**Comment by bitwalker** [comment]
@mpahrens Yeah this is definitely not intended, The tarball should only contain the current release, I'll do a bit of digging :)

**Comment by bitwalker** [comment]
I'm not totally satisfied with my solution to this one, but it works as intended and fixes another bug which was also introduced by the same change that introduced this one. It's pushed to master, once the build passes I'll push to hex!

**Comment by mpahrens** [comment]
Thanks!!
