### ISSUE TITLE
tar.gz under rel/appname/releases/version is broken

### ISSUE THREAD

**Issue by romul** [bitwalker/exrm#165]
Hello. I've discovered that tarball under rel/appname/releases/version directory is not usable, most likely because it trying to create an archive inside archived directory.
The issue was introduced by this commit: https://github.com/bitwalker/exrm/commit/4b7d9f2118b446b938a1ca7449c9c3a5d0566556

**Comment by bitwalker** [comment]
Thanks for reporting! This has been fixed in master, should be pushed to hex shortly.

**Comment by romul** [comment]
Thank you for a quick fix.

**Comment by martin-langhoff** [comment]
@romul -- see #302
