### ISSUE TITLE
location of the default sys.config and vm.args in running-config directory

### ISSUE THREAD

**Issue by umatomba** [bitwalker/exrm#166]
The sys.config and vm.args are placed in release directory and used as defaults now (should not be edited). After starting of the release they will be automatically copyed to running-config directory. The  sys.config and vm.args should be placed in running-config directory already before first starting of the release.

**Comment by bitwalker** [comment]
How would this be accomplished? As the location of `running-config` is not known until the boot script runs, and running the boot script means you are running the release, I'm not sure how this is supposed to be done. I'm also a bit unclear on the specific problem, is the current behaviour causing a bug?

**Comment by umatomba** [comment]
No it's not a bug, i just think it could be hard to understand for some people, who don't play with `RELEASE_MUTABLE_DIR`, that before first start the configuration should be done in release folder, and after the start in `running-config` directory. And we know where `running-config` placed per default. Or what do you think about it...?

**Comment by bitwalker** [comment]
I'm going to add this to the documentation rather than try to do anything special here. Users can create the `running-config` directory themselves and populate it with their desired configuration prior to first booting the release.
