### ISSUE TITLE
How to execute a mix command on the running release.

### ISSUE THREAD

**Issue by blisscs** [bitwalker/exrm#169]
Suppose I am developing an application that uses ecto in this case let it be phoenixframework.

After finished the development I do $ mix release , to release the first version.

Then I run a release using. $<path_to_extracted_release_content>/bin/<app_name> start

I wonder how can I run the mix command on the running release.

Suppose that I want to run.  
$ mix ecto.migrate

**Comment by HashNuke** [comment]
@chawladev Hello Chawla ~!
Checkout the details under "Improvements for convenience" section of this blog post http://hashnuke.com/2015/07/19/convenience-hacks-for-using-exrm-with-phoenix-apps.html.
It has the details you need.

If you think that solves the problem, please feel free to close this issue :)

**Comment by chawladev** [comment]
I see it is little confusing here. I have some questions that can help me understand. 
1. When you deploy your code suppose to a different environment. The structure of folder is something like this -
/bin
/erts-7.0
/lib
/log
/releases
/relup
/tmp
Where do I run the mix task here? For example I wan to run mix ecto.migrate. I have tried running in the root folder of this extracted release folder. I have get this issue "** (Mix) The task ecto.migrate could not be found." back

2. If we can't run it anyway. My another question is when we do mix release to create a new release. When we do start a new or upgrade a release. Does start up of that particular release already do the migration for us (Let's talk about the ecto.migrate in this case).

Thank you @HashNuke

**Comment by HashNuke** [comment]
@chawladev if you follow the setup in my blog post about the `SERVER=1` env var, then you can run your mix task in the project's root dir (assuming your server has the project cloned).

**Comment by chawladev** [comment]
No its not the clone of project here that  I am referring about here. I am talking about the exrm release here.

Please have a see the instruction here http://www.phoenixframework.org/docs/advanced-deployment#section-deploying-our-release

I am referring to the extracted release folder here.

**Comment by HashNuke** [comment]
@blisscs I know what you are referring to. But you need the cloned project to run the mix task as per the solution in my blog post. There's no way to run the mix tasks if you only have the release release since the Mix tasks aren't included/compiled in the release.

**Comment by blisscs** [comment]
Thank you @HashNuke
I can understand your point here. 
I am having confusion in the concept of doing releasing here. Why are we creating a release if we have to do the complete clone to the production environment. We could clone it and run mix phoenix.server on the production and do the mix ecto.migrate on the production.

Do you think the same way?

**Comment by HashNuke** [comment]
@blisscs Creating a release allows easier app monitoring & management IMHO. For me it was easier to use `monit` this way.
Besides that, if you don't want to clone remotely, you can migrate the database from your local computer if you have the correct credentials in `config/prod.exs` (`MIX_ENV=prod mix ecto.migrate`). But you'll have to ensure that postgres on the remote server is listening on a port & that the port is accessible from outside world (dangerous but can be secured in some way. I'll skip details).

**Comment by bitwalker** [comment]
@blisscs @HashNuke The real solution for this as far as I see it is to use the Ecto.Migrator API to run migrations in your application startup code based on some config setting. The mix task provided by ecto is there for convenience, but is not necessary for running migrations. 

After quite a bit of discussion in various places, it's quite clear to me that mix tasks are not really compatible with releases, so projects should really not count on them being available in production as a rule. Ecto does not actually require them to be available, but I think there is some confusion around that as it is really the only method currently discussed for performing migrations. I would suggest taking a look at `Ecto.Migrator.run/4`, as that is the API you can use in your application start code to execute migrations if a particular config setting or environment variable is set. I currently do not expect to do anything special in exrm to handle this kind of scenario, but I'm always open to suggestions if they are generally applicable to all projects.

**Comment by blisscs** [comment]
Thank you very much on this @HashNuke @bitwalker 
I will checkout Ecto.Migrator API and try things out from there.
Very appreciated, thank you.
