### ISSUE TITLE
priv/ not bundled on OTP 18.0

### ISSUE THREAD

**Issue by mguillemot** [bitwalker/exrm#173]
First of all, I'm not 100% sure that this is caused by OTP 18.0, but I'm definitely seeing this issue since upgrading to Elixir 1.0.5 and OTP 18.0, both on my Ubuntu Server 64bit and Windows 7 64bit machines.

The issue is simple: the content of the `priv/` directory in your project is not bundled in the release.

I've repro'ed the issue on empty projects with just exrm 0.18.5 and a simple file in priv/, both on Ubuntu Server 64bit and Windows 8.1 64bit.

**Comment by bitwalker** [comment]
@mguillemot Where are you looking for priv? I'm able to find it under `<deploy dir>/lib/<app>-<version>/priv` when testing locally on OTP 18. You can see the test project I'm using [here](https://github.com/bitwalker/exrm-test).

**Comment by bitwalker** [comment]
I'm closing this for now, feel free to reopen it if you have more comments on this!

**Comment by mguillemot** [comment]
D'oh....... You're totally right. For some reason, I was looking at the totally wrong place... Sorry for the false alert, and thanks for the investigation!
