### ISSUE TITLE
config.exs strings are not encoded correctly in utf8 for sys.config

### ISSUE THREAD

**Issue by chime-mu** [bitwalker/exrm#177]
When using a string in utf8 in config/config.exs, the elixir execution works correct. However after making it into a release, the string read from sys.config is no longer in the same utf8 encoding.

Manually editing sys.config to use the string syntax <<"...."/utf8>> solves the problem, but I've found no way to persuade erlang to generate this binary format.

It seems if I pass a third parameter [{:encoding, :utf8}] to :file.write_file the output is different, so maybe that's a solution. I'll try to make small example clearly exposing the problem.

**Comment by bitwalker** [comment]
Fixed in 29f4a7d
