### ISSUE TITLE
Failure with elixir master

### ISSUE THREAD

**Issue by liveforeverx** [bitwalker/exrm#178]
Error on creating release, using elixir master: 

==> Failed to build release. Please fix any errors and try again. Error: {:rlx_app_discovery, [{:unversioned_app, "/Users/dima/personal/elixir/bin/../lib/mix/test/fixtures/archive", :local_sample}]}

Possible solution elixir-lang/elixir#3539

**Comment by liveforeverx** [comment]
@bitwalker thanks! Can you please release 0.18.6 in hex? Thanks in before.

**Comment by bitwalker** [comment]
Can do sir, just a few minutes :)

**Comment by bitwalker** [comment]
Done!
