### ISSUE TITLE
"Failed to build release. Please fix any errors and try again." after some releases

### ISSUE THREAD

**Issue by ftaebi** [bitwalker/exrm#181]
Hi, I got a very similar issue to #118: 
I release 0.0.1 and start it, then I release 0.0.2 and upgrade. Everything works fine. 
The third time I get the following error when I do `mix release`:
```
==> Building release with MIX_ENV=dev.
==> Generating relx configuration...
==> Generating sys.config...
==> Generating boot script...
==> Performing protocol consolidation...
==> Conform: Loading schema...
==> Conform: No schema found, conform will not be packaged in this release!
==> Generating release...
==> Generated .appup for fis_api 0.0.2 -> 0.0.3
==> Failed to build release. Please fix any errors and try again.
```
My mix.exs looks like this:
```
defmodule MyApp.Mixfile do
  use Mix.Project

  def project do
    [app: :my_app,
     version: "0.0.1",
     elixir: ">= 1.0.5",
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps]
  end

  def application do
    [
      mod: { MyApp, [] },
      applications: [:logger, :cowboy]
    ]
  end

  defp deps do
    [
      {:cowboy, "1.0.2"},
      {:exrm, "0.18.1"}
    ]
  end
end
```

**Comment by bitwalker** [comment]
Could you run `mix release --verbosity=verbose`? Also could you update to exrm `0.18.6`? I just did a test with my [exrm-test](https://github.com/bitwalker/exrm-test) project, and was able to generate upgrades for 0.0.1->0.0.2->0.0.3 successfully, so I'd like to narrow down the differences.

**Comment by ftaebi** [comment]
I did run with verbosity:
```
===> Provider (relup) failed with: {error,
                                           {rlx_prv_relup,
                                            {no_upfrom_release_found,
                                             "0.0.2"}}}
==> Failed to build release. Please fix any errors and try again.
```
I have to add that I started the release in the same place it was built and not in a separate directory. Maybe this is still an issue?

**Comment by ftaebi** [comment]
As expected, this happened because I started the releases in the same directory they were created. 
Maybe you should explicitly mention that in the docs because is quite tempting to do it that way.

**Comment by HashNuke** [comment]
@ftaebi most likely related to the issue in this comment https://github.com/bitwalker/exrm/issues/167#issuecomment-122819121. Going by docs, the releases aren't supposed to be "upgraded" in the same place they are created. But the commands in the docs seem outdated too.

**Comment by bitwalker** [comment]
@ftaebi @HashNuke Yeah this has come up enough times now where I'm looking into solutions for it, I do need to update the docs to contain a warning about this though, so I will do that right away. I'm going to close this for now, but be aware that it is something I'm working on.

**Comment by HashNuke** [comment]
@bitwalker I'll try to pitch in by taking some issues off your plate.

**Comment by bitwalker** [comment]
@HashNuke Thanks man, any and all help is very much appreciated :). Ping me if you have any questions on anything!
