### ISSUE TITLE
Error during upgrade: cannot find top supervisor for application <x>?

### ISSUE THREAD

**Issue by mweibel** [bitwalker/exrm#183]
Hope this is the right place to pose a question :) 

I successfully managed to create a release and deployed it. Now I changed some little things and I would like to do an upgrade. I didn't create an `appup` file. 
In the application I have [exometer_core](https://github.com/Feuerlabs/exometer_core) as a dependency which in turn has [setup](https://github.com/uwiger/setup) as a dependency and `setup` is also listed as an application in `exometer_core`. 

Now when I run the upgrade command line I get the following error:

```
./bin/server upgrade "0.2.1"
using /opt/server/releases/0.2.0/server.conf to populate "/opt/server/running-config".
Release 0.2.1 is already unpacked, now installing.
escript: exception error: no case clause matching
                 {error,{'EXIT',{timeout,{sys,get_status,[<7052.2983.0>]}}}}
```

In `console.log` I see the following:

```
2015-08-04 23:52:28.214 [error] <0.1502.0> release_handler: cannot find top supervisor for application setup
```

Do you know what I can do about that without forking either exometer_core or setup? Should I add a appup file which explicitely mentions exometer_core and tell it should just halt & restart it (or something similar)?

Thanks in advance :) Great job you do here!

**Comment by bitwalker** [comment]
@mweibel An appup should've been created for your upgrade release automatically if you didn't generate one yourself, could you look in `rel/<app>/lib/<app>-<version>/` to see if there is an appup file there and gist it if it exists? Could you also verify that in `rel/<app>/releases/<version>` that a relup file exists?

I'm not sure what would produce that error, so I think we'll be doing some digging on this one ;)

**Comment by mweibel** [comment]
obviously now I tried to do various stuff to make it work.. and the first release upgraded now successfully but I can't reproduce the case anymore.. will reopen in case I can :)

thanks anyway ;)

**Comment by bitwalker** [comment]
@mweibel Damn, always hate those kind of bugs. Well if you do stumble on it again, try and open up this issue again if you can find it, that way we can keep related info in one place :)

**Comment by mweibel** [comment]
Could reproduce it now, after fiddling a bit with versions... not sure if related ;)
Anyway, had to sanitize the files a bit, hope it's still readable..

https://gist.github.com/mweibel/06681cc38f737394ed73

server is the application I work on. Should I post any dependency appup or so?

**Comment by mweibel** [comment]
Added a 3rd case clause to install_upgrade.escript in the call to `rpc:call(TargetNode, release_handler, install_release, [Vsn], ?TIMEOUT)` and it logged this output:

```
ERROR: release_handler:install_release failed: {'EXIT',
                                                {timeout,
                                                 {sys,get_status,
                                                  [<7053.1172.0>]}}}
[{erl_eval,match1,4,[{file,"erl_eval.erl"},{line,1087}]},
 {erl_eval,match_tuple,5,[{file,"erl_eval.erl"},{line,1180}]},
 {erl_eval,match_tuple,5,[{file,"erl_eval.erl"},{line,1180}]},
 {erl_eval,match,4,[{file,"erl_eval.erl"},{line,1073}]},
 {erl_eval,match_list,4,[{file,"erl_eval.erl"},{line,1206}]},
 {erl_eval,match_clause,5,[{file,"erl_eval.erl"},{line,982}]},
 {erl_eval,case_clauses,6,[{file,"erl_eval.erl"},{line,941}]},
 {erl_eval,local_func,5,[{file,"erl_eval.erl"},{line,556}]}]
```

well.. not much of a help though ;)

**Comment by mweibel** [comment]
FYI, this time it happened for another app/lib: https://hex.pm/packages/facebook - my own hex package... Which has indeed no supervisor.. wondering why I'd need one though

**Comment by alPacino** [comment]
@mweibel It seems the question is not related to exrm, but to Erlang's SASL release handler functionality (or OTP Design principles for applications, I'm not exactly sure :))

I've recently had the same issue and figured out that the app needs to have supervisor process Erlang to handle upgrade correctly.

Here is my case. I had:
```
defmodule MyApp do
  use Application

  def start(_, _) do
    GenServer.start_link(MyApp.Worker, [])
  end

end

defmodule MyApp.Worker do

  def init(state) do
    # some code
  end

end
```

This worked fine but not for upgrading. What/How I've modified:
```
defmodule MyApp do
  use Application

  def start(_, _) do
    MyApp.Supervisor.start_link([])
  end

end

defmodule MyApp.Supervisor do

  use Supervisor

  def start_link(state) do
    Supervisor.start_link(__MODULE__, state, name: __MODULE__)
  end

  def init(state) do
    children = [
      worker(MyApp.Worker, [state], restart: :permanent)
    ]

    supervise(children, strategy: :one_for_one)
  end

end

defmodule MyApp.Worker do

  def start_link(state) do
    GenServer.start_link(__MODULE__, state, [name: MyApp.Worker])
  end

  def init(state) do
    # some code
    {:ok, state}
  end

end
```

So that's it. Hope this will help :)

**Comment by mweibel** [comment]
@alPacino will try this thanks! However, if the dependency (or the dependency of the dependency) is not in my control, it might be not that easy :/

**Comment by bitwalker** [comment]
As @alPacino found, you do indeed want to have your application start a root supervisor (otherwise you won't have the ability to handle failures properly). I'm still unsure why this occurs, but I'll try and do some reading to find out.

**Comment by alPacino** [comment]
@mweibel agree, but sometimes we should contribute into such dependencies (many of them are hosted on GitHub) like I'm doing right now :). My app depends from lib which doesn't work with exrm properly (including the problem described above). So I'm solving own problem and help others (I hope :)). Sorry for off-topic

**Comment by mweibel** [comment]
@alPacino sure! I do that often actually :) problem is that it's not always treated as necessary from the developer or it's, for the specific case, not even necessary at all. Will try though .. ;)

**Comment by mweibel** [comment]
closing again ;) hopefully this fixed it, but can't yet test really because of some hex issues

**Comment by arnvald** [comment]
Hi everyone! I'm sorry for refreshing the old issue, but it happens I've got the same problem and I don't know how to find out which of the application does not have supervisor. Do I need to check them one by one? `crash.log` file says only:
```
2016-01-20 15:34:58.714 [error] <0.1524.0> release_handler: cannot find top supervisor for application setup
```

**Comment by arnvald** [comment]
Oh my, now I've read it again and I understood that `setup` is the name of the application! I thought that it's just `application setup` phrase

**Comment by arnvald** [comment]
Hi everyone (sorry for the previous comments, I removed them to just leave the necessary information)

I'm having the same issue now, when I try to perform upgrade I get the message about the `setup` application. @mweibel do you remember how you solved it? I tried to use the last release of `setup` but it still causes the error. Is there some for that has it fixed? Thanks in advance!

**Comment by mweibel** [comment]
@arnvald need to check again, didn't work on this (side-)project in a while.. but I think this did the trick:
https://github.com/mweibel/facebook.ex/commit/fd2aab72b50654c8f41cc13dfe58cf0b606e732b
which is a dependency of the project I'm working on.

**Comment by arnvald** [comment]
@mweibel thanks for response! So in the end you didn't have to change anything in the `setup` application?

**Comment by bitwalker** [comment]
@arnvald It looks to me like the `setup` application does not start a root supervisor, rather it directly spawns a process via `proc_lib`. The release handler expects there to be a supervisor tree under an application (by which I mean, something which implements the `application` behaviour), so that appears to be why it fails with `setup`, and likely any other application with a similar setup (like @mweibel's `facebook` application).

The quick solution would be to have the application behaviour start a root supervisor which then does whatever you were starting straight from the application start callback previously. If you look at @mweibel's approach in the link he provided, you'll see what that looks like (in Elixir anyway).

Is `setup` a direct dependency of yours or a transitive one? From what I gather, it's somewhat at odds with using `exrm`, or another release handling tool, but that's just from my brief look. Do you have a specific need for it?

**Comment by arnvald** [comment]
@bitwalker unfortunately it's dependency of `exometer` library which I'm using. That's why I was wondering how @mweibel solved the problem, since he mentioned in the beginning that he was using `exometer` as well.

I opened issue in `setup` repository. For now it seems the only way to make it work is to fork `setup` and change it to start supervisor, and probably I'd have to fork `exometer` as well to use my fork instead of the original one.

**Comment by bitwalker** [comment]
@arnvald No need to fork exometer, just use the `override: true` option for your fork of the `setup` dependency in your `mix.exs` and it will use yours instead of the one specified in the `exometer` mix.exs.

**Comment by arnvald** [comment]
@bitwalker thanks for the hint! With supervisor added to `setup`, and using `override` in my `mix.exs`, upgrades started working.
