### ISSUE TITLE
91f7651 forcing me to use conform?

### ISSUE THREAD

**Issue by d-b** [bitwalker/exrm#184]
I have a project which I'm not using conform for and have no interest in doing so.

Normally while building the release I would see the following:
```
==> Conform: Loading schema...
==> Conform: No schema found, conform will not be packaged in this release!
```

However starting in commit 91f7651878a05174869cfb7b115b04f86f9a0453, conform seems to generate an empty schema file and forces me to use it:
```
==> Conform: Loading schema...
==> Conform: Schema succesfully loaded!
==> Conform: generating test.schema.ez.
```

It appears the regression (if it is one?) occurred in the switch to conform 0.15.1

**Comment by bitwalker** [comment]
This was a bug in conform due to a recent PR, fix was pushed to hex, so this is now fixed in exrm master, should see a new release soon!
