### ISSUE TITLE
Error when deploying Ubuntu build to Debian machine

### ISSUE THREAD

**Issue by jordi-chacon** [bitwalker/exrm#186]
Hi,

I have stumbled upon a weird problem that I have been trying to fix without luck. I'm hoping that you might have a clue and point me in the right direction.

I am generating a release of my Elixir application via `mix release` on an Ubuntu machine. Then I run the binary (from that same machine) and it works just fine.

Then I generate a Docker image which includes the binary. The image is based off debian:jessie and simply installs openssl and sets up locale stuff. Then I fire up a container running that image and execute the binary of my application.

This is what I get:

```
Exec: /service/erts-6.4.1/bin/erlexec -noshell -noinput +Bd -boot /service/releases/0.0.5/facebook_service -mode embedded -config /service/releases/0.0.5/sys.config -boot_var ERTS_LIB_DIR /service/erts-6.4.1/../lib -args_file /service/releases/0.0.5/vm.args -- foreground
Root: /service
{"init terminating in do_boot",{'cannot load',exometer_app,get_files}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
```

I find it very weird and confusing that the same binary work in my Ubuntu machine but not in a fresh Debian. I am completely clueless. So if you have any hints as to what could be the problem, I'd be truly grateful if you let me know.

Thank you!

**Comment by bitwalker** [comment]
This is likely due to the fact that you are including the ERTS from your Ubuntu machine, which was compiled against a different version of SSL. What I would do is create a `relx.config` file under `rel`, with the following:

```erlang
{include_erts, false}.
```

This will then use the ERTS from the environment the release is running in.

Could you give that a try and let me know the results?

**Comment by jordi-chacon** [comment]
Thanks for your reply @bitwalker.

So what you are saying is that the container running my application should have Erlang installed and use its own version of ERTS to run the application? Ideally I would like to avoid that and instead have the binary be fully self-contained, but I can give a try at your suggestion.

Actually, part of the information I posted in my initial post was incorrect, my apologies for this. Let me correct it here:

The build environment which generates the binary is a Docker container with the following Dockerfile:
```
FROM debian:jessie

ENV DEBIAN_FRONTEND="noninteractive" \
  DE_ERLANG="1:17.5.3"

RUN apt-get update -qq && \
    apt-get install -y locales && \
    locale-gen C.UTF-8 && \
    /usr/sbin/update-locale LANG=C.UTF-8 && \
    apt-get remove -y locales
ENV LANG C.UTF-8

RUN mkdir /tmp/erlang-build && \
  cd /tmp/erlang-build && \
  apt-get -y install wget build-essential git && \
  wget http://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb && \
  dpkg -i erlang-solutions_1.0_all.deb && \
  apt-get -y update && \
  apt-get -y -f install erlang-base-hipe=$DE_ERLANG erlang-dev=$DE_ERLANG erlang=$DE_ERLANG erlang-asn1=$DE_ERLANG erlang-common-test=$DE_ERLANG erlang-corba=$DE_ERLANG erlang-crypto=$DE_ERLANG erlang-diameter=$DE_ERLANG erlang-edoc=$DE_ERLANG erlang-eldap=$DE_ERLANG erlang-erl-docgen=$DE_ERLANG erlang-eunit=$DE_ERLANG erlang-gs=$DE_ERLANG erlang-ic=$DE_ERLANG erlang-inets=$DE_ERLANG erlang-megaco=$DE_ERLANG erlang-mnesia=$DE_ERLANG erlang-odbc=$DE_ERLANG erlang-os-mon=$DE_ERLANG erlang-parsetools=$DE_ERLANG erlang-percept=$DE_ERLANG erlang-pman=$DE_ERLANG erlang-public-key=$DE_ERLANG erlang-reltool=$DE_ERLANG erlang-runtime-tools=$DE_ERLANG erlang-snmp=$DE_ERLANG erlang-ssh=$DE_ERLANG erlang-ssl=$DE_ERLANG erlang-ssl=$DE_ERLANG erlang-syntax-tools=$DE_ERLANG erlang-test-server=$DE_ERLANG erlang-toolbar=$DE_ERLANG erlang-tools=$DE_ERLANG erlang-tv=$DE_ERLANG erlang-typer=$DE_ERLANG erlang-webtool=$DE_ERLANG erlang-xmerl=$DE_ERLANG erlang-src=$DE_ERLANG erlang-appmon=$DE_ERLANG erlang-debugger=$DE_ERLANG erlang-dialyzer=$DE_ERLANG erlang-et=$DE_ERLANG erlang-inviso=$DE_ERLANG erlang-observer=$DE_ERLANG erlang-wx=$DE_ERLANG && \
  cd /tmp/erlang-build && \
  git clone https://github.com/elixir-lang/elixir.git && \
  cd /tmp/erlang-build/elixir && \
  git checkout v1.0.4 && \
  make install && \
  cd $HOME && \
  rm -rf /tmp/erlang-build && \
  apt-get clean
```

Once the binary has been generated by the build environment container I pass it on to the running environment container, which has the following Dockerfile:
```
FROM debian:jessie
RUN apt-get update -q -q && apt-get install -y \
  curl \
  locales \
  openssl -qq \
  && locale-gen en_US.UTF-8 en_us \
  && dpkg-reconfigure locales \
  && dpkg-reconfigure locales \
  && locale-gen C.UTF-8 \
  && /usr/sbin/update-locale LANG=C.UTF-8
ENV LANG C.UTF-8
ENV LANGUAGE C.UTF-8
ENV LC_ALL C.UTF-8
RUN mkdir /service
ADD ./rel/facebook_service/facebook_service-*.tar.gz /service
COPY pre_service_launch.sh /service/
EXPOSE 4000
CMD ["/bin/bash", "-c", "source /service/pre_service_launch.sh && /service/bin/facebook_service foreground"]
```

As you can see, both Dockerfiles are based on the same Debian distribution. I just noticed though that I am not installing the `openssl` package within the build environment. I will fix that and see if that fixes the whole problem.

Regarding your suggestion of creating a `relx.config` file, could you please explain when I need to do that? Is it before or after running `mix release`?

Thank you again for your help.

**Comment by jordi-chacon** [comment]
I just edited the Dockerfile of the build environment to install `openssl` and `curl`, just like in the running environment. Now the only difference between the two environments is that one has Erlang and Elixir and the other doesn't. I still get the same error.

**Comment by bitwalker** [comment]
@jordi-chacon Could you post your mix.exs? I'd like to double check something.

**Comment by jordi-chacon** [comment]
Of course. Here it is:

```
defmodule FacebookService.Mixfile do
  use Mix.Project

  def project do
    [app: :facebook_service,
     version: "0.0.4",
     elixir: "~> 1.0",
     elixirc_paths: elixirc_paths(Mix.env),
     compilers: [:phoenix] ++ Mix.compilers,
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps]
  end

  # Configuration for the OTP application
  #
  # Type `mix help compile.app` for more information
  def application do
    [mod: {FacebookService, []},
     applications: [:httpex
                   ],
     included_applications: [:storex
                            ]
    ]
  end

  # Specifies which paths to compile per environment
  defp elixirc_paths(:test), do: ["lib", "web", "test/support"]
  defp elixirc_paths(_),     do: ["lib", "web"]

  # Specifies your project dependencies
  #
  # Type `mix help deps` for examples and options
  defp deps do
    [{:edown, github: "uwiger/edown", tag: "0.7", override: true},
     {:exometer, github: "Feuerlabs/exometer"},
     {:exometer_core, github: "Feuerlabs/exometer_core", override: true},
     {:exrm, "~> 0.18.3"},
     {:httpex, git: "git@github.com:.../httpex", branch: "master"},
     {:lager, git: "git@github.com:basho/lager.git", tag: "3.0.0-RC1", override: true},
     {:meck, "~> 0.8.2", override: true},
     {:storex, git: "git@github.com:.../storex", branch: "master"}]
  end
end
```

**Comment by jordi-chacon** [comment]
In case it matters, I am running `mix release` with MIX_ENV=test. Tomorrow I'll check if the problem also occurs if I use prod instead.

**Comment by jordi-chacon** [comment]
I think this was caused by a bug in my deployment scripts. Will investigate more tomorrow and confirm.

I apologize for having wasted your time. Thank you very much for your support anyway!

**Comment by bitwalker** [comment]
@jordi-chacon I'm pretty sure the cause of the error is because you are missing dependencies in `applications` in the mix.exs for `:facebook_service`. You have:

```elixir
def application do
    [mod: {FacebookService, []},
     applications: [:httpex],
     included_applications: [:storex]
    ]
  end
```

When what you should have is:

```elixir
def application do
    [mod: {FacebookService, []},
     applications: [:edown, :httpex, exometer, exometer_core, :httpex, :lager],
     included_applications: [:storex]
    ]
  end
```

**Comment by jordi-chacon** [comment]
Hi!

I have some news. I have managed to reproduce a very weird behaviour which involves exrm and docker, I am not sure where the problem is though.

I have created a dummy phoenix app to demonstrate the problem: https://github.com/jordi-chacon/dummy_phoenix_app

Simply clone it and run `make test_missing_files`. It creates the binary, creates a Docker image including the binary, and runs the Docker container. Do take a look at the Dockerfile, specially at this part:
```
ADD binary.tar.gz /service1/
COPY binary.tar.gz /service2/
CMD ["/bin/bash", "-c", "tar -xf /service2/binary.tar.gz --directory /service2/ && diff --brief -r /service1 /service2"]
```

The point of this is to demonstrate the weird behaviour: unpacking the tar.gz manually via `tar -xf` and unpacking it through the Docker `ADD` command yield directories which look different, even though they should look the same, unless I am missing something here.

When I run the container I get the following:
```
docker run -it dummy_phoenix_app
Only in /service2: erts-6.4.1
Only in /service2/lib: asn1-3.0.4
Only in /service2/lib/dummy_phoenix_app-0.0.1/priv: static
Only in /service2/lib/exometer-1.1-47-gfc36768/ebin: exometer_app.beam
Only in /service2/lib/exometer-1.1-47-gfc36768/priv: check_edown.script
Only in /service2/lib: goldrush-0.1.6
Only in /service2/lib: idna-1.0.2
```

I have opened an issue in the Docker github page (https://github.com/docker/docker/issues/15799). I have been asked by the Docker guy how the tar.gz is generated so I'd appreciate it if you could answer in that issue and provide a high level description.

Thank you very much!

**Comment by bitwalker** [comment]
@jordi-chacon Sure thing, I'll chime in on that thread. I have Docker locally myself so I'll do some testing when I get some free time as well.
