### ISSUE TITLE
Mix not released with exrm

### ISSUE THREAD

**Issue by jsvisa** [bitwalker/exrm#187]
I'm using `Mix.Config.read!/1` to read my custom config file in my application, seems `exrm` didn't  package `Mix` module with Elixir. So in the release tar, I can't use the functions like `Mix.Config.read!` or others. So what should I have to avoid those situations or I shouldn't use `Mix.Config` to read custom config

**Comment by edgurgel** [comment]
Related: https://github.com/bitwalker/exrm/issues/67

**Comment by jsvisa** [comment]
@edgurgel THANKS

**Comment by jsvisa** [comment]
@edgurgel I just add `mix` in  `included_applications` when released, like below

```Elixir
included_applications: [:mix]
```

This worked for me.

**Comment by bitwalker** [comment]
Mix is not included by default because it's behaviour is not guaranteed to be the same in the context of a release. As @jsvisa pointed out, you can add it as an included application if desired.
