### ISSUE TITLE
Request:  Option to skip tar.gz creation

### ISSUE THREAD

**Issue by cjimison** [bitwalker/exrm#190]
Currently we use exrm for both package creation and running local builds.  It would be great for day to day development to be able to skip creating the tar.gz file because we never use it locally (we do use it when deploying new builds to remote servers) and it just eats up build time.

Thanks!

-Chris

**Comment by bitwalker** [comment]
@cjimison Starting with 0.19.4 when running `mix release --dev` it will skip the packaging step.
