### ISSUE TITLE
generating release fails after upgrading dependency

### ISSUE THREAD

**Issue by manukall** [bitwalker/exrm#191]
using exrm 0.19.2, after upgrading dependencies i sometimes get errors during deployment. i then do `mix release.clean --implode` to start fresh and do a "cold upgrade". this is not optimal of course.

this time, the error i got when running with `verbosity=verbose` was:

```
silent])===> Provider (relup) failed with: {error,
                                           {rlx_prv_relup,
                                            {relup_script_generation_error,
                                             systools_relup,
                                             {file_problem,
                                              {"/home/deployer/projects/gh_forum/rel/gh_forum/lib/plug-1.0.0/ebin/plug.appup",
                                               {error,
                                                {open,
                                                 "/home/deployer/projects/gh_forum/rel/gh_forum/lib/plug-1.0.0/ebin/plug.appup",
                                                 enoent}}}}}}}
```

the new version was basically upgrading my app to a new phoenix version, which included upgrading plug.

**Comment by bitwalker** [comment]
I'm generating appups for dependencies, but it looks like dependencies of dependencies aren't getting caught, hence the error. I probably just need to tweak my dep loading code to make sure the whole tree is walked.

**Comment by keichan34** [comment]
Hey, I know this is already assigned to you, but I thought I'd take a stab at it since it's a pretty big problem for me too.

How does this look? It seems to work over here -- we should probably get some tests in there as well.

https://github.com/keichan34/exrm/commit/0f6be20c24476288f41bad88a8481b8e4d5e4ac6

**Comment by bitwalker** [comment]
Looks good to me! If you send a PR with that change I'll merge it :)

**Comment by manukall** [comment]
this is great. thanks to both of you!
