### ISSUE TITLE
Fails to build on Linux

### ISSUE THREAD

**Issue by brweber2** [bitwalker/exrm#197]
I have an empty project. I add exrm as a dependency and the dependencies are not able to compile on (CentOS 6.5 or Ubuntu 14.04). 

* Elixir
```
Elixir 1.0.5
```

* Erlang
```
Erlang/OTP 18 [erts-7.0] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]
```

```
$ mix deps.compile
==> neotoma (compile)
==> erlware_commons (compile)
ERROR:
===============================================
 You need to install neotoma to compile PEG grammars
 Download the latest tarball release from github
    https://github.com/seancribbs/neotoma
 and install it into your erlang library dir
===============================================

** (Mix) Could not compile dependency erlware_commons, /usr/bin/rebar command failed. If you want to recompile this dependency, please run: mix deps.compile erlware_commons
```

I _DO_ see neotoma in the deps directory so it is there.

Am I doing something wrong?

**Comment by bitwalker** [comment]
Just out of curiosity, does this happen when you run `mix do clean, compile`?

**Comment by brweber2** [comment]
Yes. I've tried every permutation of clean and deps.clean --all etc. I could think of. I tied on a second box wondering if there was something wrong with my VM ... I'm calling it a night for me. I'll be back at it again tomorrow.

**Comment by brweber2** [comment]
The problem may be with erlware_commons (or mix) and not exrm?  If I cd to deps/neotoma and I do rebar compile it works.  It does not work for erlware_commons.  However, if I check out erlware_commons directly on the same machine, it does compile with rebar just fine. (master and the tagged release) This makes me wonder if this is some sort of path issue? 

Do you have any suggestions for additional steps I can try?  

Thanks.

**Comment by bitwalker** [comment]
This is odd, I spun up a new container running Ubuntu 14.04, Erlang 18/Elixir 1.0.5, and I can clone exrm, fetch deps, and compile it just fine. If I create a new project and add it as a dep, same thing. Given that exrm has more Ubuntu users than anything else, I suspect this might be a problem with your rebar installation, could you run the following commands on that machine and let me know the result?

- In the project root: `mix deps.clean --all`
- `rm ~/.mix/rebar`
- `mix do deps.get, compile`

Mix will prompt you to reinstall rebar on the last command. If you had an outdated rebar, then it's possible that's the issue here.

If that isn't it, I'll try with CentOS next and see if it's a problem there.

/cc @tsloughter

**Comment by tsloughter** [comment]
Pretty sure this must be using an old copy of relx. neotoma shouldn't be fetched or used.

**Comment by bitwalker** [comment]
@tsloughter neotoma is used by conform (another dependency of exrm) so it would be fetched whether relx uses it or not. However it does look like I was back a few minor versions (exrm is currently on 3.1.0 and hex is up to 3.5.0). I'll upgrade today.

**Comment by bitwalker** [comment]
@brweber2 exrm 0.19.5 was just published which uses the latest relx, so you can try to see if that also fixes the problem

**Comment by brweber2** [comment]
Ok. It will be a few hours before I get back to a computer but I will try it later tonight. 

Thanks for your help!

**Comment by brweber2** [comment]
I was pretty hesitant to create an issue claiming that this didn't work on "Linux" because that didn't seem likely... :)

So, the problem was rebar, but not ~/.mix/rebar, it was /usr/bin/rebar.  I think it was installed along with Erlang, but I haven't confirmed that yet. I'll spin up a new VM and test it again. If there is anything of consequence I'll note it here.

Thanks again for the help!  I'm closing this issue.  Hopefully it helps someone in the future if they hit the same error.

**Comment by tsloughter** [comment]
@brweber2 did you install from the Erlang Solutions deb package? If so you may have got the "enterprise" version which sadly contains rebar and other third party stuff that is likely to break things.

**Comment by johnhamelink** [comment]
@tsloughter I came across this exact same problem which was caused from installing rebar from erlang-solutions' repo instead of allowing mix to install it for me.

**Comment by bitwalker** [comment]
@johnhamelink You can also run `mix local.rebar --force` to force mix to install rebar for you. Only caveat there is making sure `~/.mix/rebar` is in your PATH before `/usr/local/bin/rebar` or wherever it's installed by default with the Erlang Solutions package.

**Comment by johnhamelink** [comment]
@bitwalker thanks for the tip! Adding to my release script :+1:
