### ISSUE TITLE
Missing Erts folder

### ISSUE THREAD

**Issue by GalaxyGorilla** [bitwalker/exrm#201]
Hi,
 
I have a lot of trouble releasing Elixir apps with exrm after an update to one of the newer commits. Using an old commit from 18. May (2b99889) everything works find. The problem is simply that the erts folder is missing in the release. This has some further impact since the releases with no erts folder seem to use the installed system binaries and hence the boot script (especially the stopping part) does not work properly since the path variables point to the wrong direction and grepping processes via the path variables fails.

I want to point out that this only happens in a certain build environment in a docker container where the erts stuff is properly set up. On my local machine I have no trouble with releases. What I want to ask for are known pitfalls I might have fallen into. Every suggestion is highly appreciated.

EDIT: I'm using the relx 'include_erts' option for cross compiling. I checked that everything is at its right place.

**Comment by GalaxyGorilla** [comment]
According to my understanding exrm should behave with a set 'include_erts' option as follows:

1. {include_etrs, true} -> take the system binaries for erlang from the build host, pack them into the erts folder and use them at runtime. This is the default.
2. {include_etrs, "some_path"} -> take the binaries for erlang from the given path from build host, pack them into the erts folder and use them at runtime
3. {include_etrs, false} -> don't pack the erlang binaries at all and use the system erlang binaries from the runtime host

Please correct me if I'm wrong. The crucial commit here seems to be:
https://github.com/bitwalker/exrm/commit/11228e502895a21d736752cae3f45458ae2f355a

Reverting this I have no problems.

**Comment by bitwalker** [comment]
Actually that commit is unrelated (it incidentally works, but actually would break using a custom ERTS path). I've pushed a fix though. I had some code to identify the proper ERTS to use, but it wasn't being used when re-packaging the release as it should have been.

I'll be pushing a new release shortly. Thanks for reporting!
