### ISSUE TITLE
Elixir 1.1 Support

### ISSUE THREAD

**Issue by gerred** [bitwalker/exrm#203]
Currently, exrm warns about the version on Elixir 1.1. Are there any compatibility issues or should exrm just work with 1.1? If so, mix.exs may need to be updated.

**Comment by bitwalker** [comment]
@gerred exrm's mix.exs currently supports 1.1, as `~> 1.0` means "any version between 1.0 and 2.0, excluding 2.0", but it's possible one of exrm's deps needs to be updated to suppress the warning. In any case, exrm works fine with 1.1 (it's what I'm running right now). I didn't see a warning on my machine when I upgraded, but maybe it was a fluke.

**Comment by gerred** [comment]
Hey @bitwalker,

I got a warning, which is why I opened the issue. Let me retry, because I thought something was messed up with the semver. I'll update with the results.

**Comment by gerred** [comment]
Closed. I had to do a `mix deps.update`
