### ISSUE TITLE
`status` argument to boot script

### ISSUE THREAD

**Issue by jeffweiss** [bitwalker/exrm#205]
As we briefly talked about at ElixirConf, in order to get our app to be properly managed by Puppet (full disclosure: I work for Puppet Labs), we needed a `status` command for the boot script before we could use it as the system init script (don't get me started on sysvinit v. upstartd v. systemd).
For Reasons:tm:, we're only deploying to fairly recent version of Debian, so we could at least use some of the lsb functions.

Our wrapping script to make this work looks like 

``` shell
#! /bin/sh

### BEGIN INIT INFO
# Provides:          thing
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: THING
### END INIT INFO

set -e

. /lib/lsb/init-functions

NAME=thing
DESC="THING"
DEPT="PLACE"
PIDFILE=/opt/$DEPT/$NAME/erlang.pid

do_start() {
  start-stop-daemon -S -p $PIDFILE -q --oknodo --startas /opt/$DEPT/$NAME/bin/thing -- start
}

do_stop() {
  /opt/$DEPT/$NAME/bin/thing stop
  start-stop-daemon -K -p $PIDFILE -q --oknodo --retry 5
}

case "$1" in
    start)
      do_start
      log_daemon_msg "Starting $DESC" "$NAME"
      case "$?" in
        0|1) log_end_msg 0 ;;
        2) log_end_msg 1 ;;
      esac
      ;;
    stop)
      log_daemon_msg "Stopping $DESC" "$NAME"
      do_stop
      case "$?" in
        0|1) log_end_msg 0 ;;
        2) log_end_msg 1 ;;
      esac
      ;;
    restart)
      do_stop
      do_start
      ;;
    status)
      status_of_proc -p $PIDFILE
      ;;
    *)
      /opt/$DEPT/$NAME/bin/thing $1
      ;;
esac
```

This gets fed into `fpm` for the creation of an OS system package with the `--deb-init` flag and the `conform`-generated config file here embedded as `--config-files /opt/#{dept}/#{config[:product]}/releases/#{elixir_version}/#{config[:product]}.conf`. That `elixir_version` is `git describe | cut -d - -f1,3 -`.

If something like this gets pulled into exrm, awesome. If not, no big deal, we have solved this problem for our scenario; this issue is partly to publicly document how we're using exrm releases in native system packages with OS init scripts, with the OS package, service state, and configuration managed by an external CM system (Puppet in our case).

**Comment by bitwalker** [comment]
@jeffweiss Thanks for this! I did some looking after we talked, and I think `ping` should suffice as it works today. If `ping` does not return `ok`, the exit code is non-zero. However I want to make sure that this is enough for your use case. Is zero/non-zero exit code enough? Or would `status` simply wrap `ping` and output `0 | 1` to stdout + set the exit code?
