### ISSUE TITLE
Bug in upfrom version selection

### ISSUE THREAD

**Issue by bitwalker** [bitwalker/exrm#207]
When versions containing extra metadata, such as git sha1s, etc., the version sorter is treating the base version as the latest, i.e. given the following versions:

```
0.0.7
0.0.7-1-g4844472
0.0.7-2-g7712c1b
0.0.7-3-g19a7959
```

Each new version will use `0.0.7` as the upfrom version, rather than the correct variant.

See [this gist](https://gist.github.com/jeffweiss/e92f8013d03f9a662fdc) for additional detail.

/cc @jeffweiss

**Comment by bitwalker** [comment]
@jeffweiss This is fixed in master now

**Comment by jeffweiss** [comment]
💜
