### ISSUE TITLE
Umbrella project Conform.effective doesn't work for exrm (v0.19.6)

### ISSUE THREAD

**Issue by seantanly** [bitwalker/exrm#210]
Putting this up in exrm to for visibility on issue https://github.com/bitwalker/exrm-umbrella-test/issues/3

**Comment by bitwalker** [comment]
Going to close this, since it's a conform specific issue (which has been removed as a direct dependency in exrm in master).

**Comment by seantanly** [comment]
Thanks for the fast response. :)
