### ISSUE TITLE
Current docs are 404ing

### ISSUE THREAD

**Issue by ericmj** [bitwalker/exrm#212]
If you update to ex_doc 0.10.0 and regenerate I think they should work.

**Comment by bitwalker** [comment]
Updated. Thanks!

**Comment by bitwalker** [comment]
@ericmj Actually, even after pushing fresh docs, it's still not working properly. However if I go to the specific version url (0.19.9), it works fine. Thoughts?

**Comment by ericmj** [comment]
You are likely seeing a cached version.

On Wed, Oct 14, 2015 at 10:58 AM, Paul Schoenfelder <
notifications@github.com> wrote:

> @ericmj <https://github.com/ericmj> Actually, even after pushing fresh
> docs, it's still not working properly. However if I go to the specific
> version url (0.19.9), it works fine. Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitwalker/exrm/issues/212#issuecomment-148098146>.
>



-- 
Eric Meadows-Jönsson

**Comment by bitwalker** [comment]
Yeah I thought the same, until it did the same thing in a fresh private browsing window in Chrome. Seems it's cached on the server or something, not locally in my browser.

**Comment by ericmj** [comment]
Yes, it's cached on Cloudflare.

On Wed, Oct 14, 2015 at 11:00 AM, Paul Schoenfelder <
notifications@github.com> wrote:

> Yeah I thought the same, until it did the same thing in a fresh private
> browsing window in Chrome. Seems it's cached on the server or something,
> not locally in my browser.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitwalker/exrm/issues/212#issuecomment-148098795>.
>



-- 
Eric Meadows-Jönsson

**Comment by bitwalker** [comment]
Ah, makes sense, any idea how long it takes for the old cached version to get flushed?

**Comment by ericmj** [comment]
Hard to say, it's very inconsistent. Not more than 2 hours.

On Wed, Oct 14, 2015 at 11:02 AM, Paul Schoenfelder <
notifications@github.com> wrote:

> Ah, makes sense, any idea how long it takes for the old cached version to
> get flushed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitwalker/exrm/issues/212#issuecomment-148099204>.
>



-- 
Eric Meadows-Jönsson

**Comment by bitwalker** [comment]
Cool, thanks Eric!
