### ISSUE TITLE
running-config vm.args being overwritten with release vm.args even when it already exists

### ISSUE THREAD

**Issue by antipax** [bitwalker/exrm#217]
Hey, looks like a recent version of exrm changed some behavior, previously if a vm.args file was present in running-config it would not be overwritten, but this commit:

https://github.com/bitwalker/exrm/commit/a00690a715ea400ec822b95171fc90da9356ae23#diff-1d1853457160bcdb7f539fadfb9efc43R133

seems to have changed the behavior. Should the check for the file existing be for the $GENERATED_CONFIG_DIR rather than the $RELEASE_CONFIG_DIR?

**Comment by kaeNa** [comment]
Yes, we are having the same behaviour for the .conf file which makes it hard (impossible?) to generate and update the config file via template

What is the relations between `$RELEASE_CONFIG_DIR` and `$GENERATED_CONFIG_DIR` and what's the purpose of copying configuration to the `$GENERATED_CONFIG_DIR`?

We are trying to provision our release by generating the configuration file and `vm.args` from a template and now it's not clear if the file should be updated in `releases/...` or `running-config/...`

**Comment by bitwalker** [comment]
@antipax @kaeNa With master or v1 (until I push a new release), you can set `VMARGS_PATH` when booting the release to specify the `vm.args` file you wish to use instead of the one in the release. This var will be checked on start and upgrades/downgrades.
