### ISSUE TITLE
Creating a Phoenix app release for the default application

### ISSUE THREAD

**Issue by mavenastic** [bitwalker/exrm#218]
Hello,

I am trying to deploy the default Phoenix application. Making the release works for both the `dev` and `prod` environments, however it fails to run.

For the `dev` environment, it crashes stating it could not find a config. For the `prod` one, the `console` works fine but after the app starts, I cannot ping it nor run a `remote_console`. I configured database connections for both and created the appropriate databases using `mix ecto.create` and `MIX_ENV=prod mix ecto.create`.

I created a SO question with more details and an example repository.

+ http://stackoverflow.com/questions/33316661/running-a-phoenix-application-release-with-exrm-crashes
+ https://github.com/mavenastic/my_app

Thanks in advance!

**Comment by bitwalker** [comment]
@mavenastic You need to add `server: true` to your `prod.exs` under the config for `MyApp.Endpoint`. This is how Phoenix starts itself within a release. With Phoenix, I would recommend always using `MIX_ENV=prod` for releases, `MIX_ENV=dev` has a lot of development specific features (such as code reloading), that simply won't work within a release. If you are getting config errors, it's probably because you are missing some required Phoenix configuration in your environment-specific file. You can test this by running `MIX_ENV=prod mix compile` to see if it compiles successfully. You can also build your release with `--verbosity=verbose` to get detailed output for tracing down problems.

The above is also why you couldn't ping or console to the release, because it failed on startup.

**Comment by mavenastic** [comment]
Thank you for your answer and detailed explanations @bitwalker. I unfortunately already tried to add `server: true` to the production configuration, without success.

Here are the steps I am following from the default Phoenix 1.0.3 application:

  + Configure the connection to the production database in `config/prod.secret.exs`

  + Add `server: true` to `config/prod.exs`

I obtain the following:

    config :my_app, MyApp.Endpoint,
      http: [port: {:system, "PORT"}],
      url: [host: "example.com", port: 80],
      cache_static_manifest: "priv/static/manifest.json",
      server: true

  + Add `{:exrm, "~> 0.19.9"}` to the deps in `mix.exs`

At this point, I have:

    def application do
      [
        mod: {MyApp, []},
        applications: [
          :phoenix, :phoenix_html, :cowboy, :logger, :phoenix_ecto, :postgrex
        ]
      ]
    end

    defp deps do
      [
        {:phoenix, "~> 1.0.3"},
        {:phoenix_ecto, "~> 1.1"},
        {:postgrex, ">= 0.0.0"},
        {:phoenix_html, "~> 2.1"},
        {:phoenix_live_reload, "~> 1.0", only: :dev},
        {:cowboy, "~> 1.0"},
        {:exrm, "~> 0.19.9"}
      ]
    end

I don't see any production dependency not listed in the `application` function.

  + Run `MIX_ENV=prod mix do deps.get, deps.compile`

I get a warning, but it compiles fine.

    WARN:  Missing plugins: [rebar3_hex]

  + Run `MIX_ENV=prod mix compile`
  + Run `MIX_ENV=prod mix ecto.create` (the database is successfully created)
  + Run `MIX_ENV=prod mix phoenix.digest`
  + Run `MIX_ENV=prod PORT=9876 mix release --verbosity=verbose`

You can find the result of the last command [here](https://gist.github.com/mavenastic/6793c27d6810b397778b).

I then try to run:

    ./rel/my_app/bin/my_app start
    ./rel/my_app/bin/my_app ping

I obtain:

    Node 'my_app20@127.0.0.1' not responding to pings.

Is there something obvious I am missing?

Thanks!

**Comment by bitwalker** [comment]
One thing to note is that providing the `PORT` environment variable needs to be done at runtime, not when building the release, so you'd do `PORT=9876 ./rel/my_app/bin/my_app`.

Could you run `./rel/my_app/bin/my_app foreground` and paste the output here?

**Comment by mavenastic** [comment]
Thanks @bitwalker. I was indeed not specifying the port as I thought it was used at release build time.

Using `foreground` works:

    PORT=8362 rel/my_app/bin/my_app foreground
    Using /vagrant/my_app/rel/my_app/releases/0.0.1/my_app.sh
    Exec: /vagrant/my_app/rel/my_app/erts-7.1/bin/erlexec -noshell -noinput +Bd -boot /vagrant/my_app/rel/my_app/releases/0.0.1/my_app -mode embedded -config /vagrant/my_app/rel/my_app/running-config/sys.config -boot_var ERTS_LIB_DIR /vagrant/my_app/rel/my_app/erts-7.1/../lib -pa /vagrant/my_app/rel/my_app/lib/consolidated -env ERL_LIBS /vagrant/my_app/rel/my_app/lib -args_file /vagrant/my_app/rel/my_app/running-config/vm.args -- foreground
    Root: /vagrant/my_app/rel/my_app
    14:56:27.254 [info] Running my_app.Endpoint with Cowboy on http://example.com:8362
    14:56:31.563 request_id=3qlpjklmu3ml9u3ulalqfcvmjn3llnan [info] GET /
    14:56:31.563 request_id=3qlpjklmu3ml9u3ulalqfcvmjn3llnan [info] Sent 200 in 227µs

    curl http://127.0.0.1:8362
    Returns HTML from index page

Using `start` does not:

    PORT=8362 rel/my_app/bin/my_app start
    Using /vagrant/my_app/rel/my_app/releases/0.0.1/my_app.sh

    PORT=8362 rel/my_app/bin/my_app ping
    Using /vagrant/my_app/rel/my_app/releases/0.0.1/my_app.sh
    Node 'my_app@127.0.0.1' not responding to pings.

    curl http://127.0.0.1:8362
    curl: (7) Failed to connect to 127.0.0.1 port 8362: Connection refused

**Comment by bitwalker** [comment]
@mavenastic Could you use `exrm` master, and build your release again? It no longer suppresses error output from commands, so if there is something failing in `start` we should get more details. I'm not sure why foreground would work but start would not, but hopefully this will get us closer to figuring it out.

**Comment by mavenastic** [comment]
Using `master` fixed the issue. Many thanks @bitwalker.

**Comment by PotterDai** [comment]
I have the same problem. Only when using foreground, it successfully started the server.

**Comment by bitwalker** [comment]
@PotterDai Is that with the latest version of exrm? Could you paste the logs from when you run `./bin/myapp start`? There should be a `log` directory with two log files: `erlang.log.N` and `run_erl.log`.

**Comment by PotterDai** [comment]
@bitwalker  thank you for response. By using exrm master the problem just got solved!

BTW may I ask another question while using exrm? 
Is there a way not only passing PORT argument, but also passing NODE_NAME argument to define the node name? Since it's quite useful when clustering through elixir. Thank you if you got any suggestions!

**Comment by bitwalker** [comment]
@PotterDai Just edit `vm.args` or provide your own in `rel/vm.args`, if you look at the generated one, you'll see how it's done :)

**Comment by johnhamelink** [comment]
Hi there,

I'm using exrm on master and I still have this issue on my dev environment:

```
Using /Users/john/Public/fap/api/api_v2.1/rel/api/releases/0.0.1/api.sh
Exec: /Users/john/Public/fap/api/api_v2.1/rel/api/erts-7.2.1/bin/erlexec -boot /Users/john/Public/fap/api/api_v2.1/rel/api/releases/0.0.1/api -boot_var ERTS_LIB_DIR /Users/john/Public/fap/api/api_v2.1/rel/api/erts-7.2.1/../lib -env ERL_LIBS /Users/john/Public/fap/api/api_v2.1/rel/api/lib -config /Users/john/Public/fap/api/api_v2.1/rel/api/running-config/sys.config -pa /Users/john/Public/fap/api/api_v2.1/rel/api/lib/api-0.0.1/consolidated -args_file /Users/john/Public/fap/api/api_v2.1/rel/api/running-config/vm.args -user Elixir.IEx.CLI -extra --no-halt +iex -- console
Root: /Users/john/Public/fap/api/api_v2.1/rel/api
/Users/john/Public/fap/api/api_v2.1/rel/api
Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

{"Kernel pid terminated",application_controller,"{application_start_failure,api,{{shutdown,{failed_to_start_child,'Elixir.Api.Endpoint',{shutdown,{failed_to_start_child,'Elixir.Phoenix.CodeReloader.Server',{undef,[{'Elixir.Mix.Project',config,[],[]},{'Elixir.Phoenix.CodeReloader.Server',init,1,[{file,\"lib/phoenix/code_reloader/server.ex\"},{line,32}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,240}]}]}}}}},{'Elixir.Api',start,[normal,[]]}}}"}

Crash dump is being written to: erl_crash.dump...done
Kernel pid terminated (application_controller) ({application_start_failure,api,{{shutdown,{failed_to_start_child,'Elixir.Api.Endpoint',{shutdown,{failed_to_start_child,'Elixir.Phoenix.CodeReloader.S
```


A copy of the erl_crash.dump file: [erl_crash.dump.txt](https://github.com/bitwalker/exrm/files/89718/erl_crash.dump.txt)

**Comment by bitwalker** [comment]
@johnhamelink This looks like you build the release with `MIX_ENV=dev`, and the phoenix code reloader is enabled (but `phoenix_live_reload` is not in the applications list in your `mix.exs`). I would take a look at [this guide for exrm + phoenix](http://www.phoenixframework.org/docs/advanced-deployment) for a good walkthrough on using exrm with phoenix apps.

**Comment by johnhamelink** [comment]
:+1: thanks!
