### ISSUE TITLE
release.clean does not remove all release files

### ISSUE THREAD

**Issue by eproxus** [bitwalker/exrm#223]
The `release.clean` target leaves among other things, the `bin`, `erts-X.X`, `lib` and `releases` folders inside the `rel/<name>` folder.

**Comment by lermannen** [comment]
I'd like to take a stab at fixing this. Anything you want me to to think about?

**Comment by eproxus** [comment]
In my opinion, everything that is generated (links, copied files, compiled code etc.). We had a few problems building new releases because of what's left inside that folder (cannot recall exactly at the moment, but it was exrm printing out some error, and then working once we manually deleted everything).

**Comment by bitwalker** [comment]
@eproxus Those folders are left because you may have previous releases you don't want cleaned (you would lose the ability to upgrade from them). However, I think `bin` should be removed, since it is not necessary for previous releases.

**Comment by eproxus** [comment]
Then perhaps a special clean target or a `--all` flag (or similar) would be an option? For projects that don't deal with release upgrades.

**Comment by bitwalker** [comment]
@eproxus In that case, why not just use `mix release.clean --implode --no-confirm`? If you don't care that everything will be blown away, that's what you should use.

**Comment by eproxus** [comment]
Oh, didn't know that existed. Thanks.

I'll keep an eye on the whole thing, and see if I can reproduce the case where I actually wasn't able to create a new release at all. Until further notice, I'll close this issue.
