### ISSUE TITLE
osx DS_Store error

### ISSUE THREAD

**Issue by plamb** [bitwalker/exrm#224]
This caused me some confusion but seems to be limited to OSX. When generating a new release build on OSX 10.11.1 I get an error like the following:

``` shell
...
==> Generating appups for dependencies in the prod environment...
==> Checking neotoma..
==> Unable to access /project/path/rel/chat_app/releases/.DS_Store/chat_app.rel: enotdir
```

**Comment by bitwalker** [comment]
@plamb Thanks for reporting! Looks like I need to add a filter to check if a release directory is actually valid.
