### ISSUE TITLE
Moving build machines

### ISSUE THREAD

**Issue by midas** [bitwalker/exrm#226]
I began building my production application on a local laptop.  Now I have set up a staging server that I will use to build both staging and production on.  The production app is currently on release 1.3.1.  The next release will be 1.4.0.  However, the new machine does not have any of the prior releases that were built locally on my laptop.  Thus, I am assuming the build will not create some of the release files correctly (ie. app.up, RELEASES).

What is the easiest process I can employ to handle this situation?

Some possibilities I have thought of:

* scp the entire rel directory from my local machine to the staging.build server
* manually edit the output of this first build prior to deployment/upgrade (although I do not know what files I would need to edit)

Thanks!

**Comment by bitwalker** [comment]
@midas Copying your local rel folder is probably the easiest path, but you can get rid of any releases under `releases` prior to `1.3.1`, as all that's needed for the appup is the last release and it's code files from `lib`.
