### ISSUE TITLE
Hot upgrade does not upgrade consolidated protocols

### ISSUE THREAD

**Issue by ThijsWouters** [bitwalker/exrm#232]
When I upgrade to a next version, consolidated protocols which have changed are not updated to the next version. Protocols that are new are added to `lib/consolidated`.

I tried this with my master branch: http://github.com/ThijsWouters/exrm.git.

**Comment by bitwalker** [comment]
Testing with master locally appears to work as expected for me. Could you provide me with steps to reproduce?

**Comment by ThijsWouters** [comment]
I provided a [project](https://github.com/ThijsWouters/exrm_bug_232) for you.

1. Unpack version 0.0.1,
2. Start the application and remote console,
3. `ExrmBug_232.test`
```
test
:ok
```
4. Upgrade to version 0.0.2,
5. `ExrmBug_232.test`
```
test
** (Protocol.UndefinedError) protocol String.Chars not implemented for %ExrmBug_232{}
    (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir) lib/string/chars.ex:17: String.Chars.to_string/1
    (elixir) lib/io.ex:429: IO.puts/2
```

**Comment by ThijsWouters** [comment]
But while I was creating that project. I noticed that when I was testing it with iex, it also did not update the consolidated protocols.

Maybe this is an issue with mix?

**Comment by ThijsWouters** [comment]
This is not an issue with mix. I was consolidating protocols in dev. When I build and test in prod, it works.

**Comment by ThijsWouters** [comment]
I have tested this bug in the prod environment. The issue remains.

I have added a branch to the test project: [prod_release](https://github.com/ThijsWouters/exrm_bug_232/tree/prod_release).

**Comment by bitwalker** [comment]
@ThijsWouters Figured it out finally, I've pushed a fix to master, could you test and let me know if it works for you? I would recommend starting from a clean slate (i.e. blow away `rel` or `mix release.clean --implode --no-conform`)

**Comment by ThijsWouters** [comment]
Yes, it is working.
Thanks.
