### ISSUE TITLE
RFC: optionally create .iso images in addition to / instead of .tar.gz 

### ISSUE THREAD

**Issue by igalic** [bitwalker/exrm#234]
I've been recently investigating how to get a phoenix-framework project booted on [rumpkernel](https://github.com/rumpkernel/wiki/wiki/Info%3A-FAQ), and exrm seemed the perfect choice.
however, directly to convert a .tar.gz with genisoimage is impossible, so it's always a chore.
it would be nice if we could just make it a config option!

**Comment by bitwalker** [comment]
@igalic I'm interested, what do you need on the exrm side for that?

**Comment by igalic** [comment]
@bitwalker right now, exrm creates the tar.gz
i'd like it to create an .iso (too|instead)

**Comment by bitwalker** [comment]
@igalic Right, however what is the cross platform way of creating an iso? I think this is a better fit for an exrm plugin, rather than a built-in feature.

**Comment by igalic** [comment]
aah, that would make sense…!

**Comment by bitwalker** [comment]
@igalic I'm going to close this for now, but if you find you need something from exrm in order to support this feature as a plugin, please open a new one with what you need!
