### ISSUE TITLE
No app.tar.gz getting generated

### ISSUE THREAD

**Issue by cjimison** [bitwalker/exrm#235]
When I generate a release using the 0.19.9 release I am not getting a tar.gz file.

I am just creating a sample umbrella project
I run the following commands in one of my apps

```
MIX_ENV=prod mix release
```

I see the release was created and it works fine, however there is no tar.gz file.  Is there a new option I need to pass in to generate the tar.gz file?

This is also making release updates a bit of a problem :)

Thanks!

**Comment by cjimison** [comment]
Also I am running Elixir 1.1 with Erlang 18

**Comment by cjimison** [comment]
Also tried the test app and did not get a .tar.gz file:

https://github.com/bitwalker/exrm-umbrella-test.git

**Comment by cjimison** [comment]
Never mind .. it move .. should have done a find first I guess :P

New folder home is in the releases folder under the current (rel/<appname>/release/0.0.1/<appname>.tar.gz)

**Comment by bitwalker** [comment]
@cjimison Yes sorry about the confusion, that change was made a while back for a few different reasons. If there are places in the documentation that haven't been updated let me know!
