### ISSUE TITLE
Permission error in .erlang.cookie causes silent upgrade failure

### ISSUE THREAD

**Issue by cjimison** [bitwalker/exrm#236]
This is a WAY low priority issue but it was a real head scratcher to figure out.  Just thought I would throw it out there in case someone bumps into it in the future.

Somehow I screwed up the permissions on my `.erlang.cookie` file.  My guess is I got too excited about the latest exrm and I must have sudo run an instance of my servers, but I am not sure.

This was never a problem for me locally because I would just stop and start my development server ... until I decided to test upgrading a deployment.

All I would see is some output like:

```
Using /Users/username/path_to_app/tmp/releases/0.0.2/app_name.sh
```

and that was it.  The upgrade would not work, and tears would start falling from the corners of my eyes.  Because of the lack of output I thought I was just copying the wrong file, didn't get the right relup file generated, etc, etc.

I finally did some digging into the sh file and found the problem here:

```
upgrade|downgrade|install)
        if [ -z "$2" ]; then
            echo "Missing package argument"
            echo "Usage: $REL_NAME $1 {package base name}"
            echo "NOTE {package base name} MUST NOT include the .tar.gz suffix"
            exit 1
        fi

        # Make sure a node IS running
        echo "Am I running?"
        relx_nodetool "ping" > /dev/null
        echo "Not sure yet .."
        exit_status=$?
        if [ "$exit_status" -ne 0 ]; then
            echo "Node is not running!"
            exit $exit_status
        fi
        echo "Yes I am .. JOY!"
```

In this case I would see my debug text of `Am I running` but nothing else after that.  I commented out the `relx_nodetool "ping" > /dev/null` call and the if block after, and then I started getting a bunch of errors around permissions and loading my local `.erlang.cookie` file.

I deleted the file and tried again (with the removed code added back) and my upgrade work.  Not sure if there is anything that can be done to catch this but if so it would have saved me about 4 hours and a bunch of hair would still be on my head :)

I would also recommend adding to the docs in the "Upgrades and Downgrades" section what a successful upgrade should output to the TTY.

I am not trying to sound ungrateful for an awesome (and free) product.  Just hoping to help the next person who may run into this.

-Chris

**Comment by bitwalker** [comment]
@cjimison This is great information, thank you! I'll see what I can do about being able to print this type of error in the output when it occurs rather than suppressing it. I can also update the docs.
