### ISSUE TITLE
detect erlang dependencies

### ISSUE THREAD

**Issue by helios** [bitwalker/exrm#239]
Hi, 
I was "releasing" an application that uses :eldap and :eldap depends on :asn1
I had to run the app, get the error and try to understand the errore that was 

    {:error, {:asn1, :undef}}

In dev it was not possible to replicate the error, because I suspect that elixir  loads all the modules. In production/release erlang modules are not included by default, isn't it ?

Is it possible to detect the erlang dependencies at compile time ?

Adding the erlang dependencies :eldap, :asn1 in the application solved the issue.
Thanks.
--
Ra

**Comment by bitwalker** [comment]
@helios I'm building this out right now, thankfully it was easier than I expected, though still a bit of a challenge. I'll update this thread when it's in master :)
