### ISSUE TITLE
Exrm hot upgrades in autoscaled environments

### ISSUE THREAD

**Issue by maxim** [bitwalker/exrm#240]
Say you're on AWS and your servers are in autoscale group. When more servers are needed, AWS just adds them. So questions.
### What happens when new servers are added?

Couple of options.

1) When you deploy a release, you also create an image (AMI) and amazon knows to build all new servers from that image.
2) You create a user-data bash script, which pulls your exrm .tar.gz from a known location and installs it. AWS automatically runs it on all new servers.

Let's say you used one of these and AWS started 2 servers for you.
### What happens when you deploy a new release?

Again, couple of options.

1) You create a new AMI image and do a rolling upgrade (stop old servers, start new ones), completely ignoring elixir's hot upgrade facilities.
2) You use some way (doesn't matter which) to tell all machines to pull the new version and run "bin/my_app upgrade [version]", hence taking advantage of hot upgrades.

_~ 2 days later ~_

There was increase in load, and AWS started a 3rd server for you.

If you followed #1 choices above, then that new server will have the same data as the rest of them, they all came up from the same AMI.

If you followed #2 choices, then that new server will have 1 latest release only, while the other 2 servers already have 2 releases in them.
### What happens when you need to downgrade?

If you go by choices #1 - you simply do a rolling downgrade, just like upgrade, where you completely ignore hot code reloading, and just use AMI images with older releases.

If you go by choices #2 - and tell all your servers "now run bin/my_app downgrade [prev_version]" - two of them will succeed (the older ones) and the latest one will fail, because it doesn't have previous release.

So the main question is - how do you take advantage of hot upgrades in autoscaled environments?

**Comment by tsloughter** [comment]
Rolling back to a version is (with regards to what is run by the `downgrade` script) is no different from an upgrade. It can and should be treated the same from a deployment point of view regarding fetching releases. So downgrading to `prev_version` would pull down `prev_version` if it didn't already exist (you'd also not want to download `next_version` if it was already there when doing an upgrade) and run the `downgrade`.

**Comment by maxim** [comment]
@tsloughter That might work. Does exrm do the same thing on downgrade as far as "I can't find the release, trying to unpack [tar.gz file]" as it does on upgrade?

**Comment by tsloughter** [comment]
Yes, `downgrade` and `upgrade` are actually just calls to `install`. https://github.com/bitwalker/exrm/blob/master/priv/rel/files/install_upgrade.escript#L38

**Comment by maxim** [comment]
@tsloughter Awesome! I'll report back if I run into any more issues. If not, will probably write this whole thing up in a blog post.
