### ISSUE TITLE
No error displayed

### ISSUE THREAD

**Issue by ThijsWouters** [bitwalker/exrm#242]
I have an error when I am releasing. Exrm fails with a status code of 1, but there is no output.

Is it possible to have more error logging?

**Comment by ThijsWouters** [comment]
When I run it with `--verbosity verbose` it does show the error.

**Comment by bitwalker** [comment]
@ThijsWouters Could you paste the error you got when running with `--verbosity=verbose`? Errors should be displayed even when logging is quiet, so chances are the error is being swallowed somewhere incorrectly.

**Comment by ThijsWouters** [comment]
I no longer have that error. But it was complaining that I had two modules with the same name.

**Comment by bitwalker** [comment]
@ThijsWouters If you see it again, can you update this thread with the verbose log? It'll help me track down whether or not this is a bug or something expected.

**Comment by ThijsWouters** [comment]
Now it is even worse. I don't get any error now.
`MIX_ENV=prod mix release`:
```
==> exrm
Compiled lib/exrm/config.ex
Compiled lib/exrm/plugin.ex
Compiled lib/exrm/utils/logger.ex
Compiled lib/exrm/deps.ex
Compiled lib/exrm/plugins/appups.ex
Compiled lib/exrm/utils/utils.ex
Compiled lib/exrm/plugins/consolidation.ex
Compiled lib/mix/tasks/release.plugins.ex
Compiled lib/mix/tasks/release.clean.ex
Compiled lib/exrm/appups.ex
Compiled lib/mix/tasks/release.ex
Generated exrm app
Building release with MIX_ENV=prod.
This is an upgrade, verifying appups exist for updated dependencies..
==> All dependencies have appups ready for release!
```
Return code = 1.

`MIX_ENV=prod mix release --verbosity=verbose`:
```
Building release with MIX_ENV=prod.
==> Generating relx configuration...
==> Generating sys.config...
==> Generating boot script...
==> Packaging consolidated protocols...
This is an upgrade, verifying appups exist for updated dependencies..
==> All dependencies have appups ready for release!
==> Generating release...
```
Return code = 1.

In both cases no release is generated.

**Comment by ThijsWouters** [comment]
These are the changes that were done:
```
  new file:   rel/files/boot
  new file:   rel/files/boot.bat
  new file:   rel/files/boot_shim
  new file:   rel/files/boot_shim.bat
  new file:   rel/files/relx.config
  new file:   rel/files/sys.config
  deleted:    rel/timesheet/releases/RELEASES
  deleted:    rel/timesheet/releases/start_erl.data
  deleted:    rel/timesheet/relup
```

**Comment by ThijsWouters** [comment]
When I first compile, it works. I'll open a different issue for that.
But it could be that it helps you find the source of why no error is displayed.

**Comment by bitwalker** [comment]
@ThijsWouters Very strange, this seems like a new error which isn't being handled properly. Just to make sure I'm trying to reproduce with the same versions of everything, are you testing with exrm master (and if you are using conform, master of conform as well?). Strictly speaking you don't need to be, just trying to make sure we're working with the same code. Also, are you performing this build on OSX, Ubuntu/Debian, some other platform?

Sorry for all the questions, it seems like you've hit some combination of things that's causing issues I haven't yet been able to reproduce.

**Comment by ThijsWouters** [comment]
I am using https://github.com/bitwalker/exrm/commit/372921ea8499cd58f0a6fe9b5dbf5ec818610f93. I updated yesterday morning.
I don't use conform.
I'm building on Ubuntu 15.04.
Elixir 1.1.1, Erlang/OTP 18, Erts 7.1.
This is a project with Phoenix 1.0.3.
I'm building with MIX_ENV=prod.

**Comment by aaronjensen** [comment]
I was able to get past the error. Here's my new mix.lock: 

```
%{"bbmustache": {:hex, :bbmustache, "1.0.3"},
  "combine": {:hex, :combine, "0.6.0"},
  "conform": {:git, "https://github.com/bitwalker/conform.git", "2225c9865310c6690b7ce144c330f722c017ffcc", []},
  "cors_plug": {:hex, :cors_plug, "0.1.4"},
  "cowboy": {:hex, :cowboy, "1.0.4"},
  "cowlib": {:hex, :cowlib, "1.0.2"},
  "dogma": {:hex, :dogma, "0.0.11"},
  "edeliver": {:git, "https://github.com/substantial/edeliver.git", "64e3741e8510eba22f9cbbf6399f6ecfc693ff15", [branch: "do-compile"]},
  "erlware_commons": {:hex, :erlware_commons, "0.15.0"},
  "exactor": {:hex, :exactor, "2.2.0"},
  "exjsx": {:hex, :exjsx, "3.2.0"},
  "exrm": {:hex, :exrm, "1.0.0-rc6"},
  "exsyslog": {:hex, :exsyslog, "1.0.1"},
  "exvcr": {:git, "https://github.com/substantial/exvcr.git", "3c365b0c98d6ccd2d24e3e6e54c577cf282d1b8d", [branch: "use-marshal-serializer-with-hackney"]},
  "getopt": {:hex, :getopt, "0.8.2"},
  "hackney": {:hex, :hackney, "1.3.2"},
  "httpoison": {:hex, :httpoison, "0.7.5"},
  "idna": {:hex, :idna, "1.0.2"},
  "jsx": {:hex, :jsx, "2.6.2"},
  "meck": {:hex, :meck, "0.8.3"},
  "neotoma": {:hex, :neotoma, "1.7.3"},
  "phoenix": {:hex, :phoenix, "1.0.4"},
  "plug": {:hex, :plug, "1.0.3"},
  "poison": {:hex, :poison, "1.5.0"},
  "providers": {:hex, :providers, "1.4.1"},
  "ranch": {:hex, :ranch, "1.2.0"},
  "raygun": {:git, "https://github.com/aaronjensen/raygun.git", "6f00c1b8404554eeca08c3928149d7ed0395bf02", [branch: "patch-1"]},
  "relx": {:hex, :relx, "3.5.0"},
  "ssl_verify_hostname": {:hex, :ssl_verify_hostname, "1.0.5"},
  "sweet_xml": {:git, "https://github.com/substantial/sweet_xml.git", "1136aae6854bf63c6644cbdb8b81ccd6df77c6ab", [branch: "fix-xml-entities-splitting-strings"]},
  "syslog": {:hex, :syslog, "1.0.2"},
  "timex": {:hex, :timex, "0.19.5"},
  "tirexs": {:hex, :tirexs, "0.6.1"},
  "tzdata": {:hex, :tzdata, "0.5.5"},
  "xml_builder": {:hex, :xml_builder, "0.0.6"}}
```

Unfortunately, it's hard to say what actually fixed it. I had to add a `mix compile` to edeliver and I cleaned up my dependencies some.

**Comment by bitwalker** [comment]
There's been an issue in the `1.0.0-rc` series since `rc2` I found, when using `conform` in conjunction with `exrm`, which may have caused problems for you, or perhaps not, but if you update to the latest conform and exrm, add `override: true` to those two deps, and then add a dep for `{:conform_exrm, "~> 0.1"}`, this is now the required way to get conform and exrm to interoperate while keeping the two projects independent in a way that does not cause issues.

**Comment by aaronjensen** [comment]
@bitwalker I'm seeing this after following your instructions:

```
[21:01:32][Step 1/1] lib/mix/tasks/conform.archive.ex:1: warning: redefining module Mix.Tasks.Conform.Archive
[21:01:32][Step 1/1] Compiled lib/mix/tasks/conform.archive.ex
[21:01:32][Step 1/1] lib/mix/tasks/conform.configure.ex:1: warning: redefining module Mix.Tasks.Conform.Configure
[21:01:32][Step 1/1] Compiled lib/mix/tasks/conform.configure.ex
[21:01:32][Step 1/1] lib/mix/tasks/conform.effective.ex:1: warning: redefining module Mix.Tasks.Conform.Effective
[21:01:32][Step 1/1] Compiled lib/conform/translate.ex
[21:01:32][Step 1/1] lib/mix/tasks/conform.new.ex:1: warning: redefining module Mix.Tasks.Conform.New
[21:01:32][Step 1/1] Compiled lib/mix/tasks/conform.effective.ex
[21:01:32][Step 1/1] Compiled lib/mix/tasks/conform.new.ex
[21:01:32][Step 1/1] lib/mix/tasks/conform.release.ex:1: warning: redefining module Mix.Tasks.Conform.Release
[21:01:32][Step 1/1] Compiled lib/mix/tasks/conform.release.ex
``` 

Things seem to work, just pointing it out.

**Comment by bitwalker** [comment]
@aaronjensen Yeah this occurs when conform compiles it's escript, conform is already loaded, but the compile task is forcing them to be recompiled, which redefines the one already loaded. It doesn't actually affect anything, but it is annoying to see in the logs. Not sure if it's worth running that task quiet or leaving it as-is honestly.

**Comment by olivermt** [comment]
I am also getting this error.

Elixir 1.2, ubuntu 14.04 and erlang18. Both elixir and erlang instsalled through the erlang-solutions packages.

My mix.lock:
```
%{"bbmustache": {:hex, :bbmustache, "1.0.3"},
  "certifi": {:hex, :certifi, "0.3.0"},
  "combine": {:hex, :combine, "0.7.0"},
  "comeonin": {:hex, :comeonin, "2.0.0"},
  "connection": {:hex, :connection, "1.0.2"},
  "corsica": {:hex, :corsica, "0.4.0"},
  "cowboy": {:hex, :cowboy, "1.0.4"},
  "cowlib": {:hex, :cowlib, "1.0.2"},
  "decimal": {:hex, :decimal, "1.1.1"},
  "earmark": {:hex, :earmark, "0.2.0"},
  "ecto": {:hex, :ecto, "1.1.1"},
  "erlware_commons": {:hex, :erlware_commons, "0.15.0"},
  "ex_doc": {:hex, :ex_doc, "0.11.3"},
  "exq": {:hex, :exq, "0.6.1"},
  "exrm": {:hex, :exrm, "1.0.0-rc7"},
  "fs": {:hex, :fs, "0.9.2"},
  "gen_smtp": {:hex, :gen_smtp, "0.9.0"},
  "getopt": {:hex, :getopt, "0.8.2"},
  "hackney": {:hex, :hackney, "1.4.7"},
  "httpoison": {:hex, :httpoison, "0.8.0"},
  "idna": {:hex, :idna, "1.0.2"},
  "mimerl": {:hex, :mimerl, "1.0.2"},
  "phoenix": {:hex, :phoenix, "1.1.2"},
  "phoenix_ecto": {:hex, :phoenix_ecto, "2.0.0"},
  "phoenix_html": {:hex, :phoenix_html, "2.2.0"},
  "phoenix_live_reload": {:hex, :phoenix_live_reload, "1.0.2"},
  "plug": {:hex, :plug, "1.0.3"},
  "poison": {:hex, :poison, "1.5.2"},
  "poolboy": {:hex, :poolboy, "1.5.1"},
  "postgrex": {:hex, :postgrex, "0.10.0"},
  "providers": {:hex, :providers, "1.4.1"},
  "ranch": {:hex, :ranch, "1.2.0"},
  "redix": {:hex, :redix, "0.3.4"},
  "relx": {:hex, :relx, "3.5.0"},
  "ssl_verify_hostname": {:hex, :ssl_verify_hostname, "1.0.5"},
  "sweet_xml": {:hex, :sweet_xml, "0.5.0"},
  "timex": {:hex, :timex, "1.0.0"},
  "tzdata": {:hex, :tzdata, "0.5.6"},
  "uuid": {:hex, :uuid, "1.1.2"}}
```

I ran with verbosity verbose and it just ends with `==> Generating release...` just like for Thisj..

Running a mix compile --force solved the issue for me right now though.
Will merge some code changes to the release branch and see if it works still with --force.

**Comment by bitwalker** [comment]
@ThijsWouters @olivermt I pushed a fix for this to master, I think what was happening is calls to `abort!` when errors occur were shutting the application down before the Logger process could print the errors.

**Comment by ThijsWouters** [comment]
Great work, thanks a lot!
This is the output: `ERROR: "Failed to build release. Please fix any errors and try again."`
It is a little generic, but now it at least indicates that it has failed.
With verbose, it gives enough information to solve the problem.
Closing...
