### ISSUE TITLE
Removing dependency gives error

### ISSUE THREAD

**Issue by ThijsWouters** [bitwalker/exrm#243]
I have removed a dependency from my app. Now `mix release --verbosity=verbose` fails with:

``` elixir
{error,
  {rlx_prv_relup,
    {relup_script_generation_error,
      systools_rc,
      {muldef_module,
        'Elixir.Phoenix.HTML.Safe.Calendar.DateTime'}}}}
```

I remove the dependency both from `applications` and `deps`.

The release works when I remove `rel` and `_build`.

**Comment by ThijsWouters** [comment]
After more testing, I noticed that this does not have anything to do with removing the dependency.

I managed to remove the dependency, while still being able to release.

But I was implementing the `Phoenix.HTML.Safe` protocol before. This is not the case now. I will investigate further.

**Comment by ThijsWouters** [comment]
The library is not removed when I release.

Also I noticed that are multiple versions of other libraries I updated in `rel/<app>/lib`.

Shouldn't these be removed?

**Comment by bitwalker** [comment]
@ThijsWouters `rel/<yourapp/lib` can potentially contain multiple versions of your dependencies if you are doing upgrades. If you aren't doing upgrades, then you can use the `release.clean` task to clean up unnecessary files. However if you are doing upgrades, then those older versions of dependencies are necessary for recreating prior releases. When building the tarball package, only the current version's dependencies are included.

If you are expecting a previous version's dependency which is no longer in the current version to be removed from `rel/<your app>/lib`, that won't happen, because it is kept around in order to permit downgrading to that older version.

Does that answer your question?

**Comment by ThijsWouters** [comment]
Yes, that makes sense.

But then there is still a problem, the library I removed is loaded when I start my application.

**Comment by bitwalker** [comment]
@ThijsWouters Loaded or just in the code path? How are you testing whether or not it's loaded? For instance, if you try to call a function on a module contained in that library, if the module is on the code path, it will be loaded. You'd need to call `:code.all_loaded` and check the first element of each tuple in the result list for that library's name. If it's there, then something has to still be loading it.

**Comment by ThijsWouters** [comment]
When I load my application with `iex -S mix`: 

```elixir
iex(1)> Enum.map(:code.all_loaded, &elem(&1, 0)) |> Enum.map(&to_string/1) |> Enum.filter(&String.starts_with?(&1, "Elixir.Phoenix.HTML.Safe.Calendar"))
[]
```

When I run it with `rel/<app>/bin/<app> console`:

```elixir
Enum.map(:code.all_loaded, &elem(&1, 0)) |> Enum.map(&to_string/1) |> Enum.filter(&String.starts_with?(&1, "Elixir.Phoenix.HTML.Safe.Calendar"))
["Elixir.Phoenix.HTML.Safe.Calendar.DateTime"]
```
But only after I used it once. Otherwise it is empty. I tried using it with `iex`, but then it gives an error.

**Comment by ThijsWouters** [comment]
I've been digging deeper. I noticed that it has to do with consolidation. When I check the consolidated file it shows that the implementation is still there.
While in the `_build` directory, it is gone.

**Comment by bitwalker** [comment]
@ThijsWouters What's the path to the consolidated file you're checking?

**Comment by ThijsWouters** [comment]
In `rel/<app>/lib/consolidated/Elixir.Phoenix.HTML.Safe.beam` the implementation is present.
In `_build/prod/consolidated/Elixir.Phoenix.HTML.Safe.beam` the implementation is not present.
These are built from the same version of my application.

Btw, I am building both with `MIX_ENV=prod`.

**Comment by bitwalker** [comment]
@ThijsWouters `rel/<app>/lib/consolidated` is no longer the correct path for consolidated beams. They are now placed in each application's lib directory, so `rel/<app>/lib/<some_dep>/`. The reason for this is that upgrades/downgrades have to use the correct version of the consolidated beams, and this wasn't possible when they lived in `lib/consolidated`.

**Comment by smdern** [comment]
@bitwalker I've created a repro w/ steps. https://github.com/smdern/exrm_moving_module_repro/tree/master
