### ISSUE TITLE
Silent failure for unreachable_package

### ISSUE THREAD

**Issue by cjimison** [bitwalker/exrm#250]
In the utils.exs ReleaseManager.Utils. relx/5 at the end of the function:

```
case result do
      {:ok, _state} -> :ok
      {:error, _e}  -> {:error, "Failed to build release. Please fix any errors and try again."}
end
```

The issue with this code is if there are any errors you don't get any info about it.  I was just getting the text:
```
"Failed to build release.  Please fix any errors and try again."
```

However there was no error printed to the console.

I modified the code to print out the ```e``` var and got this:
```
Failed to build release. Please fix any errors and try again. {:rlx_prv_release, {:failed_solve, {:unreachable_package, :posion}}}
```
And was able to see that I fat-fingered :poison to :posion.

It would be great if this error message would return something more useful.  My simple fix was to do the following:

```
case result do
      {:ok, _state} -> :ok
      {:error, e}  -> {:error, "Failed to build release. Please fix any errors and try again. #{inspect e}"}
end
```

However it is not very pretty ...

-Chris

**Comment by bitwalker** [comment]
@cjimison Yeah I have an open issue to pretty print relx error messages, but haven't gotten to it yet. You can always get the detailed error message with `mix release --verbosity=verbose`, as well as a bunch of useful context (particularly for me) when reporting issues. However this request is in the pipeline :)

**Comment by cjimison** [comment]
I think the —verbosity is good enough.  Honestly I didn’t know that option was available  :p

-Chris

**Comment by bitwalker** [comment]
@cjimison Yeah right now the only documentation for the mix tasks is using mix itself, so you can pull all the various options for the mix tasks with `mix help release`, `mix help release.clean`, etc. :).

I'll still be addressing the pretty printing of errors, but it's a lower priority since one can still get all the info via the verbosity flag.
