### ISSUE TITLE
Upgrades fail when `{include_erts, false}.`

### ISSUE THREAD

**Issue by cschiewek** [bitwalker/exrm#254]
Initial deploy and start work fine, but when issues `bin/app upgrade "0.0.2"` I get the following error:
```shell
ERROR: release_handler:check_install_release failed: {no_such_file,
                                                      "/home/ubuntu/app/lib/kernel-4.1"}
```

**Comment by bitwalker** [comment]
Are you able to reproduce with [this repo](https://github.com/bitwalker/exrm-test)? You'll have to provide the relx.config file.

A few other quick questions:

- Did the original release have ERTS bundled?
- What is the location of the Erlang lib folder on that machine? Is the path in the error what you'd expect? If so, what is the version of the kernel module in that directory?
- Could you provide the relx.config file you used for the release?

I'll take a look tomorrow as soon as I get a chance.

**Comment by cschiewek** [comment]
I'll attempt to reproduce with that repo in the am. The release never had
erts bundled. I'll check versions as soon as I can.

Thanks!

**Comment by cschiewek** [comment]
I get the exact same error with the exrm-test: 
```
Using /Users/curtis/exrm-test/rel/test/releases/0.0.3/test.sh
Release 0.0.3 not found, attempting to unpack releases/0.0.3/test.tar.gz
Unpacked successfully: "0.0.3"
Generating vm.args/sys.config for upgrade...
sys.config ready!
vm.args ready!
Release 0.0.3 is already unpacked, now installing.
ERROR: release_handler:check_install_release failed: {no_such_file,
                                                      "/Users/curtis/exrm-test/rel/test/lib/kernel-4.1"}
```
when using `{include_erts, false}.` in `relx.config`

The path in the error looks like it's trying to use a file from `rel/test/lib`, not my system erts, which is `/usr/local/Cellar/erlang/18.1/lib/erlang/lib/kernel-4.1`

**Comment by bitwalker** [comment]
@cschiewek I just noticed you are doing an upgrade inside the `rel` folder of your project. This is expected to fail. Erlang's release handler deletes files and/or replaces them as part of it's operation, and it appears that's what is happening here. I still suspect there may be an issue though. Are you able to reproduce if you deploy to `/tmp`? I would try myself, but I'm a bit backlogged unfortunately :(. If I can get to it, I'll give it a shot in the next day or two.

**Comment by cschiewek** [comment]
This was exactly the issue, trying to upgrade inside `rel`.  Sorry!
