### ISSUE TITLE
RC5 doesn't work with :make dependencies

### ISSUE THREAD

**Issue by alco** [bitwalker/exrm#255]
I've been using exrm v0.19.9 so far and it can successfully build a release for my project.

Today I tried upgrading to v1.0.0-rc5, and it broke the release process. I'm getting the following error:

```
Building release with MIX_ENV=prod.
** (FunctionClauseError) no function clause matching in ReleaseManager.Deps.get_applications/1
    lib/exrm/deps.ex:169: ReleaseManager.Deps.get_applications(%Mix.Dep{app: :ranch, deps: [], extra: [], from: "/Users/alco/work/myproject/mix.exs", manager: :make, opts: [hex: :ranch, build: "/Users/alco/work/myproject/_build/prod/lib/ranch", dest: "/Users/alco/work/myproject/deps/ranch", override: true], requirement: "~> 1.0", scm: Hex.SCM, status: {:ok, "1.1.0"}, top_level: true})
    (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
    (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1043: Enum.map/2
    lib/exrm/deps.ex:139: ReleaseManager.Deps.get_included_applications/1
    lib/exrm/deps.ex:128: ReleaseManager.Deps.get_implicit_applications/1
    lib/exrm/deps.ex:13: ReleaseManager.Deps.get_missing_applications/2
    lib/exrm/deps.ex:48: ReleaseManager.Deps.print_missing_applications/1
```

From a quick look at `lib/exrm/deps.ex` I learned that the function in question is expecting either `:mix` or `:rebar` for the `manager` key, but for `ranch` it gets `manager: :make`. Is this value coming from Mix? Should exrm have a catch-all clause there to work with other unexpected build tools?

**Comment by bitwalker** [comment]
@alco I'll get a fix for this out shortly, there should probably just be a catch-all clause, but I'll take a closer look first.

**Comment by bitwalker** [comment]
I have a few other things I want to work on before pushing a new release, but I've pushed a fix to master for now.

**Comment by alco** [comment]
Thanks!
