### ISSUE TITLE
mix release from clean project fails when build_embedded: true

### ISSUE THREAD

**Issue by antipax** [bitwalker/exrm#257]
After checking out a fresh copy of my project and running `mix do deps.get, deps.compile exrm`, running `MIX_ENV=prod mix release` resulted in this error when compilation got to my project:

`** (Mix) Cannot execute task because the project was not yet compiled. When build_embedded is set to true, "MIX_ENV=prod mix compile" must be explicitly executed`

@bitwalker not sure if this should be considered an exrm issue at all, but wanted to mention the behavior here in case it's something that you want to address in some way.

**Comment by bitwalker** [comment]
@antipax This is due to how mix handles tasks which require compilation of the project when `MIX_ENV=prod` and `build_embedded: true`, you must explicitly compile your project first, unfortunately there isn't anything I can do for this one from exrm's side.

**Comment by antipax** [comment]
@bitwalker cool, thanks!

**Comment by nelsonic** [comment]
How are we _meant_ to compile? is it `mix compile` ?

**Comment by bitwalker** [comment]
@nelsonic you should switch to [Distillery](https://github.com/bitwalker/distillery) - it has superceded exrm and is in much better shape. Exrm is deprecated at this point in time. This issue in particular is irrelevant with Distillery, as it ensures compilation is always performed when building the release.

**Comment by nelsonic** [comment]
@bitwalker thanks for reply. have switched. 👍
