### ISSUE TITLE
Since Upgrading, running released app encounters "could not find application file: neotoma.app"

### ISSUE THREAD

**Issue by mpahrens** [bitwalker/exrm#259]
Upon upgrading my mix.exs dependency on exrm and conform from
<code><pre>
{:exrm, git: "https://github.com/bitwalker/exrm.git", tag: "0.18.5"}
</pre><code>
to
<code><pre>
     {:exrm, "~> 1.0.0-rc7", override: true},
     {:conform, "~> 1.0.0-rc7", override: true},
     {:conform_exrm, "~> 0.1"}
</pre></code>

And blowing away my previous *.schema.exs and *.conf and remaking them

Build happens successfully, but now we encounter:
<code><pre>
$ bin/blockytalky console
Using /opt/blockytalky/releases/0.3.2/blockytalky.sh
mkdir: created directory `/opt/blockytalky/running-config'
copying /opt/blockytalky/releases/0.3.2/blockytalky.conf to /opt/blockytalky/running-config/blockytalky.conf ...
using /opt/blockytalky/running-config/blockytalky.conf to populate "/opt/blockytalky/running-config".
Could not start application neotoma: could not find application file: neotoma.app
</pre></code>

Latest version can be found in the develop branch here:
https://github.com/LaboratoryForPlayfulComputation/blockytalky/tree/develop

Maybe I missed instructions along the line, I've been trying to follow along. Any help is appreciated :) thanks!

**Comment by bitwalker** [comment]
@mpahrens This is a bug I introduced, sorry about that. I've pushed a fix and released a new version of conform (1.0.0-rc8). Could you update your conform dep and try again?

**Comment by mpahrens** [comment]
Sure, will do

**Comment by mpahrens** [comment]
So I tried it, and that particular error went away. But now, when I try to run, I am seeing:
<pre><code>
$  bin/blockytalky console
Using /opt/blockytalky/releases/0.3.2/blockytalky.sh
mkdir: created directory `/opt/blockytalky/running-config'
copying /opt/blockytalky/releases/0.3.2/blockytalky.conf to /opt/blockytalky/running-config/blockytalky.conf ...
using /opt/blockytalky/running-config/blockytalky.conf to populate "/opt/blockytalky/running-config".
** (ArgumentError) argument error
    (elixir) lib/code.ex:200: Code.eval_quoted/3
    (conform) lib/conform/schema/mapping.ex:48: Conform.Schema.Mapping.from_quoted/1
    (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
    (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1043: Enum.map/2
    (conform) lib/conform/schema.ex:159: Conform.Schema.from/2
</code></pre>

I will poke at it and see if I messed anything else up.

**Comment by mpahrens** [comment]
also, `mix conform.*` are gone. this is when I try and link conform as a dep from hex. Let me try directly from git.

**Comment by bitwalker** [comment]
I suspect the tasks missing are because a compile was required, but I'm not at my computer at the moment. Regarding the error, could you gist your schema file, or email it?

**Comment by mpahrens** [comment]
sure, my schema file is here:
https://github.com/LaboratoryForPlayfulComputation/blockytalky/blob/develop/blockytalky/config/blockytalky.schema.exs

**Comment by mpahrens** [comment]
Update:
So I wiped my schema and .conf, re compiled all my deps, regenerated a schema and conf, ran
`MIX_ENV=prod mix release --verbosity=verbose` and now I am getting:

https://gist.github.com/mpahrens/c5be965d051eec8c432c

Don't know why. Still working on it

**Comment by mpahrens** [comment]
Just to let you know that I am still trying to fix this. Not sure what is wrong still but trying a few things including:
- upgrading my raspberry pis to erlang 18 since that is what I dev on
- forking conform and trying to debug Conform.Schema.Mapping line 48 to see what Code.eval_quoted is failing on in my schema mappings.

Any advice is appreciated but I'll keep trying. (I am currently not getting any IO.puts or other console logging to work from around line 48 even using Conform.Utils when I run `bin/blockytalky console` and it gives me the same output from above

Just a progress report. If I figure it out I will let you know

**Comment by mpahrens** [comment]
Ok, so for anyone else that hits this issue:
- Cross compiling a phoenix application from `mac os` to `arm with raspbian on raspberry pi`
- including the erts (built on a raspberry pi)

When putting my release on a new pi image (coder flavor of raspbian) that didn't have erlang or elixir on it I got that error above:

<pre><code>
$  bin/blockytalky console
Using /opt/blockytalky/releases/0.3.2/blockytalky.sh
mkdir: created directory `/opt/blockytalky/running-config'
copying /opt/blockytalky/releases/0.3.2/blockytalky.conf to /opt/blockytalky/running-config/blockytalky.conf ...
using /opt/blockytalky/running-config/blockytalky.conf to populate "/opt/blockytalky/running-config".
** (ArgumentError) argument error
    (elixir) lib/code.ex:200: Code.eval_quoted/3
    (conform) lib/conform/schema/mapping.ex:48: Conform.Schema.Mapping.from_quoted/1
    (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
    (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1043: Enum.map/2
    (conform) lib/conform/schema.ex:159: Conform.Schema.from/2
</code></pre>

I built, from source, erlang 18 on a pi. and replaced the erlang 17 (also built on the pi) that I was pointing at in my relx.config

So now the coder raspberry pi has erlang and elixir installed on it AND the bundled erts it is using for the release is erlang 18.1

And the problem went away.

I don't know why. haha. but either putting erlang on the pi itself (which should NOT matter) or upgrading to 18 for the include_erts (which might matter / probably matters), did it. ::shrug::

**Comment by mpahrens** [comment]
Last follow up: I tested each of the cases individually and the fix was specifically updating the erlang I was including_erts with from 17 to 18. I tried it on a pi that had old erlang systemwide and the release with erlang 18 erts included had no problem Code.eval_quoted-ing :)

**Comment by bitwalker** [comment]
Which version of 17? There were some filesystem bugs in early versions of 17.x which were fixed in 17.3 I believe. I wish I had thought to ask that :(

**Comment by mpahrens** [comment]
Not sure off the top of my head, but I think it was earlier than 17.3 judging by the timeline when I made the build originally. No worries :) environment (especially when cross compiling) is aaaaaaalways a pain haha.

**Comment by bitwalker** [comment]
Yeah I wouldn't be suprised if that bit you then, there were tons of issues about it prior to 17.3 (and for awhile after too). It's been long enough since the last one that I've all but forgotten about it, until now that is haha.
