### ISSUE TITLE
Internode Communication with Releases

### ISSUE THREAD

**Issue by midas** [bitwalker/exrm#261]
@bitwalker How you can start a release so that it has a specific name, a la `iex  --name "node@1.2.3.4" -S mix` in development?

As I currently understand, in order to use inter-node communication, each node must be started with a name.

Thanks!

**Comment by chvanikoff** [comment]
@midas [how-to-configure-your-release](https://github.com/bitwalker/exrm/blob/fae3b0f2b426468c860b123037c93c6916a05a73/docs/Release%20Configuration.md#how-to-configure-your-release) is the docs about configuration.
Name arg can be given in `rel/vm.args`, which then will be copied to `rel/APP_NAME/releases/VERSION/vm.args`

**Comment by midas** [comment]
@chvanikoff Thanks!  I read about the release configuration several months ago, but had ignored it when researching this question as I remembered it being all about Conform.  I apologize for wasting your time when the answer was already documented.

Thanks again.
