### ISSUE TITLE
Which version should I use ?

### ISSUE THREAD

**Issue by jhw** [bitwalker/exrm#262]
Hi,

I find everything works fine with branch 0.19.9 but when I try branch master I get a whole load of issues relating to neotoma not being installed

Is this correct ? Am I using the correct version ?

Thx

**Comment by bitwalker** [comment]
@jhw Are you using the latest -rc release from hex, or using master? In either case, could you paste the error output here so I can troubleshoot?

**Comment by jhw** [comment]
Sorry about that. Am away from laptop so will post precise error later but
essentially problem was that 'mix release' complained that erlware commons
required neotoma (sp). Had to manually include neotoma as a dep, then go
through a series of get/compile deps stages. This was on master branch.

**Comment by bitwalker** [comment]
Are you using conform?

**Comment by jhw** [comment]
justin@justin-ThinkPad-X240:~/work/hello_phoenix$ MIX_ENV=prod mix release
==> connection
Compiled lib/connection.ex
Generated connection app
==> erlware_commons (compile)
ERROR: 
===============================================
 You need to install neotoma to compile PEG grammars
 Download the latest tarball release from github
    https://github.com/seancribbs/neotoma
 and install it into your erlang library dir
===============================================

==> hello_phoenix
** (Mix) Could not compile dependency :erlware_commons, "/usr/bin/rebar" command failed. You can recompile this dependency with "mix deps.compile erlware_commons", update it with "mix deps.update erlware_commons" or clean it with "mix deps.clean erlware_commons"
justin@justin-ThinkPad-X240:~/work/hello_phoenix$ 


I can proceed from this point by

- adding neotoma dep
- adding neotoma application
- running various versions of 'mix deps.compile', 'mix compile'

But much more trouble than simply using v0.19.9 (what's the stable version ?)

Not using conform (what is conform ?)

Running Ubuntu 14.04

justin@justin-ThinkPad-X240:~/work/hello_phoenix$ elixir --version
Elixir 1.1.1

**Comment by bitwalker** [comment]
I'm unable to reproduce this with Elixir 1.1.1 and exrm 1.0.0-rc7. Could you blow away `deps`, `_build`, and run `mix deps.clean --unused && mix deps.update exrm && mix deps.update erlware_commons`? It may have been a temporary issue with erlware_commons that is no longer reproducible.

**Comment by mrhooray** [comment]
@bitwalker could you kindly make another rc release to hex.pm which could include #276?
due to limitation of our current internal setup, package from hex.pm is much easier to work with compared to package from git repos

**Comment by arkadiyk** [comment]
I am having the same issue with `1.0.0-rc7`. Works fine with `0.19.9`

When I run `mix deps.get` with `0.19.9` it lists `neotoma` as a dependency. It doesn't for `1.0.0-rc7`.


```
$ mix deps.get
Running dependency resolution
Dependency resolution completed
  bbmustache: 1.0.3
  conform: 0.17.0
  erlware_commons: 0.15.0
  exrm: 0.19.9
  getopt: 0.8.2
  neotoma: 1.7.3
  providers: 1.4.1
  relx: 3.5.0
```

here is output for RC7
```
$ mix deps.get
Running dependency resolution
Dependency resolution completed
  bbmustache: 1.0.3
  erlware_commons: 0.15.0
  exrm: 1.0.0-rc7
  getopt: 0.8.2
  providers: 1.4.1
  relx: 3.5.0
```

The strange thing is, the `RC7` works on my Mac. This problem appears only on my CI machine, and only on one git branch. I could not find any reasons why they behave differently..

**Comment by bitwalker** [comment]
@mrhooray @arkadiyk Just FYI, 1.0.0-rc8 has been released.

**Comment by mrhooray** [comment]
thanks @bitwalker
