### ISSUE TITLE
mix release doesn't compile the project in prod on Elixir 1.2.0-rc.0

### ISSUE THREAD

**Issue by MSch** [bitwalker/exrm#263]
Steps to reproduce: Create a new project with Elixir 1.2.0-rc.0, add the exrm dependency and run `MIX_ENV=prod mix release`.

```
> MIX_ENV=prod mix release
** (Mix) Cannot execute task because the project was not yet compiled. When build_embedded is set to true, "MIX_ENV=prod mix compile" must be explicitly executed
```

Doing `MIX_ENV=prod mix do compile, release` works.

**Comment by dbulic** [comment]
It also doesn't work on 1.1.1

**Comment by asaaki** [comment]
Can confirm:

exrm 0.19.9 and Elixir 1.1.1 -> works
exrm 1.0.0-rc7 and Elixir 1.1.1 -> error as shown above.

On the other hand I have no hard feelings about this if the new behaviour is intentional (more explicit steps for compilation and release building).

**Comment by bitwalker** [comment]
This is due to changes in Mix itself. While the code to implicitly compile the project when running `mix release` was readded in 1.0.0-rc7, the dependencies still have to be compiled in order to run the release task.
