### ISSUE TITLE
release crashes with Ecto 1.1.x

### ISSUE THREAD

**Issue by lau** [bitwalker/exrm#265]
Hi

A Phoenix app works fine with Ecto 1.0.7 and with releases too.

But when upgrading Ecto to 1.1.0 or 1.1.1 it works when running mix phoenix.server, but as a release it crashes:
```
** (UndefinedFunctionError) undefined function: Connection.start_link/2 (module Connection is not available)
    Connection.start_link(Postgrex.Connection,
```
Could this has something to do with exrm?

**Comment by bitwalker** [comment]
If it works outside of a release but not in one, it's almost certainly because an application is missing from `applications` in `mix.exs`. Especially when it's complaining that a module or application is missing. Where is the `Connection` module in this case defined?

**Comment by lau** [comment]
You are right. I had suspected the same thing, but couldn't find out which application it was. But it turned out the answer was right in front of me. `Connection` in this case was not an aliased module as I had assumed. There is actually a hex package called `:connection` which was the offender. So adding `:connection` to the `applications` list solved it :) Thanks for the response.

**Comment by bitwalker** [comment]
No problem! Glad it was an easy fix :). The newest version of exrm should be warning about this, but I scaled back the aggressiveness of it's checking a little bit, so perhaps not. What version of exrm are you using? If you have some time to reproduce it quick with 1.0.0-rc7, I'd be interested to know if you'd get a warning about the missing application.

**Comment by lau** [comment]
Yes, I was using 1.0.0-rc7. I got the same problem with an earlier version, but upgraded to 1.0.0-rc7 to see if that helped. At one point I tried to do a release for the dev environment and got a warning about `phoenix_live_reload`. But not about `connection`.

It would be very helpful if exrm could do a warning about missing applications in the mix.exs list. Or even an error preventing the release. In that case maybe that would have to be overwritten with a command line flag (e.g. --ignore-missing-applications) in order to go through with the release.

**Comment by Alamoz** [comment]
This also happened to me, but only when an app is packaged and deployed as a release; when the app runs on my local development machine it doesn't crash and works properly even if the Connection module is not in the applications list. I've created a pull request to add the Connection module to the applications list when Ecto is used by the app, see #1449.

**Comment by bitwalker** [comment]
@Alamoz That is expected behaviour, as releases run in embedded mode and do not load code dynamically. Outside of a release, the code for that application is loaded on demand. Your PR is exactly the right thing to do :)
