### ISSUE TITLE
release task fails if an Erlang project doesn't specify {registered, []}, in app resource

### ISSUE THREAD

**Issue by zeal301** [bitwalker/exrm#271]
Release task fails with: {missing_param, registered} if the dependency Erlang project doesn't specify 
 `{registered, []},` in the application resource file.

**Comment by bitwalker** [comment]
This needs to be addressed by the project maintainer (or given a reasonable default by relx), as exrm doesn't have the ability to handle this. My recommendation would be to fork the project in question and add this property (and upstream it with a PR!).
