### ISSUE TITLE
Umbrella project fails to build due to dependent project's appup file not existing in main project ebin

### ISSUE THREAD

**Issue by midas** [bitwalker/exrm#275]
I have an umbrella project where the main app is named _backend_. Amongst other projects there is one named _utils_ that is shared with the _backend_ app depending on it as well as others. The _utils_ project was at version 1.0.0 until I had to make my first change to it today. I updated the version of _utils_ to 1.1.0 and also updated the version of _backend_ 1.1.2 -> 1.1.3. 

When I attempt to build, the _utils_ project builds fine and the `util.app` and `util.appup` files are created in the `my_app/apps/util/rel/backend/lib/util-1.1.0/ebin` directory.

However, the main project, _backend_, is failing to build due to the following error:

```
Provider (relup) failed with: {error,
{rlx_prv_relup,
{relup_script_generation_error,
systools_relup,
{file_problem,
{"/home/cjharrelson/sources/my_app/apps/backend/rel/backend/lib/util-1.1.0/ebin/util.appup",
{error,
{open,
"/home/cjharrelson/sources/my_app/apps/backend/rel/backend/lib/util-1.1.0/ebin/util.appup",
enoent}}}}}}}
```

I confirmed that the `/home/cjharrelson/sources/my_app/apps/backend/rel/backend/lib/util-1.1.0/ebin/util.appup` file does not exist.

How do I fix this situation? If this is a bug in _exrm_ is there a work around?

I am currently using version `0.19.9` of _exrm_.

**Comment by midas** [comment]
@bitwalker Any updates on this issue?

**Comment by bitwalker** [comment]
@midas Apologies for the long period of silence, I've been pretty swamped with a big project at work.

This appears to be a bug, because exrm should generate an appup file for a given project's dependencies (if it's able) for use in that release, but it looks like it's not doing that here. I'll see if I can create a sample project to replicate this.

Have you tried with exrm master just to see if it works? or is that upgrade not feasible for you at the moment?

**Comment by midas** [comment]
@bitwalker No problem , I understand work strains.  I have not tried the most recent version of _exrm_ and I cannot remember why I am not using it yet.  I will take a look today.

Is there anything substantially different with the most recent release compared to v0.19.x?

**Comment by martin-langhoff** [comment]
I seem to be affected by a variation on this, on `v1.0.0-rc8`. Umbrella project fails on any build that'd need appups (ie: any build not right after a `release.clean --implode`). This umbrella project is split is a bunch of components, this is one of them. 

The `config.appup` file mentioned below exists in that exact path, but we still get a `no_relup` error:

```
                                         {rlx_prv_relup,
                                            {relup_script_generation_error,
                                             systools_relup,
                                             {no_relup,
                                              "/vagrant/apps/web/rel/web/lib/config-4.0.0-devm1-112-gd2eb5dd/ebin/config.appup",
                                              {application,config,permanent,
                                               "4.0.0-devm1-112-gd2eb5dd",[],
                                               "config",
```

**Comment by midas** [comment]
@bitwalker I can confirm this is an issue for me on the most recent release just as it is for @martin-langhoff.

**Comment by midas** [comment]
@bitwalker I would like to take a stab at fixing this issue, but am far from being able to contribute to exrm.  If you could take some time to familiarize me with the project and the underlying concerns, I would love to be able to contribute to exrm.  Do you have some time coming up that we could get together?

Thanks!

**Comment by johnhamelink** [comment]
If that does happen, I'd love to be able to jump in on that also.

**Comment by martin-langhoff** [comment]
Do you guys have a minimal (or quick compiling ;-) ) project that shows the problem? If so I can rig up a `git bisect` exploration to narrow it down.

**Comment by martin-langhoff** [comment]
My project takes long and is awkward to build/rebuild.

**Comment by midas** [comment]
@martin-langhoff I do not currently, but will work on one.  I will keep you posted.

**Comment by bitwalker** [comment]
@johnhamelink @midas I would like to talk about rewriting the way umbrella projects are handled entirely within exrm. What's the most convenient way to have a discussion about it? Here? Slack maybe?

Basically, releases via exrm are oriented around a single top-level application, but umbrellas are not so much a single top-level application, but a collective of them. In order to support packaging multiple apps in a single release, we have to create a release definition for the umbrella - which is different than how release definitions are done today, and is fundamentally why umbrella releases are done per-app.

The current bugs with releases and umbrellas I believe are due to the changes made to umbrellas in the last six months, but rather than limp along, I've always intended to rebuild that part of exrm.

Ironically I'm using exrm with an umbrella project at work currently, but building independent releases because the components are deployed in their own container images and are geographically separated anyway - so my first chance to really exercise the umbrella code actually doesn't :/.

**Comment by midas** [comment]
@bitwalker @johnhamelink I would prefer a voice or video chat so that we can plow through this in a more efficient manner.  I would suggest either http://uberconference.com or a Google hangout.  I can facilitate either of these if we can decide on a time.

Thoughts on time?

**Comment by johnhamelink** [comment]
@midas @bitwalker I'm happy to use either of those. :smile:

**Comment by martin-langhoff** [comment]
@bitwalker - while you go about these plans, any recommendations for folks hurting today on this bug? I haven't explored but you indicate it's recent, should I roll back to an earlier version? Any known-good version? Currently on `1.0.0-rc8` because we need https://github.com/bitwalker/exrm/issues/269

**Comment by johnhamelink** [comment]
@martin-langhoff You can go into each app and run `mix release` from there to build individual packages - that's what I'm doing for now.

**Comment by midas** [comment]
@martin-langhoff In my use case, one project in the umbrella is a library that 2 other projects depend on.  The failure occurs when I attempt to build the entire umbrella and an appup file is not placed in the projects that depend on the library.   

As a work around, I can implode all of my releases and start fresh when the dependent library is changed and everything works fine.  This kills my ability to hot deploy, but at least I am not stuck.

`mix release.clean --implode`

**Comment by martin-langhoff** [comment]
Ummm, strange. I _am_ running mix release in each of them, and this bug still hits. Perhaps it's because they include/reference a shared `app/common`. :-/

**Comment by midas** [comment]
Maybe we are dealing with 2 separate but similar bugs here?

**Comment by johnhamelink** [comment]
@martin-langhoff yes you have to adjust `mix.exs` to refer to `../../` like so:

```elixir
  def project do
    [app: :api,
     version: "0.3.43",
     build_path: "../../_build",
     config_path: "../../config/config.exs",
     deps_path: "../../deps",
     lockfile: "../../mix.lock",
     elixir: "~> 1.0",
     elixirc_paths: elixirc_paths(Mix.env),
     compilers: [:phoenix, :gettext] ++ Mix.compilers,
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     aliases: aliases,
     deps: deps]
  end
```

**Comment by bitwalker** [comment]
@martin-langhoff I'm doing the same thing you are, but with no isssues. I'm using 1.0.0 though. I have a shared common library, and two Phoenix-based services, one an API, and one a web project.

**Comment by bitwalker** [comment]
@midas @johnhamelink Either of your suggestions for a voice chat option sounds fine, I can find time this afternoon (I'm Central Standard Time) for a bit if that works.

**Comment by johnhamelink** [comment]
@bitwalker sure, name a time and I'll make it work.

**Comment by martin-langhoff** [comment]
Interesting, so I am running a project structured exactly as @bitwalker describes, referencing as @johnhamelink says. I'll update to `1.0.x` when I get a chance and see.

**Comment by midas** [comment]
@bitwalker @johnhamelink 2:00 PM CST?
www.uberconference.com/cjharrelson

**Comment by bitwalker** [comment]
@midas @johnhamelink Sure, I can make that work

**Comment by johnhamelink** [comment]
@midas @bitwalker yep

**Comment by midas** [comment]
@bitwalker @johnhamelink Looking forward to it.  Will see you then.

**Comment by johnhamelink** [comment]
@midas @bitwalker  nice chatting :) Do you know where I can see the video from the beginning?

**Comment by midas** [comment]
@johnhamelink It looks like there is no video recorded, only audio :/

**Comment by martin-langhoff** [comment]
Any summary? Plan of action? :-)

**Comment by midas** [comment]
@bitwalker I can confirm this issue is resolved in 1.x.x.  Not sure if you want to fix it in older release or just suggest an upgrade to all experiencing this issue.  I will let you decide whether to close or not. Thanks!

**Comment by bitwalker** [comment]
I think I'll recommend upgrading, I'm already building releases into Mix, where many things including umbrellas are much better, and there are enough fixes in 1.x that not upgrading is something I would discourage.
