### ISSUE TITLE
Pheonix with Exrm on Vagrant

### ISSUE THREAD

**Issue by abderrahmaneayad** [bitwalker/exrm#277]
I'm trying to get a Phoenix app working in a local Vagrant:

But it does not start with a start command :

``` Shell
rel/phoenix_app/bin/phoenix_app start
Using /var/www/rel/phoenix_app/releases/0.0.1/phoenix_app.sh
```

But somehow it does work with the foreground command :

``` Shell
rel/phoenix_app/bin/phoenix_app foreground
Using /var/www/rel/phoenix_app/releases/0.0.1/phoenix_app.sh
Exec: /var/www/rel/phoenix_app/erts-7.2/bin/erlexec -noshell -noinput +Bd -boot /var/www/rel/phoenix_app/releases/0.0.1/phoenix_app -mode embedded -config /var/www/rel/phoenix_app/running-config/sys.config -boot_var ERTS_LIB_DIR /var/www/rel/phoenix_app/erts-7.2/../lib -env ERL_LIBS /var/www/rel/phoenix_app/lib -pa /var/www/rel/phoenix_app/lib/consolidated/consolidated /var/www/rel/phoenix_app/lib/phoenix_app-0.0.1/consolidated -args_file /var/www/rel/phoenix_app/running-config/vm.args -- foreground
Root: /var/www/rel/phoenix_app
21:39:15.986 [info] Running PhoenixApp.Endpoint with Cowboy using http on port 8888
```

And when I run the remote_console command :

``` Shell
rel/phoenix_app/bin/phoenix_app remote_console
Using /var/www/rel/phoenix_app/releases/0.0.1/phoenix_app.sh
Node is not running!
```

Is it something I'm messing here ? I'v been on this for two days now

**Comment by realistschuckle** [comment]
@abderrahmaneayad Do you have an erl crash file or something in the `rel/phoenix_app/logs` directory that you can share to help diagnose this?

**Comment by OnorioCatenacci** [comment]
@abderrahmaneayad You also want to fill in some of the details about your setup. What's the host OS?  What's the virtual OS (name and version)? etc. etc. etc.  Don't assume that someone can easily reproduce the issue with any version of vagrant from any platform targeting any vm.

**Comment by guiltry** [comment]
+1
Funny thing is, I can only run console and foreground.
I've already set ```server: true```

@realistschuckle my rel/hello_phoenix/log is empty

@OnorioCatenacci 
Host = Darwin 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64
Guest = Linux 3.13.0-55-generic #92-Ubuntu SMP Sun Jun 14 18:32:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by abderrahmaneayad** [comment]
Here is the Vagrantfile : [https://gist.github.com/abderrahmaneayad/ce283efca9f1490f6f02](https://gist.github.com/abderrahmaneayad/ce283efca9f1490f6f02)

@realistschuckle me too, rel/phoenix_app/log is empty.

**Comment by jeromedoyle** [comment]
I have something very similar happening. I generated the release on the `debian/jessie64` vagrant box. I am trying to run the release via systemd on a separate server with the same OS. If I call `ExecStart` with `/home/my_user/apps/my_app/bin/my_app start`, it will work the first time, but will not start again after I call `ExecStop`. If I use `/home/my_user/apps/my_app/bin/my_app foreground`, I can start and stop it properly, but it isn't backgrounded. I'm on 1.0.0-rc7 also.

Distributor ID:	Debian
Description:	Debian GNU/Linux 8.1 (jessie)
Release:	8.1
Codename:	jessie

**Comment by jeromedoyle** [comment]
@abderrahmaneayad have you discovered anything new on this? I am having the exact same issue now. Before, I could run fine using `start` from the terminal, just had couldn't use the same command with systemd. Now, without systemd from the terminal, I get the `Using...` output, but the app isn't running. `rel/app/log` is also empty.

**Comment by abderrahmaneayad** [comment]
@jeromedoyle sadly I didn't find any solution, all I do now is building the release and scp it to the host.

**Comment by jeromedoyle** [comment]
Running the created release with `rel/my_app/bin/my_app start`does nothing, however, if I copy `rel/my_app/releases/0.0.1/my_app.tar.gz` to `/tmp`, untar it, and run it with `./bin/my_app start`, it works correctly. When I run it from `/tmp` I have files in `log/` and `tmp/erl_pipes/my_app`. All directories are owned by the `vagrant` user that I'm running as. Also, the behavior is the same if I run with `sudo`.

**Comment by jeromedoyle** [comment]
@bitwalker should there be any difference between running the app via `rel/my_app/bin/my_app start` vs using the untarred version?

**Comment by jeromedoyle** [comment]
@bitwalker In your talk at ElixirConf 2015 you mention that you don't recommend running a release from the rel directory. Why is this?

**Comment by jeromedoyle** [comment]
So, it appears that building and running the releases works fine, just can't run the release with `rel/my_app/bin/my_app start`

**Comment by martin-langhoff** [comment]
I've hit this, or a form of this. If your release files are on the /vagrant mount (and it's the magic virtualbox mount) Erlang fails to setup the unix pipes. Took me some stracing to figure out.

To test this theory -- copy your release directory to a directory outside of /vagrant, try running it there, if it works...

A practical workaround is to use a bindmount for the rel directory.
