### ISSUE TITLE
Current path inside release?

### ISSUE THREAD

**Issue by iwarshak** [bitwalker/exrm#280]
More of a question, but I have a node script that gets called from porcelain:

```Porcelain.shell("node ./priv/foo.js")```

This works fine in dev, but when I deploy with exrm, `.` seems to be at the top level deploy directory, and not within the release folder itself. (I have followed the docs setting up a release folder structure).

Error: ```Error: Cannot find module '/home/ubuntu/rel/myapp/priv/foo.js'```

Content of `/home/ubuntu/rel/myapp`:

```bin  erl_crash.dump  erts-7.1  lib  log  releases  running-config  tmp```

Using exrm 0.19.9

Is there a solution to be able to call a script like this in a way that works locally & with exrm?

**Comment by bitwalker** [comment]
Yep :), just use `:code.priv_dir(:your_app_name)`. This will return a path to the priv directory for your application as a charlist (so make sure you convert it to a binary before passing it to Porcelain).
