### ISSUE TITLE
Module is not available

### ISSUE THREAD

**Issue by djthread** [bitwalker/exrm#284]
My phoenix app works great in dev mode, prod mode, and even with exrm before I just added the [Timex](https://github.com/bitwalker/timex) module. But since I included this module, when I build my app for prod and execute it, sending a line of chat causes my module call to fail:

    ** (UndefinedFunctionError) undefined function Timex.Date.now/1 (module Timex.Date is not available)

I have `use Timex` and otherwise have followed the Timex instructions. I'm left wondering if there is an exrm quirk here? What am I missing?

... somehow, the runtime seems to know that when I said Date.now, it knew I wanted Timex.Date.now... so the `use Timex` helped that far, at least?

My repo: https://github.com/djthread/tuesday

Thanks in advance for any thoughts.

	Exec: /app/tuesday/erts-7.2.1/bin/erlexec -noshell -noinput +Bd -boot /app/tuesday/releases/0.0.1/tuesday -mode embedded -config /app/tuesday/running-config/sys.config -boot_var ERTS_LIB_DIR /app/tuesday/erts-7.2.1/../lib -pa /app/tuesday/lib/consolidated -env ERL_LIBS /app/tuesday/lib -args_file /app/tuesday/running-config/vm.args -- foreground
	Root: /app/tuesday
	21:36:01.999 [info] Running Tuesday.Endpoint with Cowboy using http on port 4090
	21:36:09.080 request_id=1pf4icpjg29ndvvkas474lji7unsddan [info] GET /info.json
	21:36:09.086 request_id=1pf4icpjg29ndvvkas474lji7unsddan [info] Sent 200 in 6ms
	21:36:12.352 [info] JOIN rooms:lobby to Tuesday.RoomChannel
	  Transport:  Phoenix.Transports.WebSocket
	  Parameters: %{}
	21:36:12.353 [info] Replied rooms:lobby :ok
	21:36:12.374 [error] GenServer #PID<0.1254.0> terminating
	** (UndefinedFunctionError) undefined function Timex.Date.now/1 (module Timex.Date is not available)
		Timex.Date.now("America/Detroit")
		(tuesday) web/channels/room_channel.ex:40: Tuesday.RoomChannel.handle_in/3
		(phoenix) lib/phoenix/channel/server.ex:229: Phoenix.Channel.Server.handle_info/2
		(stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
		(stdlib) gen_server.erl:681: :gen_server.handle_msg/5
		(stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

	=CRASH REPORT==== 25-Jan-2016::21:36:12 ===
	  crasher:
		initial call: Elixir.Phoenix.Channel.Server:init/1
		pid: <0.1254.0>
		registered_name: []
		exception exit: {undef,
							[{'Elixir.Timex.Date',now,[<<"America/Detroit">>],[]},
							 {'Elixir.Tuesday.RoomChannel',handle_in,3,
								 [{file,"web/channels/room_channel.ex"},
								  {line,40}]},
							 {'Elixir.Phoenix.Channel.Server',handle_info,2,
								 [{file,"lib/phoenix/channel/server.ex"},
								  {line,229}]},
							 {gen_server,try_dispatch,4,
								 [{file,"gen_server.erl"},{line,615}]},
							 {gen_server,handle_msg,5,
								 [{file,"gen_server.erl"},{line,681}]},
							 {proc_lib,init_p_do_apply,3,
								 [{file,"proc_lib.erl"},{line,240}]}]}
		  in function  gen_server:terminate/7 (gen_server.erl, line 826)
		ancestors: [<0.1248.0>]
		messages: []
		links: [<0.1248.0>,<0.1101.0>]
		dictionary: []
		trap_exit: true
		status: running
		heap_size: 1598
		stack_size: 27
		reductions: 2625
	  neighbours:
	21:36:13.385 [info] JOIN rooms:lobby to Tuesday.RoomChannel
	  Transport:  Phoenix.Transports.WebSocket
	  Parameters: %{}
	21:36:13.386 [info] Replied rooms:lobby :ok
	21:36:19.080 request_id=037ggh0j067v2btu2dp9al1gq6ripl9f [info] GET /info.json
	21:36:19.081 request_id=037ggh0j067v2btu2dp9al1gq6ripl9f [info] Sent 200 in 1ms
	21:36:29.080 request_id=ncpoqlcalokh54eujmgfv2rt5urmjp17 [info] GET /info.json

**Comment by olivermt** [comment]
`:timex ` is missing from your application list in mix.exs, as it says in the docs you need to have it in there for exrm to be able to pull in the deps.

**Comment by djthread** [comment]
Thank you very much for the reply, olivermt. The [readme](https://github.com/bitwalker/timex) says I need to include :tzinfo in my application list, which I have done. I notice now that if I *also* add :timex to my application list, things seem to work more smoothly as you suggest.

I would really love to know how I was supposed to know to do that. You'll notice Timex's readme says nothing about adding :timex to the application list... Is this some sort of rule that comes into play when building with exrm?

I see some discussion about it in the exrm docs, but I'm still left wondering exactly what I'm missing. Why does exrm need :timex when my app, running under mix phoenix.server, doesn't?

What's the rule that should have let to me adding :timex to the application list without asking? :)

Thank you thank you!

**Comment by olivermt** [comment]
I meant exrm docs, not timex docs :)

Basically if you get a message something is missing, its 99% of the time because its not added to the application list.

Exrm pulls in the deps through that list when it builds the application structure.

**Comment by djthread** [comment]
Interesting. I had assumed that the only reason to put applications in this list is to have their start function invoked on the greater application's startup. I guess exrm is particular about using this to understand what needs building whereas when normally

It looks like timex has :tzinfo in its applications list, so all I need to include is :timex . . . so I do wonder why the timex docs don't just ask me to include :timex rather than :tzinfo.

Anyway, thank you very much for setting me down the right path. I'm still not certain of the subtleties here, but at least I'll have an idea what to try next time I encounter something like this.

**Comment by bitwalker** [comment]
@djthread Yes the reason it's not in the timex docs is because this is a release-specific requirement. The requirement to add `:tzdata` to applications is necessary for normal operation regardless of the use of releases. Sorry for the confusion!

As you pointed out, because Timex has `:tzdata` in it's application's list, the docs can probably just recommend adding `:timex` instead. I'll make that change when I push an update next.

**Comment by djthread** [comment]
ty, bitwalker!
