### ISSUE TITLE
Error in escript when trying to hot upgrade on 0.19.9

### ISSUE THREAD

**Issue by maxim** [bitwalker/exrm#288]
I'm on exrm 0.19.9. I setup a new server and started getting this error when trying to hot-upgrade:

https://gist.github.com/maxim/52f7f822f8c880dc916c

The only difference between this and other servers is that here I run the app with `RELEASE_CONFIG_DIR` altered to another path.

I tracked down the error to this case statement. It does return error, but not the one that's matching:
https://github.com/bitwalker/exrm/blob/ba7596cdc9f303708d7279b223408c19219c2ca3/priv/rel/files/install_upgrade.escript#L84-L96

Any advice? Should I switch to rc version?

**Comment by maxim** [comment]
Just found more info, the app was outputting this: error during a which_children call to Ecto.Adapters.MySQL

**Comment by bitwalker** [comment]
@maxim Looks like this is due to an issue in Ecto, as discovered in #297. It's been fixed in Ecto master, and is present in the v1.1 branch (so I'd expect it on hex.pm in either another 1.1.x release, or in 2.x).
