### ISSUE TITLE
foreground command crashing

### ISSUE THREAD

**Issue by houli** [bitwalker/exrm#291]
Hi I'm using exrm on an elixir project to generate releases. I'm having no problems running commands like `console` `start` `remote_console` etc. but I am getting a crash trying to start the `foreground` command. This is the output of `rel/proxy/bin/proxy foreground`
```
Using /Users/eoinhoulihan/projects/elixir/proxy/rel/proxy/releases/0.0.1/proxy.sh
Exec: /Users/eoinhoulihan/projects/elixir/proxy/rel/proxy/erts-7.2.1/bin/erlexec -noshell -noinput +Bd -boot /Users/eoinhoulihan/projects/elixir/proxy/rel/proxy/releases/0.0.1/proxy -mode embedded -config /Users/eoinhoulihan/projects/elixir/proxy/rel/proxy/running-config/sys.config -boot_var ERTS_LIB_DIR /Users/eoinhoulihan/projects/elixir/proxy/rel/proxy/erts-7.2.1/../lib -pa /Users/eoinhoulihan/projects/elixir/proxy/rel/proxy/lib/consolidated -env ERL_LIBS /Users/eoinhoulihan/projects/elixir/proxy/rel/proxy/lib -args_file /Users/eoinhoulihan/projects/elixir/proxy/rel/proxy/running-config/vm.args -- foreground
Root: /Users/eoinhoulihan/projects/elixir/proxy/rel/proxy
{error_logger,{{2016,2,10},{13,7,51}},crash_report,[[{initial_call,{supervisor,kernel,['Argument__1']}},{pid,<0.981.0>},{registered_name,[]},{error_info,{exit,{on_load_function_failed,'Elixir.Socket'},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,352}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}},{ancestors,[kernel_sup,<0.959.0>]},{messages,[]},{links,[<0.960.0>]},{dictionary,[]},{trap_exit,true},{status,running},{heap_size,376},{stack_size,27},{reductions,117}],[]]}
{error_logger,{{2016,2,10},{13,7,51}},supervisor_report,[{supervisor,{local,kernel_sup}},{errorContext,start_error},{reason,{on_load_function_failed,'Elixir.Socket'}},{offender,[{pid,undefined},{id,kernel_safe_sup},{mfargs,{supervisor,start_link,[{local,kernel_safe_sup},kernel,safe]}},{restart_type,permanent},{shutdown,infinity},{child_type,supervisor}]}]}
{error_logger,{{2016,2,10},{13,7,52}},crash_report,[[{initial_call,{application_master,init,['Argument__1','Argument__2','Argument__3','Argument__4']}},{pid,<0.958.0>},{registered_name,[]},{error_info,{exit,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,'Elixir.Socket'}}},{kernel,start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,134}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}},{ancestors,[<0.957.0>]},{messages,[{'EXIT',<0.959.0>,normal}]},{links,[<0.957.0>,<0.956.0>]},{dictionary,[]},{trap_exit,true},{status,running},{heap_size,376},{stack_size,27},{reductions,117}],[]]}
{error_logger,{{2016,2,10},{13,7,52}},std_info,[{application,kernel},{exited,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,'Elixir.Socket'}}},{kernel,start,[normal,[]]}}},{type,permanent}]}
{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,kernel_safe_sup,{on_load_function_failed,'Elixir.Socket'}}},{kernel,start,[normal,[]]}}}"}
[1]    12874 user-defined signal 2  rel/proxy/bin/proxy foreground
```
The code for reference is at https://github.com/houli/http-proxy

**Comment by houli** [comment]
So checking out the code in https://github.com/bitwalker/exrm-test the foreground command works perfectly until I add https://github.com/meh/elixir-socket as a dependency and add it to the applications list. Not sure if this is an issue with exrm or with the socket library,

**Comment by bitwalker** [comment]
Looks to me like the issue is the use of @on_load in `lib/socket.ex`, if the on_load function itself depends on a module being available from an application which also has an on_load function, that module will be unavailable in a release because of how code is loaded.

**Comment by houli** [comment]
The release seems to work fine for commands like `start` `console` however. I'm not sure about the implications but the on_load code for the socket library only appears to be calling standard library functions and returning `:ok`.

**Comment by bitwalker** [comment]
@houli I found the problem, and opened a PR with the elixir-socket repo, if you want, use my fork for now until meh can merge the change.

**Comment by aramisbear** [comment]
This could just be newness to Elixir @bitwalker but whenever I tried to use your fork I'm still getting the error. I'm assuming I'm doing something wrong in terms of trying to force it to use your fork? I'm also using the email_checker library which includes `{:socket, "~> 0.3.1"}` as a dependency. Is there a simple way of forcing yours for all dependencies or is this a situation where I'm going to have to fork everything that depends on it until @meh merges the pull request?

**Comment by bitwalker** [comment]
@aramisbear Did you run `mix deps.unlock socket && mix deps.update socket` after changing the entry in `mix.exs`? I'm guessing it's still using the original dep. You can always check by looking in `mix.lock` to see precisely which version of a package is being fetched.

**Comment by bitwalker** [comment]
As for using my fork for other dependencies, all you have to do is just `{:socket, github: "bitwalker/elixir-socket", override: true}`. `override: true` will override the dependency globally in your application to use the one specified.

**Comment by aramisbear** [comment]
Thanks @bitwalker. Huge help.
