### ISSUE TITLE
Releases built with 1.0.0-rc8 are starting applications in the wrong order

### ISSUE THREAD

**Issue by obmarg** [bitwalker/exrm#296]
I've just upgraded an application to using 1.0.0-rc8 (from rc7). Releases built with rc8 are producing a completely different application startup order from rc7, that's causing my start up to fail.  I'm not entirely sure if this is a bug in exrm or elsewhere, but definitely seems to be linked to rc8.

The application in question is closed source, but I've put together an example of the issue here: https://github.com/obmarg/exrm_test - the first commit uses rc7, and the second uses rc8.  They both generate fairly different app startup orders.   Here's a diff of the end of the `exrm_test.script` files in the 2 releases (which I assume is what decides the order of things, correct me if I'm wrong):

```diff
@@ -1320,35 +1320,35 @@
      {apply,{application,start_boot,[setup,permanent]}},
      {apply,{application,start_boot,[syntax_tools,permanent]}},
      {apply,{application,start_boot,[compiler,permanent]}},
-     {apply,{application,start_boot,[asn1,permanent]}},
-     {apply,{application,start_boot,[idna,permanent]}},
-     {apply,{application,start_boot,[mimerl,permanent]}},
-     {apply,{application,start_boot,[certifi,permanent]}},
-     {apply,{application,start_boot,[ranch,permanent]}},
-     {apply,{application,start_boot,[crypto,permanent]}},
-     {apply,{application,start_boot,[esqlite,permanent]}},
-     {apply,{application,start_boot,[xmerl,permanent]}},
-     {apply,{application,start_boot,[poolboy,permanent]}},
      {apply,{application,start_boot,[goldrush,permanent]}},
-     {apply,{application,start_boot,[public_key,permanent]}},
-     {apply,{application,start_boot,[cowlib,permanent]}},
-     {apply,{application,start_boot,[elixir,permanent]}},
      {apply,{application,start_boot,[lager,permanent]}},
-     {apply,{application,start_boot,[ssl,permanent]}},
+     {apply,{application,start_boot,[exometer_core,permanent]}},
+     {apply,{application,start_boot,[elixir,permanent]}},
      {apply,{application,start_boot,[logger,permanent]}},
-     {apply,{application,start_boot,[cowboy,permanent]}},
-     {apply,{application,start_boot,[poison,permanent]}},
-     {apply,{application,start_boot,[ssh,permanent]}},
+     {apply,{application,start_boot,[exometer_datadog,permanent]}},
+     {apply,{application,start_boot,[elixometer,permanent]}},
      {apply,{application,start_boot,[cryptex,permanent]}},
-     {apply,{application,start_boot,[exometer_core,permanent]}},
-     {apply,{application,start_boot,[plug,permanent]}},
+     {apply,{application,start_boot,[poolboy,permanent]}},
+     {apply,{application,start_boot,[crypto,permanent]}},
+     {apply,{application,start_boot,[asn1,permanent]}},
+     {apply,{application,start_boot,[public_key,permanent]}},
+     {apply,{application,start_boot,[ssh,permanent]}},
+     {apply,{application,start_boot,[xmerl,permanent]}},
      {apply,{application,start_boot,[porcelain,permanent]}},
+     {apply,{application,start_boot,[exgpg,permanent]}},
+     {apply,{application,start_boot,[poison,permanent]}},
+     {apply,{application,start_boot,[esqlite,permanent]}},
      {apply,{application,start_boot,[sqlitex,permanent]}},
+     {apply,{application,start_boot,[ssl,permanent]}},
+     {apply,{application,start_boot,[certifi,permanent]}},
+     {apply,{application,start_boot,[mimerl,permanent]}},
+     {apply,{application,start_boot,[idna,permanent]}},
      {apply,{application,start_boot,[hackney,permanent]}},
-     {apply,{application,start_boot,[exgpg,permanent]}},
-     {apply,{application,start_boot,[elixometer,permanent]}},
-     {apply,{application,start_boot,[exometer_datadog,permanent]}},
      {apply,{application,start_boot,[httpoison,permanent]}},
+     {apply,{application,start_boot,[plug,permanent]}},
+     {apply,{application,start_boot,[cowlib,permanent]}},
+     {apply,{application,start_boot,[ranch,permanent]}},
+     {apply,{application,start_boot,[cowboy,permanent]}},
      {apply,{application,start_boot,[exrm_test,permanent]}},
      {apply,{application,start_boot,[iex,permanent]}},
      {apply,{application,start_boot,[sasl,permanent]}},
```

`exometer_datadog` lists `httpoison` in it's applications, and `httpoison` lists `hackney`, so I assume `hackney` should always be started before `exometer_datadog`, but it appears this is not the case with rc8, which is causing the failures I am seeing.

**Comment by obmarg** [comment]
From running a `git bisect` this change seems to have been brought in by [this commit that updated relx](https://github.com/bitwalker/exrm/commit/f3da2750d4c5acc20136fa363b005c6e2c7f70df)

**Comment by tsloughter** [comment]
Odd. That commit is before we ditched the custom sorting and rely now on systools sorting that was fixed, so I don't see how the sorting would have changed.

But either way, may want to update relx and see if it still is a problem.

**Comment by obmarg** [comment]
@tsloughter I'm seeing this issue with relx 3.16.0, think that's the latest version?

**Comment by bitwalker** [comment]
@tsloughter Is this dependent on a fix in Erlang's stdlib? Is there a particular version cut-off for that fix if so?

**Comment by tsloughter** [comment]
No, it has been fixed in OTP since like R12. relx still had its own because when it was `sinan` it was before this fix was in otp and so we just kept it. But I have since removed it.

**Comment by tsloughter** [comment]
Can you gist the .app files that exist after building so we can verify applications is correct.

**Comment by bitwalker** [comment]
@tsloughter I'll clone that test repo and gist up the .app files for you, should just be a few minutes

**Comment by bitwalker** [comment]
@tsloughter Looks like they are basically identical .app's (other than version)

.app for v1 with exrm rc7
```erlang
{application,exrm_test,
             [{registered,[]},
              {description,"exrm_test"},
              {vsn,"0.0.1"},
              {modules,['Elixir.ExrmTest']},
              {applications,[kernel,stdlib,elixir,logger,cowboy,plug,
                             porcelain,httpoison,sqlitex,esqlite,poison,exgpg,
                             xmerl,ssh,poolboy,cryptex,elixometer,
                             exometer_datadog]},
              {mod,{'Elixir.ExrmTest',[]}}]}.
```

exrm_test v2 with exrm rc8

```erlang
{application,exrm_test,
             [{registered,[]},
              {description,"exrm_test"},
              {vsn,"0.0.2"},
              {modules,['Elixir.ExrmTest']},
              {applications,[kernel,stdlib,elixir,logger,cowboy,plug,
                             porcelain,httpoison,sqlitex,esqlite,poison,exgpg,
                             xmerl,ssh,poolboy,cryptex,elixometer,
                             exometer_datadog]},
              {mod,{'Elixir.ExrmTest',[]}}]}.
```

**Comment by tsloughter** [comment]
What is in the exometer_datadog's .app?

**Comment by bitwalker** [comment]
@tsloughter I'm generating them again, want any other apps?

**Comment by bitwalker** [comment]
@tsloughter Here's exometer_datadog's .app

```erlang
{application,exometer_datadog,
             [{registered,[]},
              {description,"exometer_datadog"},
              {vsn,"0.3.0"},
              {modules,['Elixir.ExometerDatadog',
                        'Elixir.ExometerDatadog.Reporter',
                        'Elixir.ExometerDatadog.Reporter.Metric',
                        'Elixir.ExometerDatadog.Reporter.Options',
                        'Elixir.ExometerDatadog.Reporter.Point',
                        'Elixir.ExometerDatadog.SystemMetrics',
                        'Elixir.Poison.Encoder.ExometerDatadog.Reporter.Metric']},
              {applications,[kernel,stdlib,elixir,logger,exometer_core]},
              {mod,{'Elixir.ExometerDatadog',[]}},
              {env,[{add_reporter,true},
                    {reporter_config,[]},
                    {update_frequency,1000},
                    {metric_prefix,nil},
                    {report_system_metrics,false},
                    {report_vm_metrics,false},
                    {host_fn,{inet,gethostname}}]}]}.
```

**Comment by tsloughter** [comment]
There you go, it doesn't have httpoison in applications.

**Comment by bitwalker** [comment]
@obmarg You mentioned that exometer_datadog has httpoison in it's applications, but looking a the mix.exs of the version specified in your deps, it actually does not (and this is reflected in the built .app files). Looks like you just need to make sure you are using a version where httpoison is in applications, or add it to your own applications list.

**Comment by bitwalker** [comment]
@tsloughter Thanks for helping out, should've double checked that myself :/

**Comment by obmarg** [comment]
You know this was the first thing I checked.  Unfortunately I didn't verify the commit in my `mix.lock` file was correct - just checked the tag in there and my `mix.exs`.  The tag was pointing at a version with httpoison but the commit was not, and it seems that silently takes precedence.

Thanks for the help - really appreciate it, sorry for wasting both your time.

**Comment by bitwalker** [comment]
@obmarg No worries! It's still useful to have things like this in the issue tracker for other people to reference when they experience issues like this.

As for the tag/commit issue, a git tag is just a reference to a specific commit, so the tag is resolved to the commit when deps are fetched/locked. If the tag was deleted and recreated to reference a different commit after you locked your deps, you'd have to explicitly force that dep to be refetched (using mix.deps unlock <dep> and mix deps.update <dep>).

**Comment by obmarg** [comment]
@bitwalker I actually think this might be a bug (or at least an unfriendly bit of behaviour) in mix.  I'd changed the tag I was requesting in my `mix.exs` to v0.4.0 then ran `mix deps.get`.  That's usually how I deal with upgrading hex.pm packages.  But unlike when I do it for hex.pm packages, this didn't cause a new commit to be pulled in, it just wrote out the tag I was requesting to `mix.lock` (even though it didn't match the commit tag at all).

I've actually been tripped up by this twice today, but it didn't occur to me that it could be happening here as well.

**Comment by bitwalker** [comment]
Yeah that doesn't sound right, definitely worth reporting!
