### ISSUE TITLE
RFC - Keep a changelog so people can tell what's different

### ISSUE THREAD

**Issue by ericlathrop** [bitwalker/exrm#298]
Thanks for working on this project, it's really useful!

I'd like to know what's different between versions, so it would be helpful if the project kept a changelog. A good format I've seen is documented at http://keepachangelog.com/

**Comment by edevil** [comment]
+1

**Comment by mingchuno** [comment]
+1

**Comment by bitwalker** [comment]
I can certainly do this moving forward. For past changes, you can look through the commit log - every release is tagged in git, so doing something like `git log 1.0.0-rc7..1.0.0-rc8` will show you the commits included in 1.0.0-rc8. I know that's not necessarily as useful as a high-level overview, but it's better than nothing!
