### ISSUE TITLE
Nested release tarball

### ISSUE THREAD

**Issue by martin-langhoff** [bitwalker/exrm#302]
I seem to be having a variation on #165  on `1.0.0-rc8`. On a fresh checkout (or after `mix release.clean --implode`) my release tarballs contain a nested copy of themselves. The "outer" tarball is exactly 2x the expected size, the "inner" one is about right.

If I extract the inner tarball and then expand both, the only difference between them is the inner tarball, tested with `diff -uN --recursive`. 

A trivial workaround is to extract the inner tarball, but overall this seems rather odd.

**Comment by mingchuno** [comment]
correct me if I am wrong as I am new to Elixir. 
checkout the doc on upgrade and downgrade
https://hexdocs.pm/exrm/extra-upgrades-and-downgrades.html

It seems to be correct for a OTP release. When you try to upgrade to a new version, you need to put the jar of your new release into the release dir from the outer tarball in the old release.

**Comment by martin-langhoff** [comment]
So this is expected. I apologize and proceed to crawl back under my rock. 

Mixed feelings about it, but I'll chew through the implications. (I understand wanting to have the untampered tarball at hand, but then you only need the inner tarball and unpack utilities/scripts outside, etc. Nervermind my mumbling :-) )

**Comment by bitwalker** [comment]
The tarball is necessary for the release handler, it allows it to perform upgrades/downgrades once the release is installed.
