### ISSUE TITLE
Function being called from wrong namespace

### ISSUE THREAD

**Issue by faizaanshamsi** [bitwalker/exrm#303]
I have a phoenix application that includes https://github.com/vikram7/sec_latest_filings_rss_feed_parser in the `deps` with `app: false`. Everything works fine when I compile and run the server, but when I build a release I get: 

```
=SUPERVISOR REPORT==== 23-Feb-2016::21:03:04 ===
     Supervisor: {local,'Elixir.Quantum.Supervisor'}
     Context:    child_terminated
     Reason:     {undef,
                     [{'Elixir.SecLatestFilingsRssFeedParser','parse!',
                          [<<"<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>\n<feed xmlns=\"http://www.w3.org/2005/Atom\">\n...
```

I suspect the issue is that `Elixir.SecLaterFilingsRssFeedParser.parse!/0` is being called instead of `SecLaterFilingsRssFeedParser.parse!/0` but I'm not sure of what I'd need to configure to get it to work correctly. Any help would be appreciated.

**Comment by bitwalker** [comment]
@faizaanshamsi Did you add `:sec_recent_filings_rss_feed_parser` to your applications list?

**Comment by bitwalker** [comment]
@faizaanshamsi Also, `SecLaterFilingsRssFeedParser` is the exact same thing as `Elixir. SecLaterFilingsRssFeedParser`. When Elixir code is compiled, all Elixir source modules have `Elixir.` prepended to them.

**Comment by faizaanshamsi** [comment]
D'oh. That did it, thanks!
