### ISSUE TITLE
readlink doesn't have a -f option on OSX

### ISSUE THREAD

**Issue by chrismcg** [bitwalker/exrm#306]
Just trying exrm for the first time with 1.0.0 and getting an error when I try to run the console on OSX 10.9.5.

```
chris@gairmi % ./rel/ostali/bin/ostali console
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
cat: //releases/start_erl.data: No such file or directory
cat: //releases/start_erl.data: No such file or directory
Using //releases//ostali.sh
./rel/ostali/bin/ostali: line 11: //releases//ostali.sh: No such file or directory
./rel/ostali/bin/ostali: line 11: exec: //releases//ostali.sh: cannot execute: No such file or directory
```

https://github.com/bitwalker/exrm/pull/304 looks like the commit that introduced `readlink -f`

**Comment by bitwalker** [comment]
Pushed a new bugfix release, 1.0.1 with this fix. Thanks for reporting!

**Comment by bitwalker** [comment]
Ok looks like it broke in CI, I'll be pushing another fix soon.

**Comment by chrismcg** [comment]
Unfortunately this isn't going to work :( From the readlink manpage on OSX

> When invoked as readlink, only the target of the symbolic link is printed.  If the given argument is not a symbolic link, readlink will print nothing and exit with an error.

I tried the edit in the commit and I get an error from dirname now

**Comment by bitwalker** [comment]
@chrismcg Ok, I implemented an alternative solution which uses only POSIX commands, seems to work for me. I updated the 1.0.1 release, but the commit with the fix is 79a6819

**Comment by bitwalker** [comment]
Just passed in CI as well

**Comment by chrismcg** [comment]
Can confirm it works locally too, thanks for the super fast fix! (and all your other work on exrm).

**Comment by bitwalker** [comment]
Awesome! You're very welcome!
