### ISSUE TITLE
Is the Phoenix Guide for exrm releases deprecated or are my releases being generated incorrectly?

### ISSUE THREAD

**Issue by sashaafm** [bitwalker/exrm#307]
The Phoenix Guides seem to reference an old version (0.19.0) and some stuff happens differently from my experiments:

The guides says that an `app-0.0.1.tar.gz` tarball will be in `rel/app`, but these don't appear in my releases (I'm using `MIX_ENV=prod`). The only tarball I have is in `rel/app/releases/0.0.1/app.tar.gz`. 

Is this the correct tarball to use now? Or should that 0.0.1 tarball appear?

**Comment by midas** [comment]
@sashaafm The `rel/app/releases/0.0.1/app.tar.gz` is the correct tarball.  The Phoenix guide must be incorrect.

**Comment by bitwalker** [comment]
@sashaafm The Phoenix guide is slightly out of date, it looks to me like that's the only thing that is outdated though.

/cc @chrismccord

**Comment by sashaafm** [comment]
I had actually sent a pull request earlier to correct some of the outdated
stuff there and then noticed the other stuff like the different tarball
directory. I can further update the guide after dinner if you don't mind.

A seg, 29/02/2016, 20:55, Paul Schoenfelder <notifications@github.com>
escreveu:

**Comment by bitwalker** [comment]
@sashaafm That would be very helpful! Thanks!
