### ISSUE TITLE
Not enough information on errors

### ISSUE THREAD

**Issue by edevil** [bitwalker/exrm#308]
Today I again tried exrm 1.0.1 and got this error:
```
# mix release
Building release with MIX_ENV=prod.
This is an upgrade, verifying appups exist for updated dependencies..
==> All dependencies have appups ready for release!
==> Generated .appup for bullhorn 0.0.21 -> 0.0.22
==> ERROR: "Failed to build release. Please fix any errors and try again."
```

It's probably something that is corrupted in my releases, since I've been going back and forth between rc, 0.19 and 1.0 versions, but more info would help.

**Comment by sashaafm** [comment]
Hello @edevil what SO are you running? I've run into a similar problem yesterday on my Kubuntu VM that doesn't happen on my LXLE VM. I'm not sure what was causing it, but maybe because my Kubuntu VM has Elixir 1.1.1.

**Comment by jeromedoyle** [comment]
Try running `MIX_ENV=prod mix release --verbosity=verbose` and see if that tells you more.

**Comment by edevil** [comment]
@sashaafm I'm running on a ubuntu Docker image using Elixir 1.2.

@jeromedoyle Sorry, meanwhile I've already imploded the releases and as I suspected it's working now:

```
# mix release.clean --implode

THIS WILL REMOVE ALL RELEASES AND RELATED CONFIGURATION FOR BULLHORN!
Are you absolutely sure you want to proceed?
 [Yn]:

==> All release files for bullhorn-0.0.22 were removed successfully!
# mix release
Building release with MIX_ENV=prod.
==> The release for bullhorn-0.0.22 is ready!
==> You can boot a console running your release with `$ rel/bullhorn/bin/bullhorn console`

....

# mix release
Building release with MIX_ENV=prod.
This is an upgrade, verifying appups exist for updated dependencies..
==> All dependencies have appups ready for release!
==> Generated .appup for bullhorn 0.0.22 -> 0.0.23
==> The release for bullhorn-0.0.23 is ready!
==> You can boot a console running your release with `$ rel/bullhorn/bin/bullhorn console`
```

**Comment by bitwalker** [comment]
@edevil If you run into issues again, try running with `--verbosity=verbose`. I've also fixed an issue with the logger just now which sometimes would fail to write errors to the console prior to the application exiting.
