### ISSUE TITLE
Memory usage difference between build environments

### ISSUE THREAD

**Issue by tmjoen** [bitwalker/exrm#314]
First of all I want to say thanks for an awesome piece of software, I really love it!

I built a release on my dev machine running OSX. When I test this release the memory usage is as expected (matching up to just running plain `MIX_ENV=prod mix phoenix.server`.

            total..: 36.2 MiB
            atom...: 371.5 KiB
            process: 6.8 MiB
            binary.: 8.3 MiB
            code...: 11.4 MiB
            ets....: 1.3 MiB

Now, I needed a way to build this release so I could deploy it on my (brand new) Linode production machine running Ubuntu 14.04 LTS. I set up a Docker image on my OSX machine to build the release, and deployed it to my Linode production machine. The memory usage suddenly skyrocketed:

            total..: 97.4 MiB
            atom...: 822.9 KiB
            process: 5.9 MiB
            binary.: 50.8 MiB
            code...: 32.9 MiB
            ets....: 2.0 MiB

Next, I tried running this locally built release on my local Vagrant VM and my local Docker VM, both running Ubuntu 14.04:

            total..: 71.9 MiB
            atom...: 371.5 KiB
            process: 6.4 MiB
            binary.: 50.2 MiB
            code...: 11.4 MiB
            ets....: 997.6 KiB

The code memory is reduced from 33mb to 11mb, but the binary memory is still over 5 times as much as the OSX-built release.

Next, I provisioned a new Digital Ocean droplet which gave me these results:

Brand new Digital Ocean ubuntu 14.04 LTS running locally built image

            total..: 96.3 MiB
            atom...: 822.9 KiB
            process: 6.1 MiB
            binary.: 50.8 MiB
            code...: 32.9 MiB
            ets....: 1.9 MiB

Brand new Digital Ocean ubuntu 14.04 LTS running release built on Digital Ocean

            total..: 71.8 MiB
            atom...: 371.5 KiB
            process: 6.3 MiB
            binary.: 50.2 MiB
            code...: 11.3 MiB
            ets....: 972.4 KiB

So!

Both local virtualized (docker/vagrant) releases uses 3 times as much code memory as the OSX release, and ALL ubuntu built releases (docker/vagrant locally, linode and digitalocean natively) use 5 times as much binary memory as the OSX release.

I have tried building with and without hipe on linux. All my linux examples are without hipe. With hipe, memory usage grows further with 10mb.

The OSX build is with hipe (which confuses me even more).

Any ideas what the reason for this might be, or how I could debug further? I'm not quite sure where to start looking.

**Comment by bitwalker** [comment]
Could you give me a better idea what your app does? The only significant difference from running with mix is that all code modules are loaded when the release is booted, also known as embedded mode, but I can't think of any reason why the releases themselves would differ by that much per-platform.

On second thought, I find it suspicious that the code memory for the release running on Ubuntu 14.04 LTS is 32.9mb - the same on both Linode and DO. It still doesn't explain the binary memory increase when running it in Vagrant/Docker locally, where no code memory increase is observed. Are you using `{include_erts, false}.` by any chance?

**Comment by tmjoen** [comment]
Yes, it's a web application built with Phoenix. I'm not using `{include_erts, false}` — or any `relx.config`. I want to attribute the large code memory by something to do with my linux virtualization on my local OSX machine, since the code memory is reduced to 11mb when I build it on a native linux installation. I find it very strange that the difference between the native OSX release and all the linux releases is so large when it comes to binary memory!

Would the output of `MIX_ENV=prod mix release --verbosity=verbose` be helpful?

**Comment by tmjoen** [comment]
So, an update with some of my experiments!

I created an Amazon t2.micro instance with Ubuntu 14.04 LTS to try and set up a remote build server to see if there is something weird with my OSX environment, but I get similar results building on this machine as well:

            total..: 101.3 MiB
            atom...: 822.9 KiB
            process: 9.7 MiB
            binary.: 50.8 MiB
            code...: 33.0 MiB
            ets....: 2.0 MiB

This is the Amazon build running on my production machine. Next I tried running the Amazon build in my local Vagrant VM:

            total..: 71.6 MiB
            atom...: 371.5 KiB
            process: 6.5 MiB
            binary.: 50.2 MiB
            code...: 10.0 MiB
            ets....: 932.9 KiB

What? OK, so I started looking into how I start these releases.

TURNS OUT

Whenever I see the large code memory usage, it's because I'm starting my application with `foreground`. When I've tested locally I've started it with `console`, and that uses a third of code memory and atom memory.

I still haven't gotten any closer on the binary memory. All my linux built/running releases use 5 times as much binary  memory as my OSX-built/running releases.

**Comment by bitwalker** [comment]
Ah the reason why foreground is using more code/atom memory is because it's running in embedded mode, like it should, and console isn't - but it should, I probably accidentally removed that flag at some point. They should actually be the same, so that's a good catch.

I suspect the binary memory is related to loading something which is present on Linux, but not OSX - what that would be is beyond me. Can you check which processes are using the most memory with observer, and find out which application they are from? That might point us in the right direction.

**Comment by tmjoen** [comment]
When running observer on my production machine, and sorting processes by memory usage, none of them are using much memory. Max is `application_controller` with 449kb, followed by `Elixir.DBConnection.Connection:init/1` with 416kb.

![screen shot 2016-03-17 at 13 32 33](https://cloud.githubusercontent.com/assets/10501945/13846354/bf77b9c2-ec46-11e5-8c12-197ffeb0927f.png)

Running observer on my OSX build shows the same usage. `Elixir.DBConnection.Connection:init/1` is topping the chart with 673kb, with `application_controller` following with 449kb.

![screen shot 2016-03-17 at 13 38 40](https://cloud.githubusercontent.com/assets/10501945/13846366/ccc220a4-ec46-11e5-8391-f492f30d94c2.png)

OSX still shows ~10mb binary memory usage

![screen shot 2016-03-17 at 13 37 55](https://cloud.githubusercontent.com/assets/10501945/13846345/a7ce8b52-ec46-11e5-884f-d351cead8404.png)

while Ubuntu shows ~50mb

![screen shot 2016-03-17 at 13 33 15](https://cloud.githubusercontent.com/assets/10501945/13846327/835162e0-ec46-11e5-8353-f7d8620ea6db.png)

I tried garbage collecting my running node:

```
for p <- :erlang.processes(), do: :erlang.garbage_collect(p)
```

but that doesn't have any impact on the binary memory.

I've done a lot of googling about this, and the closest I got to an "a-ha!" moment was this article by Fred Hebert:

https://blog.heroku.com/archives/2013/11/7/logplex-down-the-rabbit-hole

The "How Erlang's Memory Stuff Works" section where he talks about memory deallocations leaving big unutilized holes. 

I'm not quite sure how to translate his findings into my situation though.

**Comment by bitwalker** [comment]
Hmm, I wonder if some large allocation happens on boot, and then is deallocated, leaving the space unused, but still held by the VM, not sure what it would be specifically, but it seems to vibe with what was described in that post.

**Comment by tmjoen** [comment]
The investigation continues (fits your avatar picture well @bitwalker)!

I started with a brand new phoenix installation on a Ubuntu 14.04 LTS image.

Created a release, and ran it with `console`

```
iex(exrm_tester@vagrant-ubuntu-trusty-64)1> :erlang.memory
[total: 15617320, processes: 4282024, processes_used: 4281984, system: 11335296,
 atom: 331249, atom_used: 304968, binary: 38424, code: 7984132, ets: 507904]
```

Looks great!

Now I changed the deps a bit -> upgrading `phoenix_ecto` to `~> 3.0.0.-beta`.

```
iex(exrm_tester@vagrant-ubuntu-trusty-64)1> :erlang.memory
[total: 70477264, processes: 5548200, processes_used: 5548160, system: 64929064,
 atom: 331249, atom_used: 312315, binary: 52618896, code: 8680146, ets: 760360]
```

So which deps change between these two versions?

```diff
  connection: 1.0.2
  cowboy: 1.0.4
  cowlib: 1.0.2
  db_connection: 0.2.4
  decimal: 1.1.1
- ecto: 1.1.5
+ ecto: 2.0.0-beta.2
- phoenix_ecto: 2.0.1
+ phoenix_ecto: 3.0.0-beta.2
  phoenix_html: 2.5.1
  plug: 1.1.2
- poison: 1.5.2
+ poison: 2.1.0
  poolboy: 1.5.1
  postgrex: 0.11.1
  ranch: 1.2.1
```

I roll back everything to scratch, clean the releases, deps and application itself.

First I upgrade Poison to 2.1.0 - no change.
Then I upgrade Ecto to 2.0.0-beta - blam, memory balloon.

But why on earth doesn't this happen on OSX?

**Comment by bitwalker** [comment]
@tmjoen You are a fantastic detective :). Nice work on finding the source of the issue! I'll be following along on the Ecto thread, very curious to see what the cause ends up being.
