### ISSUE TITLE
Often cannot attach

### ISSUE THREAD

**Issue by aaronjensen** [bitwalker/exrm#315]
We often cannot attach to our process running in production. Specifically, it appears to attach, but I see no IEX prompt. This is what I see:

```
$ bin/booking attach
Using /var/www/booking/releases/2.6.1-5566-g1ade97f/booking.sh
Attaching to /var/www/booking/tmp/erl_pipes/booking/erlang.pipe.4 (^D to exit)

^L
```

Pressing ^D does exit, but that's it. Sometimes I can stop the service and restart it and get it to attach, but obviously that's no good :smile:

**Comment by bitwalker** [comment]
Is it predictable? Or does it happen randomly? I'm not sure what would cause that to happen..

It might also be useful to know your deployment workflow, maybe I can find a way to reproduce if I know what steps lead to that happening.

**Comment by aaronjensen** [comment]
We are using edeliver to deploy. We're not doing hot upgrades. After a deploy, we do a stop followed by a start.

I don't know how to reproduce it consistently, unfortunately. It just seems to happen. I go to attach to a process that has probably been running for a bit and it does that. I wonder if the ^L is a clue. There are multiple people accessing it, so it's very possible that one person has a bad habit that is getting it into this state. Of course, it shouldn't be possible to get it into this state... but...

For a bit today I thought it was that we had hit Ctrl-C and then Ctrl-D once attached, but that has a different (also bad) behavior. It leaves the service in a state where it cannot be stopped normally, you have to kill it. It looks like there is an erl option (`+B`) to disable the break menu, I wonder if we should (and how) enable that.

Ok, so I think I may have found at least one way to repro it. It appears someone left the `console` running instead of the service itself. So, if you run `console` and then attempt to `attach` to it, you get the behavior I described. I'll have to check again to see if that is what is happening next time I see this. I have let the team know that they should not do this :smile:

**Comment by aaronjensen** [comment]
Ok, so I actually misunderstood how things work. As soon as you start a service with `bin/booking start` it starts a console, that's why I saw it in my `ps`. I'm totally stumped.

**Comment by aaronjensen** [comment]
One other hint, my erl pipes directory grows over time:

```
/var/www/booking/tmp/erl_pipes/booking$ ll
total 8
drwxr-xr-x 2 deploy deploy 4096 Mar 17 21:26 ./
drwxr-xr-x 3 deploy deploy 4096 Mar 14 14:23 ../
prw-r--r-- 1 deploy deploy    0 Mar 17 16:28 erlang.pipe.10.r|
prw-r--r-- 1 deploy deploy    0 Mar 17 16:28 erlang.pipe.10.w|
prw-r--r-- 1 deploy deploy    0 Mar 17 23:51 erlang.pipe.11.r|
prw-r--r-- 1 deploy deploy    0 Mar 17 23:51 erlang.pipe.11.w|
prw-r--r-- 1 deploy deploy    0 Mar 14 14:34 erlang.pipe.1.r|
prw-r--r-- 1 deploy deploy    0 Mar 14 14:34 erlang.pipe.1.w|
prw-r--r-- 1 deploy deploy    0 Mar 14 14:50 erlang.pipe.2.r|
prw-r--r-- 1 deploy deploy    0 Mar 14 14:50 erlang.pipe.2.w|
prw-r--r-- 1 deploy deploy    0 Mar 14 16:29 erlang.pipe.3.r|
prw-r--r-- 1 deploy deploy    0 Mar 14 16:29 erlang.pipe.3.w|
prw-r--r-- 1 deploy deploy    0 Mar 16 09:53 erlang.pipe.4.r|
prw-r--r-- 1 deploy deploy    0 Mar 16 09:53 erlang.pipe.4.w|
prw-r--r-- 1 deploy deploy    0 Mar 16 15:24 erlang.pipe.5.r|
prw-r--r-- 1 deploy deploy    0 Mar 16 15:24 erlang.pipe.5.w|
prw-r--r-- 1 deploy deploy    0 Mar 16 21:40 erlang.pipe.6.r|
prw-r--r-- 1 deploy deploy    0 Mar 16 21:40 erlang.pipe.6.w|
prw-r--r-- 1 deploy deploy    0 Mar 17 10:32 erlang.pipe.7.r|
prw-r--r-- 1 deploy deploy    0 Mar 17 10:32 erlang.pipe.7.w|
prw-r--r-- 1 deploy deploy    0 Mar 17 10:35 erlang.pipe.8.r|
prw-r--r-- 1 deploy deploy    0 Mar 17 10:35 erlang.pipe.8.w|
prw-r--r-- 1 deploy deploy    0 Mar 17 15:41 erlang.pipe.9.r|
prw-r--r-- 1 deploy deploy    0 Mar 17 15:41 erlang.pipe.9.w|
```

**Comment by aaronjensen** [comment]
So last night I restarted the service and verified I could attach to it. This morning, I got the `^L` thing. I'm pretty sure no one did anything between those times, so it just appears to be time that causes it.

**Comment by fholzhauser** [comment]
Hi,

I've found this bug report while looking into a similar issue on Erlang release with relx. 
Not sure if it helps your problem, but in my case it was an issue with the TERM environment not being there, when the release is started from an RH init script at boot time. Adding e.g. TERM=xterm to the environment in the init script before starting made attach work for me.

Regards,
Ferenc

**Comment by redbeardster** [comment]
Got the same issue with rebar 2.6.2 under Ubuntu 16.04

**Comment by Rakoth** [comment]
With https://github.com/bitwalker/exrm/commit/420f1a66ff521ef7bc5ca51ecab2542e758931f9 attach always works as described (hangs with ^L and no prompt)

**Comment by fertel** [comment]
https://github.com/bitwalker/exrm/commit/420f1a66ff521ef7bc5ca51ecab2542e758931f9 seems to be breaking behavior for whats expected for start (foreground seems to be the case you want to fix that "bug"). Rebar and in turn relx suggest start should start a console that you can pipe into. http://www.rebar3.org/docs/releases#booting-upgrade-and-inspecting

**Comment by smiley325** [comment]
+1

I'm having the same attach issue (^L character, hangs) in exrm 1.0.6. Downgrading to 1.0.2 seems to fix the issue, so something must have changed in the interm. Any ideas?

**Comment by derek121** [comment]
Much like @fholzhauser, I found this issue while having a similar ^L hanging issue (with an Erlang release via `rebar3 as prod tar`, when deployed via Amazon's CodeDeploy). TERM didn't seem to be set, so adding the `TERM=xterm` allowed successful attach.

**Comment by redink** [comment]
@fholzhauser @derek121 

It works.

THANKS VERY MUCH !!
