### ISSUE TITLE
Can't build a release (upgrade)

### ISSUE THREAD

**Issue by deini** [bitwalker/exrm#317]
I did my first release and everything went smoothly. After a couple of more changes I decided to do another release and I couldn't get it working and I couldn't figure out what I was doing wrong. I decided to nuke everything with `mix release.clean --implode` and re-release and then it worked.

So today I tried again to create a new release and I have the same issue, I can't figure out how to release a new version.

Using:
exrm `1.0.1`
elixir/mix `1.2.3`
phoenix `1.1.4`
Have a `PORT` env variable setup.

```
MIX_ENV=prod mix phoenix.digest
MIX_ENV=prod mix deps.get
MIX_ENV=prod mix compile
MIX_ENV=prod mix release
```

Decided it to run it with `--verbosity=verbose` and this is the output:
```
deini@tracker:~/tracker$ MIX_ENV=prod mix release --verbosity=verbose
Building release with MIX_ENV=prod.
==> Generating relx configuration...
==> Generating sys.config...
==> Generating boot script...
==> Packaging consolidated protocols...
This is an upgrade, verifying appups exist for updated dependencies..
```

And thats it. Nothing else happens. If I go to `rel/tracker/releases` I can't see my new version.

What am I doing wrong?

**Comment by bitwalker** [comment]
Can you upgrade to 1.0.2 and try again? I fixed an issue with logging recently and that issue is probably why you are getting no output.

**Comment by deini** [comment]
Thanks @bitwalker. Tried it again with 1.0.2 and it gave more information.

```
deini@tracker:~/tracker$ MIX_ENV=prod mix release --vervosity=verbose
Building release with MIX_ENV=prod.
This is an upgrade, verifying appups exist for updated dependencies..
==> Unable to access /home/deini/tracker/rel/tracker/releases/0.0.4/tracker.rel: enoent
```
Which indeed `racker.rel` doesn't exist. Any ideas of what I'm doing wrong now?

**Comment by bitwalker** [comment]
@deini Is 0.0.4 the release you are upgrading from, or the one you are upgrading to? It looks to me like perhaps you are running the release from within your project directory (i.e. running `rel/tracker/bin/tracker start` and then `rel/tracker/bin/tracker upgrade "<version>"`), if that's the case, the .rel file is consumed as part of the upgrade, it's not intended to be run from your build directory, so the next time you try to build a release, it will fail like this.

If that's not the case, could you fix the `verbosity` flag in (looks like you typo'd), and gist the full output? I'll take a look and see if there is something else going on.

**Comment by deini** [comment]
My bad, ran it again without the typo
```
deini@tracker:~/tracker$ MIX_ENV=prod mix release --verbosity=verbose
Building release with MIX_ENV=prod.
==> Generating relx configuration...
==> Generating sys.config...
==> Generating boot script...
==> Packaging consolidated protocols...
This is an upgrade, verifying appups exist for updated dependencies..
==> Unable to access /home/deini/tracker/rel/tracker/releases/0.0.4/tracker.rel: enoent
```

0.0.4 is the release I'm upgrading from, which is also the first after nuking everything.

I have a separate `~/releases` folder where I uncompress all my releases so far 0.0.1, 0.0.2, 0.0.3, and 0.0.4.

I am running `MIX_ENV=prod mix release` from my project directory, and then move the tar to my `~/releases` directory (or at least thats what I did with my last releases). 

```
deini@tracker:~/tracker$ rel/tracker/bin/tracker ping
cat: /home/deini/tracker/rel/tracker/releases/start_erl.data: No such file or directory
cat: /home/deini/tracker/rel/tracker/releases/start_erl.data: No such file or directory
Using /home/deini/tracker/rel/tracker/releases//tracker.sh
rel/tracker/bin/tracker: 11: exec: /home/deini/tracker/rel/tracker/releases//tracker.sh: not found
```

```
deini@tracker:~/releases$ bin/tracker ping
Using /home/deini/releases/releases/0.0.4/tracker.sh
pong
```

**Comment by bitwalker** [comment]
Can you try and reproduce with my test project? It's https://github.com/bitwalker/exrm-test, the instructions for executing the test are in the README of the master branch. If we can reproduce it with that, it will definitely help.

**Comment by deini** [comment]
I just went trough the process and everything worked as expected. I did notice I did something different when releasing the first times. 

So when I updated from 0.0.1 -> 0.0.2 I ran `mix release` copied the tar to the root folder of my releases say `/tmp/test/` and unpacked the files right there. So this probably override a couple of files and created the 0.0.2 folder. Could this be what I did wrong?

**Comment by bitwalker** [comment]
@deini Ah yes, that would explain it - release tarballs must be unpacked by the release handler for upgrades/downgrades - if you manually extract them, it definitely will fail in an unexpected way.

Just to recap:

- Initial deployment to the deployment root (i.e. `/tmp/test`)
- Additional deployments:
  - Create versioned release directory (i.e. `/tmp/test/releases/<version>`)
  - Copy upgrade tarball to that directory (i.e. `/tmp/test/releases/<version>/test.tar.gz`)
  - Unpack upgrade with `/tmp/test/bin/test upgrade "<version>"`
- If you are not doing hot upgrades, but rolling releases instead, just deploy to the root (i.e. `/tmp/test`)

**Comment by deini** [comment]
@bitwalker I knew I was doing something wrong, and the instructions are super clear in the docs. I just messed up. Sorry about all the confusion and thanks for your help!

**Comment by bitwalker** [comment]
Hey no worries, if you have any questions, just let me know!

**Comment by itzikbenh** [comment]
Hey,
I have the same problem, but don't understand your solution.
I'm using Phoenix. When I "mix release" It creates the following structure:
rel/play has `bin  erts-7.2  lib  log  releases  relup  running-config  tmp`
First upgrade works well, but second doesn't, because the play.rel is missing so I can't release.
`Unable to access /etc/nginx/app/elixir-phoenix/rel/play/releases/0.0.6/play.rel: enoent
`
When I first upgrade I get this message
`
Release 0.0.8 not found, attempting to unpack releases/0.0.8/play.tar.gz
Unpacked successfully: "0.0.8"
Generating vm.args/sys.config for upgrade...
sys.config ready!
vm.args ready!
Release 0.0.8 is already unpacked, now installing.
Installed Release: 0.0.8
Made release permanent: "0.0.8"
`

I don't understand what I'm supposed to do. The structure that you're showing is what I have I think.

**Comment by bitwalker** [comment]
@itzikbenh This happens if you build and run your release from the same directory, i.e. your project is cloned to `/tmp/somewhere`, you run `mix release`, and then run `/tmp/somewhere/rel/bin/play start`. If you do an upgrade in this directory, the .rel file gets clobbered because of how systools unpacks the release. You need to take the tarball generated in `rel/<app>/releases/<version>/<app>.tar.gz`, and extract that to your deployment target. Do not build and run your release from your project directory.

**Comment by itzikbenh** [comment]
Thanks for quick response. So I will move the tarball, but then how do I run bin/play upgarde? I only have that directory in my project directory. I need to move the whole rel directory outside?

**Comment by bitwalker** [comment]
The tarball contains everything needed to run the release. All you have to do is:

- `tar -xzf play.tar.gz && cd play`
- `bin/play start`

To upgrade:

- `mix release`
- `mkdir -p path/to/play/releases/<new version>`
- `cp rel/play/releases/<new version>/play.tar.gz path/to/play/releases/<new version>/`
- `cd path/to/play && bin/play upgrade <new version>`

**Comment by itzikbenh** [comment]
I get it now, thanks!

**Comment by itzikbenh** [comment]
Works like magic. Thanks a lot for creating this package.
