### ISSUE TITLE
Appups aren't being generated when upgrading Elixir between versions

### ISSUE THREAD

**Issue by Psli** [bitwalker/exrm#321]
I'm having trouble upgrading a phoenix app when creating an exrm release to go from Elixir 1.2.0 to 1.2.3 

```
Provider (relup) failed with: {error,
                                    {rlx_prv_relup,
                                     {relup_script_generation_error,
                                      systools_relup,
                                      {file_problem,
                                       {"/tmp/erlang/test_app/builds/rel/test_app/lib/elixir-1.2.3/ebin/elixir.appup",
                                        {error,
                                         {open,
                                          "/tmp/erlang/test_app/builds/rel/test_app/lib/elixir-1.2.3/ebin/elixir.appup",
                                          enoent}}}}}}}
```

**Comment by bitwalker** [comment]
@Psli Oh damn, the appup generator must be missing the `:elixir` application for some reason. This is something I can fix and push, but I won't be able to get to it right away. If you don't absolutely need to hot upgrade, stopping/starting the app will fix it, otherwise you'll have to wait for the fix :(

**Comment by weixiyen** [comment]
I may have the same issue.  I'm using SemaphoreCI and they recently upgraded both Elixir and Erlang versions.

Source: https://semaphoreci.com/blog/2016/04/19/platform-update-on-apr-26th.html

This command fails - MIX_ENV=prod mix release --verbosity=verbose

It just gave a warning though regarding erts upgrade, no actual error other than that the release failed, and I need to fix it.
