### ISSUE TITLE
Elixir.IEx.CLI.start undef with 1.0.3

### ISSUE THREAD

**Issue by evax** [bitwalker/exrm#323]
On an existing project with previously working releases, upgrading to 1.0.3 causes releases to break.

The application starts and and can be pinged with nodetool but there's an early crash:
```erlang
{error_logger,{{2016,3,28},{18,9,37}},crash_report,[[{initial_call,{supervisor_bridge,user_sup,['Argument__1']}},{pid,<0.173.0>},{registered_name,[]},{error_info,{exit,{undef,[{'Elixir.IEx.CLI',start,[],[]},{user_sup,start_user,3,[{file,"user_sup.erl"},{line,100}]},{user_sup,init,1,[{file,"user_sup.erl"},{line,49}]},{supervisor_bridge,init,1,[{file,"supervisor_bridge.erl"},{line,80}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,352}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}},{ancestors,[kernel_sup,<0.153.0>]},{messages,[]},{links,[<0.154.0>]},{dictionary,[]},{trap_exit,true},{status,running},{heap_size,2586},{stack_size,27},{reductions,272}],[]]}
```
and the rest of the application is not functional.

Reverting to 1.0.2 fixes the issue.

**Comment by bitwalker** [comment]
@evax How are you running the release? Via `./bin/yourapp start`?

**Comment by evax** [comment]
If I do `./bin/myapp start` then that's the situation where the app responds to nodetool pings but is non-functional. Trying to get a shell hangs just after the printing of the erlang version.
I get the trace pasted above when running `./bin/myapp console_clean`.

**Comment by bitwalker** [comment]
Do you get the same thing when running `./bin/myapp foreground`?

**Comment by evax** [comment]
No crash in this case, but no shell either, and a non-functional app. Only nodetool pings are working.

**Comment by martin-langhoff** [comment]
I am seeing a variant on this.  Downgrading to 1.0.2 helps.

**Comment by martin-langhoff** [comment]
@bitwalker -- this affects the exrm_test project

he exam-test project, which is a vanilla as it gets, fails to run
'console_clean' with the same error, invoked as:

```
  rel/test/bin/test console_clean

```

and also 'command' seems to not work. For example this works...

```  $ rel/test/bin/test console
  (...)
  EErlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:2:2]
[async-threads:10] [hipe] [kernel-poll:false]
  Interactive Elixir (1.2.3) - press Ctrl+C to exit (type h() ENTER for help)
  iex(test@iso)1> Elixir.Tzdata.links()
  %{"Europe/Vatican" => "Europe/Rome", "Indian/Antananarivo" =>
"Africa/Nairobi",
    "Asia/Calcutta" => "Asia/Kolkata" (...)
```
but this breaks:

```
  $ rel/test/bin/test command Elixir.Tzdata links
   Using /home/martin/src/exrm-test/rel/test/releases/0.0.1/test.sh
    {"init terminating in
do_boot",{badarg,[{ets,lookup,[tzdata_current_release,release_version],[]},
   {'Elixir.Tzdata.ReleaseReader',current_release_from_table,0,[{file,"lib/tzdata/release_reader.ex"},{line,41}]},{'Elixir.Tzdata.ReleaseReader',simple_lookup,1,[{file,"lib/tzdata/release_reader.ex"},{line,13}]},{'Elixir.Tzdata.ReleaseReader',links,0,[{file,"lib/tzdata/release_reader.ex"},{line,4}]},{init,start_it,1,[]},{init,start_em,1,[]}]}}
```

**Comment by martin-langhoff** [comment]
So with the help of adding `-init_debug` to the script, I narrowed the problem down to Joken, specifically Joken.Signer . Updating Joken cured the problem, though I am not entirely sure how or why.

The update brought:

```
-  "joken": {:hex, :joken, "1.1.0"},
-  "jose": {:hex, :jose, "1.7.1"},
+  "joken": {:hex, :joken, "1.2.0"},
+  "jose": {:hex, :jose, "1.7.3"},
-  "plug": {:hex, :plug, "1.1.2"},
+  "plug": {:hex, :plug, "1.1.3"},
```

@evax reports similar improvements updating Joken.

**Comment by martin-langhoff** [comment]
So the Joken changelog has a reference to `on_load` and working better with exrm :-/ https://github.com/bryanjos/joken/blob/master/CHANGELOG.md and a bit more digging finds https://github.com/bryanjos/joken/pull/120

**Comment by evax** [comment]
Thanks @martin-langhoff for the great analysis
