### ISSUE TITLE
Unable to build a release for a Phoenix project using Exrm 1.0.0+ without first compiling the app

### ISSUE THREAD

**Issue by brienw** [bitwalker/exrm#326]
FULL DISCLOSURE: I'm new to the elixir world, and therefore new to exrm, so I'm not sure if this is a regression or intended behavior in the latest version

I followed the Phoenix documentation on how to build Exrm releases, and the workflow stated for building a release is

```
mix do deps.get, compile
MIX_ENV=prod mix phoenix.digest
MIX_ENV=prod mix release
```

which worked fine when pulling in exrm version 0.19.9, after noticing a much newer version of exrm, I tried the same thing with exrm-1.0.3 and ran into the following error during the `MIX_ENV=prod mix release` step

```
...
===> Running provider resolve_release
===> Solving Release hello_phoenix-0.0.1
===> Provider (resolve_release) failed with: {error,
                                                     {rlx_prv_release,
                                                      {failed_solve,
                                                       {unreachable_package,
                                                        hello_phoenix}}}}
==> ERROR: "Failed to build release. Please fix any errors and try again."
```

I discovered that can get around the build error by running `MIX_ENV=prod mix compile` myself before running mix `MIX_ENV=prod mix release`

After poking around a bit at the commit history, i found that commit 10b2cff09f9af8838ee2c501d4a236034610c872 removed a step `build_project` that used to run the explicit `mix compile` in the build's environment

Here comes the big payoff question:

Should I expect `mix release` to compile my application (in which case I will happily submit a PR to add it back in) or should I instead assume that this is expected behavior, and that I should instead change my workflow to include an explicit `MIX_ENV=prod mix compile` step before I build a release?

**Comment by zipme** [comment]
I ran into the same issue 🤔

**Comment by mgwidmann** [comment]
As all other `mix` commands compile the application before they're run, I'd expect this behavior. But if they took it out pre-1.0, there must have been a reason 😕 

I'd 👍 putting this back in...

**Comment by aaronjensen** [comment]
Gettings this:

```
===> Provider (resolve_release) failed with: {error,
                                                     {rlx_prv_release,
                                                      {failed_solve,
                                                       [{[{[sasl,iex,elixir,
                                                            {booking,
                                                             {<<"2.6.1-7291-gcac66cd">>,
                                                              {[],[]}}}],
                                                           [sasl,iex,elixir,
                                                            {booking,
                                                             {<<"2.6.1-7291-gcac66cd">>,
                                                              {[],[]}}}]}],
                                                         []}]}}}
```

**Comment by pmontrasio** [comment]
I'm getting this too. 

To provide a reproducible test case I cloned https://github.com/bitwalker/exrm-umbrella-test/ and run

    mix deps.get
    MIX_ENV=prod mix compile
    MIX_ENV=prod mix release

and

    Building release with MIX_ENV=prod.
    ==> Failed to build release. Please fix any errors and try again.

Adding ```--verbosity=verbose``` shows

    ===> Running provider resolve_release
    ===> Solving Release app_one-0.0.1
    ===> Provider (resolve_release) failed with: {error,
                                                     {rlx_prv_release,
                                                      {failed_solve,
                                                       {unreachable_package,
                                                        app_one}}}}


In ```mix.exs``` I have

     {:exrm, github: "bitwalker/exrm", branch: "v1"}

I replaced ```v1``` with ```master``` in ```mix.exs``` and ```apps/master_app/mix.exs```.
```mix clean && mix deps.get && MIX_ENV=prod mix.compile && MIX_ENV=prod mix release```
Same error.

If I omit ```MIX_ENV=prod``` I still get the error, v1 and master.

**Comment by bitwalker** [comment]
The explicit compilation is required for the `prod` environment - it's been quite awhile now, so I forget the exact reasoning, but IIRC it was due to a change in mix. That said it looks like there is an issue with my test umbrella project, I'll make a note to take a look.
