### ISSUE TITLE
foreground subtask of boot script ignores RELX_REPLACE_OS_VARS env variable

### ISSUE THREAD

**Issue by werbitzky** [bitwalker/exrm#327]
```rel/<projectname>/bin/<projectname> start``` while ```RELX_REPLACE_OS_VARS=true``` provides a good way to dynamically configure a release based on environment variables at runtime as stated in https://github.com/bitwalker/exrm/issues/90
the custom boot script however irgnores this env. variable when executing the ```foreground``` subtask. 

Generating the bootscript automatically instead of using the custom provided one (see https://github.com/werbitzky/exrm/commit/f5f2d2682cf362a453cc94805cebaab7a8712286) fixes the problem and ```RELX_REPLACE_OS_VARS``` is no longer ignored, maybe the custom boot script is based on a too old version of the original? Is there a strong reason not to use the generated one?

**Comment by bitwalker** [comment]
There are a few reasons why exrm uses a forked version of the extended start script from relx:

1.) support for running an Elixir shell when running the release interactively
2.) ensures consolidated protocols are added to the release package and added to the code path when booting the release
3.) hooks for conform (if you use it, if not, then you can ignore this point)

The first two are the primary reason. There is no way (at least that I have found so far) to add in that support after generating the start script, and 1 is a big user-facing feature, and 2 is a critical performance requirement. Anyway, the `RELX_REPLACE_OS_VARS` support *was* working, but it looks like something may have broken it, at least for the foreground command.

**Comment by emerleite** [comment]
I just tryed RELX_REPLACE_OS_VARS and it's working like a charm on exrm 1.0.4

**Comment by werbitzky** [comment]
Thank you @bitwalker for the good explanation, I'll try it out with 1.0.4 @emeleite :)

**Comment by emerleite** [comment]
@werbitzky @bitwalker I'm really having issues with foreground and RELX_REPLACE_OS_VARS. Only works with start

**Comment by bitwalker** [comment]
@emerleite Could you give [distillery](https://github.com/bitwalker/distillery) a try as a replacement for exrm? I don't recall having this issue with exrm, but I'm running several apps in production using the `foreground` task and `REPLACE_OS_VARS=true` without issue with distillery.

**Comment by emerleite** [comment]
@bitwalker I'll give `distillery` a try. But I was wrong. `foreground` with `REPLACE_OS_VARS=true` is working with exrm. Thanks ;)
