### ISSUE TITLE
Cowboy worker :killed when server under load

### ISSUE THREAD

**Issue by mgwidmann** [bitwalker/exrm#330]
Following this gist: https://gist.github.com/mgwidmann/7162c6da59e027a3f0617575fb147897 but using `fib/36` instead of `fib/35` as it shows in the script causes the cowboy worker to die. 

Heres what the log points out:

```
01:06:10.177 [error] Ranch listener Hotcode.Endpoint.HTTP had connection process started with :cowboy_protocol:start_link/4 at #PID<0.5429.0> exit with reason: :killed
```

More information can be found here: https://groups.google.com/forum/#!topic/phoenix-talk/GmbKMPko8kM

This very well may be a cowboy issue.

**Comment by mgwidmann** [comment]
So from what I've found, my workers are getting sent a `brutal_kill` message because thats what the generated `relup

**Comment by mgwidmann** [comment]
Using the following `.appup` file solves the problem:

```
{"0.0.2",
 [{"0.0.1",
   [{load_module,'Elixir.Hotcode.Endpoint',brutal_purge,soft_purge,[]},
    {load_module,'Elixir.Hotcode.Fib',brutal_purge,soft_purge,[]},
    {load_module,'Elixir.Hotcode.ErrorHelpers'},
    {load_module,'Elixir.Hotcode.Gettext'},
    {load_module,'Elixir.Hotcode.Repo'},
    {load_module,'Elixir.Hotcode.Router.Helpers'},
    {load_module,'Elixir.Hotcode.Router',brutal_purge,soft_purge,[]}]}],
 [{"0.0.1",
   [{load_module,'Elixir.Hotcode.Endpoint',brutal_purge,soft_purge,[]},
    {load_module,'Elixir.Hotcode.Fib',brutal_purge,soft_purge,[]},
    {load_module,'Elixir.Hotcode.ErrorHelpers'},
    {load_module,'Elixir.Hotcode.Gettext'},
    {load_module,'Elixir.Hotcode.Repo'},
    {load_module,'Elixir.Hotcode.Router.Helpers'},
    {load_module,'Elixir.Hotcode.Router',brutal_purge,soft_purge,[]}]}]}.
```

Is there any way to know to do this besides testing it out manually like I did? i.e. how can I recognize code that will need soft purging?

**Comment by bitwalker** [comment]
@mgwidmann This is one of the caveats of hot upgrades/downgrades with Erlang. The auto generated appups are best effort, but may not always work for all applications. Pre-exrm, appups were written by hand (or people wrote their own appup generators), and in general, doing hot upgrades/downgrades requires intimate knowledge of how your app should be upgraded/downgraded. For most cases, the auto-generated appups exrm produces are good enough, but it will never be able to cover all the edge cases.

However, I can look into whether there is a way I can "smarten" up the appup generator to soft purge based on some critiera. Problem is, I'm not sure what the criteria is specifically. Could you describe in more detail what led you to making that change? That might give me some ideas.

**Comment by mgwidmann** [comment]
@fishcakez helped me out on slack to get this file working. We mostly toyed around with it, and through trial and error came up with that file. I'm not sure how I would come up with this file on an actual project, which is why I was concerned.

I understand if you don't know how to do this programmatically, maybe it would help if there was more information on writing appup files on the wiki.

**Comment by ibizaman** [comment]
@mgwidmann It's not an easy subject but doc exists:
http://erlang.org/doc/man/appup.html
http://erlang.org/doc/design_principles/appup_cookbook.html
http://learnyousomeerlang.com/relups
https://www.metabrew.com/article/erlangotp-releases-rebar-release_handler-appup-etc
