### ISSUE TITLE
Unable to shutdown umbrella app

### ISSUE THREAD

**Issue by AaronBetterOfficeApps** [bitwalker/exrm#333]
Our application is in an umbrella project with a phoenix app as the master application.

 It builds and runs fine in production, but hangs on shutdown when using the `bin/my_app stop` command. It prints ok and just hangs there without shutting down beam.

 If the other application in the umbrella app is taken out of the application list in the mix file of the master application(phoenix app) then the `bin/my_app stop` works as expected. 

Is there any special configuration of commands that need to be used with an umbrella app for the commands to work correctly?

**Comment by ibizaman** [comment]
Can you stop the application by issuing `bin/my_app remote` then `:init.stop` ?
