### ISSUE TITLE
Passing command line args to start function

### ISSUE THREAD

**Issue by danturn** [bitwalker/exrm#334]
Hi guys, 

I can't work out how to pass command line args to the start function in my application (Client). e.g. "--log-level debug" (an arg my application understands)

my mix file looks like this:

`defmodule Client.Mixfile do
  use Mix.Project

  def project do
    [app: :client,
     version: "0.0.0",
     deps_path: "../../deps",
     lockfile: "../../mix.lock",
     elixir: "~> 1.1",
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps]
  end

  def application do
    [
      applications: [:lager, :core, :json],
      mod: {Client, []}
    ]
  end

  defp deps do
    [
      {:exrm, "~> 1.0.3"},
      {:core, in_umbrella: true},
      {:lager, github: "basho/lager"},
      {:json, "~> 0.3.0"}
    ]
  end
end`

any help would be gratefully received!

**Comment by ibizaman** [comment]
Did you try something like this? http://asquera.de/blog/2015-04-10/writing-a-commandline-app-in-elixir/
