### ISSUE TITLE
running_config sys.config incorrect

### ISSUE THREAD

**Issue by pdilyard** [bitwalker/exrm#335]
Upon building a clean release on my local machine, I have the following files:

``` elixir
# myapp.schema.exs
[
  mappings: [
    ...
    "myapp.http.port": [
      doc: "The port on the local machine that the app will mount to",
      to: "myapp.Elixir.MyApp.Endpoint.http.port",
      datatype: :integer,
      default: 4000
    ],
    "myapp.url.host": [
      doc: "A hostname at which this application can be reached",
      to: "myapp.Elixir.MyApp.Endpoint.url.host",
      datatype: :binary,
      default: "example.com"
    ],
    "myapp.url.port": [
      doc: "The port that pairs with the hostname",
      to: "myapp.Elixir.MyApp.Endpoint.url.port",
      datatype: :integer,
      default: 80
    ],
    "myapp.secret_key_base": [
      doc: "A secret key used by Phoenix",
      to: "myapp.Elixir.MyApp.Endpoint.secret_key_base",
      datatype: :binary,
      default: "redacted"
    ],
    ...
  ],
  translations: [
    ...
  ]
]
```

```
# myapp.conf

# The port on the local machine that the app will mount to
myapp.http.port = 4000

# A hostname at which this application can be reached
myapp.url.host = "example.com"

# The port that pairs with the hostname
myapp.url.port = 80

# A secret key used by Phoenix
myapp.secret_key_base = "redacted"
```

``` erlang
% rel/myapp/releases/1.0.1/sys.config

[{sasl,[{errlog_type,error}]},
...
 {logger,
     [{console,
          [{format,<<"$time $metadata[$level] $message\n">>},
           {metadata,[request_id]}]},
      {level,info}]},
 {phoenix,[{serve_endpoints,true}]},
 {myapp,
      {env,prod},
      {'Elixir.MyApp.Endpoint',
          [{http,[{port,4000}]},
           {url,[{host,<<"localhost">>}]},
           {secret_key_base,
               <<"redacted">>},
           {render_errors,
               [{accepts,[<<"json">>]},{view,'Elixir.MyApp.ErrorView'}]},
           {pubsub,
               [{name,'Elixir.MyApp.PubSub'},
                {adapter,'Elixir.Phoenix.PubSub.PG2'}]},
           {server,true},
           {root,<<".">>}]}]}
...
 ].
```

So far so good, the release seems to have generated properly. However, when I run the app with `./rel/myapp/bin/myapp start`, the following gets used as the config:

``` erlang
% rel/myapp/running-config/sys.config

[{sasl,[{errlog_type,error}]},
 {logger,
     [{console,
          [{format,<<"$time $metadata[$level] $message\n">>},
           {metadata,[request_id]}]},
      {level,info}]},
 {phoenix,[{serve_endpoints,true}]},
 {myapp,
     [{'Elixir.MyApp.Endpoint',
          [{secret_key_base,<<"redacted">>},
           {url,[{port,80},{host,<<"example.com">>}]},
           {http,[{port,4000}]}]},
      {env,prod}
     ...
    ].
```

As you can see, there's a substantial amount of configuration missing from `MyApp.Endpoint`. I was led to this issue because Phoenix PubSub wasn't working, and I eventually investigated the exrm config, as I was not having this issue running in dev.

I tried asking on the Elixir Slack, but we couldn't figure it out there, so I hope it's ok that I created an issue! 😄

**Comment by smpallen99** [comment]
I have a very similar issue which I'm trying to troubleshoot right now. The running_config/sys.config file is not being created with app.conf file.

**Comment by pdilyard** [comment]
I think this issue is slightly different than that. For me, it appears that _only_ items in the app.conf file are being used in the running-config/sys.config file

**Comment by martin-langhoff** [comment]
What exrm / conform versions in use? I might be affected by same or similar issue. 

```
conform_exrm 1.0.0
exrm 1.0.3
conform 2.0.0
```

**Comment by smpallen99** [comment]
I found my issue. I had left configuration in prod.exs after I had removed the schema and config. So my sys.config was picking up the stuff in prod.exs. Silly mistake.

**Comment by pdilyard** [comment]
My exrm version is `0.19.0`. At this point I've ditched conform and I'm now using env variables at build time, because it obviously wasn't acceptable for none of the configuration to be working in production for 9 days 😞 

I'd still love to see this issue resolved though.

**Comment by bitwalker** [comment]
I would be very interested to know if your issue is resolved in the latest exrm and conform versions, I suspect it is, but if you could confirm one way or the other they would be hugely helpful!
