### ISSUE TITLE
`{include_erts, false}.` excludes stdlib and other erlang dependencies

### ISSUE THREAD

**Issue by kennyballou** [bitwalker/exrm#336]
# Reproduction #

Using the [exrm-test][1] project as a base, create the `./rel` directory and
add a `relx.config` with the following:

    $ mkdir rel
    $ cat << EOF > ./rel/relx.config
    {include_erts, false}.
    EOF

Create the release:

    $ MIX_ENV=prod mix do deps.get, compile, release

Check the output of `./rel/test/lib/`:

    $ ls ./rel/test/lib
    certifi-0.4.0  hackney-1.6.0  logger-1.2.4   ssl_verify_fun-1.1.0
    tzdata-0.5.7 combine-0.7.0  idna-1.2.0     metrics-1.0.1  test-0.0.1
    elixir-1.2.4   iex-1.2.4      mimerl-1.0.2   timex-2.0.0

# Expected Output #

Using the same steps as above, without creating the `relx.config` file, the
`./rel/test/lib` folder contains the expected output:

    $ ls ./rel/test/lib
    asn1-4.0.2      hackney-1.6.0  mimerl-1.0.2          test-0.0.1
    certifi-0.4.0   idna-1.2.0     public_key-1.1.1      timex-2.0.0
    combine-0.7.0   iex-1.2.4      sasl-2.7              tzdata-0.5.7
    compiler-6.0.3  kernel-4.2     ssl-7.3 crypto-3.6.3    logger-1.2.4
    ssl_verify_fun-1.1.0 elixir-1.2.4    metrics-1.0.1  stdlib-2.8

# Other Notes #

As a side note, adding `{system_libs, true}.` explicitly to `./rel/relx.config`
does not solve this issue, none of the Erlang/system libraries are included.

All steps above were done on Arch Linux.

    $ elixir --version
    Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

    Elixir 1.2.4

[1]: https://github.com/bitwalker/exrm-test

**Comment by bitwalker** [comment]
They shouldn't be included, by not bundling ERTS, modules which are linked to that specific ERTS installation will be loaded from the ERTS on the target system (where you are deploying the release to).
