### ISSUE TITLE
stdlib and kernel undefined when adding httpoison after timex

### ISSUE THREAD

**Issue by manukall** [bitwalker/exrm#339]
See my for of the test project at https://github.com/manukall/exrm-test/blob/stdlib_kernel_undefined/mix.exs.

When adding `httpoison` after `timex` in the applications list, `mix release --verbosity=verbose` results in 

```
...
===> Provider (release) failed with: {error,
                                             {rlx_prv_assembler,
                                              {release_script_generation_error,
                                               systools_make,
                                               {undefined_applications,
                                                [stdlib,kernel]}}}}
```

Moving `httpoison` in the applications list to before `timex` (so it becomes `[:logger, :httpoison, :timex]`) fixes the error.

I have no idea what's going on here and I find the error particularly weird, as it indicates only `sdtlib` and `kernel` are undefined. `httpoison` only depends on `hackney` and putting this directly into the applications instead of `httpoison` does not result in the error describe.

**Comment by dmarkow** [comment]
Same exact error here. Moving `:timex` to the end of my applications list fixed it.

**Comment by bitwalker** [comment]
That is really odd. A coworker of mine just reported the same issue, so this is definitely an issue. I have a couple of ideas I can test, but at least we have a workaround for the interim. Thanks for the report!

**Comment by vdaniuk** [comment]
Same problem here with the :quantum package which depends on Timex. Moving it to the end of the deps worked. Feeling much better now, thx for the solution.
