### ISSUE TITLE
Including but not running app

### ISSUE THREAD

**Issue by alg** [bitwalker/exrm#345]
Thanks for the great tool!

I've got a problem with including Amnesia with the release of the app. According to the doc of mnesia, I need to run `:mnesia.create_schema` before the mnesia app is started, however, I can't do that because I include Amnesia (and thus mnesia) into the :applications list for exrm to package it. If I don't include it, the app is (correctly) not started, but at the same time it's not packaged into release either.

Please advise.

**Comment by antipax** [comment]
@alg use :included_applications rather than :applications, and then start the application manually in your application's start func.

**Comment by alg** [comment]
@antipax :included_applications starts applications (:mnesia) this application (Amnesia) depends on. Doesn't work for me.

**Comment by antipax** [comment]
Included apps doesn't start applications. Maybe you need to put both mnesia
and amnesia in there.

**Comment by bitwalker** [comment]
@alg `:included_applications` by definition does not start applications, and is the right solution for your question. I think @antipax has the right idea, and that you should put both amnesia and mnesia in `:included_applications`.

**Comment by alg** [comment]
@antipax, @bitwalker Unfortunately, it's not what I see. Here's the test repo (forgive the uninventive naming) -- https://github.com/alg/ttt

    $ mix do deps.get
    $ MIX_ENV=prod mix compile
    $ MIX_ENV=prod mix release
    $ rel/ttt/bin/ttt console

    ... you will get the list of started apps shown. Please tell me that it doesn't contain ":mnesia".

If I run the app with `mix phoenix.server`, it all works as you guys describe. But if I build the release and run it, I get :mnesia among the started applications.

**Comment by antipax** [comment]
That's not a problem, you want the :mnesia application started. In fact, that's required for create_schema.

**Comment by alg** [comment]
@antipax That's the whole point. You can't create schema with running :mnesia. It won't let you. Here's the sequence:

     1> mnesia:create_schema([node()]).
     ok
     2> mnesia:start().
     ok
     3> mnesia:create_table(funky, []).
     {atomic,ok}

**Comment by antipax** [comment]
@alg `:application.which_applications/0` is not the started applications: 

```
iex(ttt@Erics-iMac)2> Application.started_applications |> Enum.map(fn {app, _, _} -> app end)
[:sasl, :iex, :ttt, :phoenix, :poison, :eex, :phoenix_pubsub, :phoenix_html,
 :plug, :cowboy, :ranch, :cowlib, :crypto, :gettext, :logger, :exquisite,
 :elixir, :compiler, :stdlib, :kernel]
```

**Comment by alg** [comment]
@antipax I didn't get your last comment. Here's what I can see in the source code of Application:

    def started_applications(timeout \\ 5000) do
      :application.which_applications(timeout)
    end

Also, are you sure you started the console from the release with: `rel/ttt/bin/ttt console` ? I'm asking, because I don't see the app in the list when launched with `iex -S mix phoenix.start` or `iex -S mix`.

**Comment by antipax** [comment]
@alg well, I just kinda assumed it was the loaded applications and not the started ones, my bad. The first thing I did when the application started was use Application.started_applications because I am more familiar with that than `:application.which_applications`. I did start it with `rel/ttt/bin/ttt console`, here's what's printed by your code on my machine:

```[{:phoenix, 'Productive. Reliable. Fast. A productive web framework that\ndoes not compromise speed and maintainability.\n', '1.2.0-rc.0'}, {:poison, 'An incredibly fast, pure Elixir JSON library', '2.1.0'}, {:eex, 'eex', '1.2.4'}, {:phoenix_pubsub, 'Distributed PubSub and Presence platform\n', '1.0.0-rc.0'}, {:phoenix_html, 'Phoenix.HTML functions for working with HTML strings and templates', '2.5.1'}, {:plug, 'A specification and conveniences for composable modules between web applications', '1.1.4'}, {:cowboy, 'Small, fast, modular HTTP server.', '1.0.4'}, {:ranch, 'Socket acceptor pool for TCP protocols.', '1.2.1'}, {:cowlib, 'Support library for manipulating Web protocols.', '1.0.2'}, {:crypto, 'CRYPTO', '3.6.3'}, {:gettext, 'Internationalization and localization through gettext', '0.11.0'}, {:logger, 'logger', '1.2.4'}, {:exquisite, 'DSL to match_spec', '0.1.6'}, {:elixir, 'elixir', '1.2.4'}, {:compiler, 'ERTS  CXC 138 10', '6.0.3'}, {:stdlib, 'ERTS  CXC 138 10', '2.8'}, {:kernel, 'ERTS  CXC 138 10', '4.2'}]```

**Comment by alg** [comment]
@antipax ah, ok, no problem. Here's what I get:

` → rel/ttt/bin/ttt console
Using /Users/alg/tmp/ttt/rel/ttt/releases/0.0.1/ttt.sh
Exec: /Users/alg/tmp/ttt/rel/ttt/erts-7.2.1/bin/erlexec -boot /Users/alg/tmp/ttt/rel/ttt/releases/0.0.1/ttt -mode embedded -config /Users/alg/tmp/ttt/rel/ttt/running-config/sys.config -boot_var ERTS_LIB_DIR /Users/alg/tmp/ttt/rel/ttt/erts-7.2.1/../lib -env ERL_LIBS /Users/alg/tmp/ttt/rel/ttt/lib -pa /Users/alg/tmp/ttt/rel/ttt/lib/ttt-0.0.1/consolidated -args_file /Users/alg/tmp/ttt/rel/ttt/running-config/vm.args -user Elixir.IEx.CLI -extra --no-halt +iex -- console
Root: /Users/alg/tmp/ttt/rel/ttt
/Users/alg/tmp/ttt/rel/ttt
Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

[{:phoenix, 'Productive. Reliable. Fast. A productive web framework that\ndoes not compromise speed and maintainability.\n', '1.2.0-rc.0'}, {:poison, 'An incredibly fast, pure Elixir JSON library', '2.1.0'}, {:eex, 'eex', '1.2.2'}, {:phoenix_pubsub, 'Distributed PubSub and Presence platform\n', '1.0.0-rc.0'}, {:phoenix_html, 'Phoenix.HTML functions for working with HTML strings and templates', '2.5.1'}, {:plug, 'A specification and conveniences for composable modules between web applications', '1.1.4'}, {:cowboy, 'Small, fast, modular HTTP server.', '1.0.4'}, {:ranch, 'Socket acceptor pool for TCP protocols.', '1.2.1'}, {:cowlib, 'Support library for manipulating Web protocols.', '1.0.2'}, {:crypto, 'CRYPTO', '3.6.2'}, {:gettext, 'Internationalization and localization through gettext', '0.11.0'}, {:logger, 'logger', '1.2.2'}, {:mnesia, 'MNESIA  CXC 138 12', '4.13.2'}, {:exquisite, 'DSL to match_spec', '0.1.6'}, {:elixir, 'elixir', '1.2.2'}, {:compiler, 'ERTS  CXC 138 10', '6.0.2'}, {:stdlib, 'ERTS  CXC 138 10', '2.7'}, {:kernel, 'ERTS  CXC 138 10', '4.1.1'}]`

I must admit, this is weird. I can clearly see it in the list and it drives me mad. :) Ok, I'll get :observer going and try to figure where the discrepancy is coming from. In the mean time which Elixir / Erlang versions are you using?

**Comment by antipax** [comment]
@alg 18.3 and 1.2.4.

Is there already an existing mnesia schema on disk? Maybe it's checking and starting mnesia automatically if so.

**Comment by alg** [comment]
@antipax nope. I'm having exactly what you have. That's why I isolated this case in its own repo.

**Comment by alg** [comment]
@antipax updating Elixir to 1.2.5 to try that. I was at 1.2.2 as you could see.

**Comment by antipax** [comment]
@alg ok, I figured it out. You have to add :mnesia to your included_applications as well. I mistakenly thought I'd added it to mix.exs to test it but not saved before building. Once I removed that and re-built it showed up in the started apps as well.

**Comment by alg** [comment]
@antipax great detective work, thanks! Now the only question that bothers me is why would running the release (`rel/ttt/bin/ttt console`) behave differently to running through interactive shell (`iex -S mix`). But at least I know now I'm not totally crazy and included app dependencies are indeed started even though the very included app is not. :) Thanks for checking it for me!

**Comment by antipax** [comment]
@alg no problem, sorry for the confusion on my end as well. :)

**Comment by bitwalker** [comment]
@alg Running a release versus running via mix (i.e. `iex -S mix`) is different for a number of reasons. One major difference is that the release runs in embedded mode, meaning all applications in the release are loaded when the release starts, and only those applications which are either in `applications` or `included_applications`. `iex -S mix` will dynamically load/start applications as needed, including those which you haven't specified in `mix.exs` (if you forgot one for example). The release is also not run via mix at all, but via `run_erl`, an ERTS tool. The former you can emulate with `iex` by running `MIX_ENV=prod iex -S mix`, assuming that you have `build_embedded: Mix.env == :prod` and `start_permanent: Mix.env == :prod` in your `mix.exs`.

**Comment by alg** [comment]
@bitwalker fantastic explanation, thanks mate!

**Comment by ylankgz** [comment]
@alg Probably, you can get rid of Amnesia and setup mnesia directly in erlang and put it into `/src`. Inside module create schema, start mnesia, create tables and then stop
