### ISSUE TITLE
option to silence echo "Using $RELEASES_DIR/$REL_VSN/$REL_NAME.sh"

### ISSUE THREAD

**Issue by smpallen99** [bitwalker/exrm#355]
The above line in `priv/rel/files/boot_shim` is causing us issues. Right now, we are need to remove the line post install which is kind of ugly. Could you add an option to suppress this line? Or is there some other option available?

**Comment by bitwalker** [comment]
I think we can remove this entirely actually - it's not really needed, at one point I added it because it was useful, but to be honest it's not all that useful anymore. I'll make the change :)

**Comment by bitwalker** [comment]
Fixed in 6df2765
