### ISSUE TITLE
RELEASE_CONFIG_FILE isn't respected on upgrade.

### ISSUE THREAD

**Issue by brentonannan** [bitwalker/exrm#363]
It seems that RELEASE_CONFIG_FILE isn't respected when used with upgrade - app/running-config/app.conf gets replaced with the app.conf provided with the release (which is all empty strings for me because secrets).

(From my comment [here](https://github.com/bitwalker/conform_exrm/issues/1#issuecomment-221749100))

**Comment by aaronjensen** [comment]
@brentonannan It did for us, I believe, but we had to ensure that the user/script running the upgrade had that environment variable set, which, for us, because we were using edeliver, required us to put it in the deploy user's `.profile`, I believe.
