### ISSUE TITLE
erts is still being bundled with release even with include_erts = false

### ISSUE THREAD

**Issue by elpddev** [bitwalker/exrm#365]
I am not sure if this is a bug and not a desired behavior.
1. Build a release without relx.config and its options => I get a release is built with erts.
2. Setting file rel/relx.config with {include_erts, false}. 
3. Build release => release is still being built with erts.

Only after I deleted the project dir in "rel/" which includes the erts lib that was put there by step 1, and then running the build again, then the release is built without the erts bundled.

**Comment by keithmattix** [comment]
Did you run `mix release.clean` before hand? `mix.release` doesn't clear out the rel directory, so I'm pretty sure you have to do it manually.

**Comment by bitwalker** [comment]
@keithmattix is correct, if you don't clean first, files that are under rel will not be deleted, only overwritten.

**Comment by elpddev** [comment]
I did do `mix release.clean`. It removes the specific release 0.0.1 folder in the `releases` folder.
It does not however removes the `erts-7.3` folder in the `rel/app-name/` folder. After that, doing a release again the erts still get bundled.

**Comment by bitwalker** [comment]
Ah I know what's happening. Reopening..

**Comment by felipesere** [comment]
Any update on this? I am also seeing stuff in `rel/<app-name>/lib` that I am not expecting as I use `{:include_erts, false}.`

**Comment by zhaohansprt** [comment]
so how to deal with this problem I meet this  too

**Comment by bitwalker** [comment]
@zhaohansprt At this point, my recommendation is to migrate to [distillery](https://github.com/bitwalker/distillery). My time is fairly constrained, so exrm gets little love these days. If there is a reason why you haven't migrated yet, please open an issue on the Distillery tracker (if one isn't already open), and I will look into it ASAP.
