### ISSUE TITLE
Remove vm.args from `command` task

### ISSUE THREAD

**Issue by hayesgm** [bitwalker/exrm#367]
When running `bin/my_release command`, we add `-args $VMARGS_PATH`, which probably isn't sensible as we want to run a task, not connect to an existing node. When I try to run a command on a live server, I thus get the following issue:

```erlang
{error_logger,{{2016,6,21},{22,4,1}},"Protocol: ~tp: the name my_project@my_host seems to be in use by another Erlang node",["inet_tcp"]}
```

Do we have a good reason why we include `vm.args` in the `command` release command? Does it make sense to remove it?

Relates to PR #368

**Comment by bitwalker** [comment]
Your PR addresses this so I'm going to close this issue. Thanks for reporting!
