### ISSUE TITLE
Generated binary doesnt work when there is a space in directory path

### ISSUE THREAD

**Issue by insiderq** [bitwalker/exrm#371]
After successfull building of my project when i attempt to run binary
I've got the following error when i used my "Non Dropbox" folder with a space in the path.

`~/Non Dropbox/invoices/invoices ➭ rel/invoices/bin/invoices
cat: /Users/username/Non: No such file or directory
cat: Dropbox/invoices/invoices/rel/invoices/releases/start_erl.data: No such file or directory
cat: /Users/username/Non: No such file or directory
cat: Dropbox/invoices/invoices/rel/invoices/releases/start_erl.data: No such file or directory
rel/invoices/bin/invoices: line 10: /Users/username/Non Dropbox/invoices/invoices/rel/invoices/releases//invoices.sh: No such file or directory
rel/invoices/bin/invoices: line 10: exec: /Users/username/Non Dropbox/invoices/invoices/rel/invoices/releases//invoices.sh: cannot execute: No such file or directory`

**Comment by OnorioCatenacci** [comment]
@insiderq Spaces in directory names cause issues on both Windows and Linux.  If I were you I'd but things into a directory that has no spaces in the name.

**Comment by ibizaman** [comment]
I would also avoid paths with spaces although it would be worth adding that to the documentation.
