### ISSUE TITLE
Running release without distribution...

### ISSUE THREAD

**Issue by danturn** [bitwalker/exrm#372]
Hi, 

Is there any way to run without distribution? 

i've tried setting 
  -sname nonode@nohost
  -setcookie nocookie
in the vm.args file but i get the following error
"Invalid node name: ~p~n",['nonode@nohost']}

dan

**Comment by bitwalker** [comment]
Without distribution there is no way for the start script to talk to the running node, so no, there is no way to disable distribution entirely. If the concern is security, you can set `-hidden` in the vm.args, along with a randomly generated cookie, and the node will not be visible to other nodes unless explicitly configured to connect to that node with the correct cookie.
