### ISSUE TITLE
Relup not found

### ISSUE THREAD

**Issue by wende** [bitwalker/exrm#379]
Building and upgrading on Ubuntu 14.04

```
release 0.0.2 is already unpacked, now installing.
escript: exception error: no case clause matching
                 {error,{enoent,"/home/user/user/rel/project/releases/0.0.1/relup"}}
```

There is no `rel/relx.config` file as stated in the docs

Exrm version 1.0.8

**Comment by wende** [comment]
Exact same behaviour with /bitwalker/distillery

**Comment by bitwalker** [comment]
Are you building the release and upgrading it from the directory the release is output to? That won't work, you have to deploy the release to another directory. Some files get removed by the release handler when installing an upgrade, and this causes future upgrades to fail.

**Comment by Sitch** [comment]
I just ended up doing `mix release.clean --implode --no-confirm` and starting from scratch.  I tried just doing `mix release.clean` on the server and redeploying but to no avail.  Anyone have a better solution?
