### ISSUE TITLE
reduce permissions on sys.config

### ISSUE THREAD

**Issue by kf8a** [bitwalker/exrm#380]
Since sys.config can contain sensitive info (passwords, etc) it might be good if the permissions for the file were 600 instead of 644. I could add a chmod to `generate_sys_config` in mix/task/release.ex, but maybe it should be handled by relx instead. Thoughts?

**Comment by bitwalker** [comment]
We always pass our own `sys.config` to relx, so adding the call to `File.chmod` in `generate_sys_config` is the way to go on this one.

**Comment by kf8a** [comment]
Ok, thanks. I'll get PR ready.
