### ISSUE TITLE
Generating upgrade fails when attaching git revision to version

### ISSUE THREAD

**Issue by ali-l** [bitwalker/exrm#384]
I changed my version to use the first 7 characters of the git revision, ex. `0.1.7-48a3892`. After this, upgrade generation failed: `Appup generation failed with bad_new_appvsn`. I cleaned my `rel/` folder with `mix release.clean --implode` and tried to generate a fresh release and it worked fine. Then went to generate an upgrade for `0.1.7-6623b73`, and it is failing for the same reason.

I took the git revision off and generated an upgrade for `0.1.7`, which worked fine.

Any idea what I'm doing wrong? Verbose mode doesn't seem to reveal much.

Using `exrm 1.0.8`, `elixir 1.3.2`, `phoenix 1.2.0`

**Comment by bitwalker** [comment]
You must use the `git-describe` format, i.e. `x.x.x-<num of commits since tag>-<shorthash of tag>`, so using your example, it'd be something like `0.1.7-1-48a3892`.
