### ISSUE TITLE
RELX_REPLACE_OS_VARS boot script fails on awk with env vars containing certain characters

### ISSUE THREAD

**Issue by novaugust** [bitwalker/exrm#390]
we had an environment variable, `export DB_PASSWORD='Pntu>x9hC<6&zX:e'` that prevented the boot script from getting anywhere, freezing in this area

```sh
if [ $RELX_REPLACE_OS_VARS ]; then
    awk '{while(match($0,"[$]{[^}]*}")) {var=substr($0,RSTART+2,RLENGTH -3);gsub("[$]{"var"}",ENVIRON[var])}}1' < $SYS_CONFIG > $SYS_CONFIG.2.config
    SYS_CONFIG=$SYS_CONFIG.2.config
fi
```

[source on GH](https://github.com/bitwalker/exrm/blob/9184f2e890cdd2692d43024a153c14d4bb7f7eae/priv/rel/files/boot#L181-L184)

changing to another password fixed the script and got our app up and running.

**Comment by bitwalker** [comment]
Interesting, I'll have to dig in to awk a bit to figure out why it's choking on that string. Thanks for reporting!

**Comment by novaugust** [comment]
Just had this happen with another password. Seems like the bad character is the `&`

**Comment by bitwalker** [comment]
@novaugust I fixed this in distillery, but haven't yet ported the fix to exrm. You can see the commit where I did so referenced above. I'll push the fix to exrm as soon as I'm able.
