### ISSUE TITLE
Raspbian Jessie with erlang 19 failed to start release

### ISSUE THREAD

**Issue by samuelebistoletti** [bitwalker/exrm#402]
I'm trying to start a release packaged on Ubuntu 16.10 with Elixir 1.3 and Erlang 19. The release has been deployed on a RaspberryPi 3 running Raspian Jessie with Erlang 19 compiled from source (tried also version 18 on esl-erlang package but the problem is the same), when I try to start the app I get this strange error:

$ bin/heimdall foreground
/home/pi/heimdall/erts-8.1/bin/erlexec: 1: /home/pi/heimdall/erts-8.1/bin/erlexec: Syntax error: "&" unexpected
Shutting down node cleanly..
/home/pi/heimdall/erts-8.1/bin/escript: 1: /home/pi/heimdall/erts-8.1/bin/escript: n: not found
/home/pi/heimdall/erts-8.1/bin/escript: 1: /home/pi/heimdall/erts-8.1/bin/escript: n: not found
/home/pi/heimdall/erts-8.1/bin/escript: 1: /home/pi/heimdall/erts-8.1/bin/escript: n: not found
/home/pi/heimdall/erts-8.1/bin/escript: 1: /home/pi/heimdall/erts-8.1/bin/escript: ELF: not found
/home/pi/heimdall/erts-8.1/bin/escript: 2: /home/pi/heimdall/erts-8.1/bin/escript: Syntax error: ")" unexpected
Node is not running!

**Comment by bitwalker** [comment]
You won't be able to deploy a release compiled on one architecture to a machine of another architecture. To do this, you need to either cross-compile the release, or set `{include_erts, false}` in `rel/relx.config`.
