### ISSUE TITLE
Can't add `poolboy` as dependence

### ISSUE THREAD

**Issue by jsvisa** [bitwalker/exrm#43]
I don't know why, but it occurred. I add [poolboy](https://github.com/devinus/poolboy) as  my dependence, use your tool to create a release, I found it can't add `poolboy` as it's dependence. You can try it.

**Comment by tsloughter** [comment]
No, `included_applications` will not "simply load them". It does more. You should use `load` as the type to have the app only `load` when the release is run: http://www.erlang.org/doc/man/rel.html 

This is supported in `relx` by simply adding `load` to a tuple with the app name in the relx list of applications: `{release, {rel_name, "vsn"}, [app_name, {another_app, load}]}.`

**Comment by tsloughter** [comment]
Also see http://learnyousomeerlang.com/the-count-of-applications#included-applications

**Comment by bitwalker** [comment]
@tsloughter Yeah I've mentioned in other places since this one was closed about what `included_applications` is actually for. Learned that the hard way :/

**Comment by tsloughter** [comment]
Ah ok. Someone linked me to this in the Elixir channel after they said it appeared to be your suggested solution after I told them not to use it :)

**Comment by bitwalker** [comment]
Damn it haha. I'll have to update the docs to talk about it then. Thanks for running interference :). Normally I'm in IRC during the day, but today was heads down on work projects.

**Comment by aaronjensen** [comment]
It was me :disappointed: So what is the suggested approach now @bitwalker?

**Comment by bitwalker** [comment]
@aaronjensen Put all of your dependencies in `:applications`. If you do not want an OTP application you have as a dependency to start, then you'll want to use the suggestion @tsloughter made:

- Create `rel/relx.config`
- Put `{release, {your_app_name, "your_app_vsn"}, [your_app_name, {another_app, load}]}.` in `relx.config`.

I haven't tested this myself, so it may break some assumptions with how I'm merging in `relx.config`, but if so, just open an issue for it. On my roadmap is providing a better release configuration mechanism for exrm, probably before I release 1.0.
