### ISSUE TITLE
conform binary should be included within the release directory, not bin

### ISSUE THREAD

**Issue by johnfoconnor** [bitwalker/exrm#57]
instead of my_app/bin/conform we should have my_app/releases/0.0.1/conform

the reasoning is that the conform executable is directly related to the specific schema and conf format used in that release. over the lifetime of an app, if the version of conform changes in a way that is not backwards compatible then using the older binary will cause issues. For this reason the conform executable should instead be located with the associated schema and conf files within the appropriate releases subdirectory

**Comment by bitwalker** [comment]
I'm going to revisit this now, it should be a fairly easy change.

**Comment by johnfoconnor** [comment]
Unfortunately I no longer have to pleasure of working on elixir apps but this is definitely needed, especially as exrm is continuing to gain traction. Nice job!

**Comment by bitwalker** [comment]
@johnfoconnor That's too bad! Hopefully if you get the chance to return, things will be much more refined :)

**Comment by bitwalker** [comment]
Fixed in a5af772, will be pushed in the next release of exrm.
