### ISSUE TITLE
Upgrade is successful, but no changes are effected

### ISSUE THREAD

**Issue by async-cl** [bitwalker/exrm#74]
I seem to have a nice update going on, I have this in output

executing: bin/xservice upgrade 0.0.4
Release 0.0.4 not found, attempting to unpack releases/0.0.4/xservice.tar.gz
Unpacked successfully: "0.0.4"
Installed Release: 0.0.4
Made release permanent: "0.0.4"

however, even though, I do mix clean, mix deps.get, mix compile, mix release

with some changed files I'm just not seeing any changes in my output.

I'm running my erlang process in docker/ubuntu in foreground mode as it's run as a daemon afterwards, then i do the exrm upgrade it in a separate process.

I'm new to erlang hot code updates, so I am not sure exactly how they work, but generally I believe the @vsn in a module is a checksum I don't explicitly have to set. However, i also tried setting the @vsn to "0.0.4" for the module I'm checking for updates on in case that was necessary - still no cigar.

So, I think I'm missing someting fundamental somewhere.

Any ideas?
....

update: one thing, the changes I'm looking for are in another project which is referenced as a dep from the one I'm actually releasing, would that make a diff?

update2: also, like Devinus, I'm not getting any log output in the log dir

**Comment by bitwalker** [comment]
exrm now generates appups automatically for dependencies, as of 0.19.0. I'm closing this for now, but please feel free to reopen it if this is still an issue.
