### ISSUE TITLE
Start/console with 'include_erts, false'

### ISSUE THREAD

**Issue by rubencaro** [bitwalker/exrm#77]
I tried to setup a release workflow on a new project and I decided not to include erts. 

Everything went fine until I got to run `bin/project start`. Then my app wouldn't start complaining about modules not being there.

I got everything to work just by adding `unset ROOT_DIR` the line before the `exec` command inside `console` (right before this line https://github.com/bitwalker/exrm/blob/b7df8aa1fe00cf24d49981d0eb659fb4d97b84e2/priv/rel/files/boot#L382 ) . It was set to my project's root, but it did not work. By unsetting it it worked again. It should have been set to the local erts root, I guess. 

I see that `ROOT_DIR` comes out ok from `find_erts_dir` (at https://github.com/bitwalker/exrm/blob/b7df8aa1fe00cf24d49981d0eb659fb4d97b84e2/priv/rel/files/boot#L154), but right after that you force it to `RELEASE_ROOT_DIR` (at https://github.com/bitwalker/exrm/blob/b7df8aa1fe00cf24d49981d0eb659fb4d97b84e2/priv/rel/files/boot#L155). If I removed that forced value, then other things may get broken. I preferred to simply unset it already inside the `console` case clause.

I haven't tried upgrades and stuff yet, but with this I got start, console, ping, rpc and restart to work. Reboot did not work complaining about 'heart not set' or something like that.

I'll be more specific when I can try it again, sorry. My bad. 

Will come back with more data. Anything specific you want me to run and post here?

Thanks

**Comment by rubencaro** [comment]
@bitwalker I'm afraid I cannot get the same behaviour again. Now I am trying generating the release on a Fedora21 laptop and running on a Ubuntu14.04 server. Following the same steps above I get the same `{undef,[{crypto,hash,[sha,\"pass\"],[]}` message, but also I see another message:

```
15:21:37.130 [error] Unable to load crypto library. Failed with error:
":load_failed, Failed to load NIF library /tmp/sequeler/lib/crypto-3.4.2/priv/lib/crypto: 'libcrypto.so.10: cannot open shared object file: No such file or directory'"
OpenSSL might not be installed on this system.
```
That one was not showing before. Let there be light.

But the `unset ROOTDIR` hack did not work this time. So now I cannot get the release generated from a Fedora to work on a Ubuntu. I guess that it was only for the first mix of versions (from Fedora20 to Ubuntu14.04) that the hack could make it work between the two OSs, but not for a general case. 

This Issue can be closed. Thanks.

I guess avoiding the `crypto` dependency (if that's even possible), or else bundling openssl with erts ([is it real?](http://www.erlang.org/download/otp_src_17.4.readme)) this could be solved. None of them are options for me now. I need crypto for several applications, and shipping erts itself has even more problems with portability.

Is there a way to include openssl itself into my release?

Thank you.

**Comment by bitwalker** [comment]
I feel like I've seen this before, not necessarily with releases, but someone just running their app and getting that error. I'll poke around a bit, maybe I can find some references to a fix. The error message to search for you if you are trying to figure this out as well would be the "OpenSSL might not be installed on this system` bit.

**Comment by rubencaro** [comment]
Yes the problem is crypto being compiled against some version of openssl, and then try to run it with another version.

It says it's not installed because it's looking for some 'libcrypto.so.10', but on that system there is only 'libcrypto.so' . If I make a link to libcrypto.so named libcrypto.so.10  then it complains not to be the exact same version...

That's why I was talking about shipping openssl and not just installing it on target server.

Maybe there's a way to get that lib on the package and have it on the path once extracted. That would solve it. I will play with it when I can too. 

Thanks!

**Comment by bitwalker** [comment]
Makes sense to me, not sure what the ideal solution is here, other than making sure the versions match on the build server and the production server. Let me know how your experimentation goes/what solution you end up with - it'd be good to have documented somewhere in case it comes up again. I'll close this for now.
