### ISSUE TITLE
Issue starting correct version when stopping app then restarting

### ISSUE THREAD

**Issue by skylerparr** [bitwalker/exrm#80]
If I issue a stop to my application after it has been upgraded to a higher version than the initial version for release, then upon restart the version restarts back at the initial version. Additionally, if I run upgrade to the expected version it reports it's already at that version. In order to get it to the correct version I have to downgrade to the initial version then upgrade back to the expect version.

Repro steps:
- mix release
- rel/app/bin/app start
- bump version number in mix.exs
- mix release
- rel/app/bin/app upgrade "0.0.2"
- rel/app/bin/app stop
- rel/app/bin/app start
# 0.0.1 starts
- rel/app/bin/app upgrade "0.0.2"
# already installed and marked permanent
- rel/app/bin/app downgrade "0.0.1"
- rel/app/bin/app upgrade "0.0.2"
# finally running the correct version

I would expect the application to start up with the correct version.

**Comment by jarednorman** [comment]
@bitwalker Don't mean to bug you, but did you track this one down?

**Comment by bitwalker** [comment]
Fixed in 0615313, released as 0.18.7
