### ISSUE TITLE
Provide means of configuring release via environment variables

### ISSUE THREAD

**Issue by bitwalker** [bitwalker/exrm#90]
See original motivation [here](https://github.com/phoenixframework/phoenix/issues/354).

Just to follow up here with [notes from the conversation](https://gist.github.com/bitwalker/cf850398db7d6e6fea6a) @josevalim and I had in IRC this morning:
- I'll add support for a new experimental config section `system_env`, which will contain app-specific configuration values which will be pulled from the system environment at boot time.
- If a user has System.get_env calls in config.exs, but no `system_env` section, a warning will be generated notifying them that any runtime configuration which depends on the system environment should be moved to that section.
- At boot time, the `system_env` section will be evaluated, and the environment values will be applied to the appropriate configuration settings via the `-application` flag when booting the VM.

An example of what the `system_env` section would look like in `config.exs`:

``` elixir
config :sasl,
  errlog_type: :error
config :phoenix,
  port: 8000

system_env: [
  phoenix: [ port: "PORT" ]
]
```

In this example, `phoenix: port` would be `8000`, unless the `PORT` environment variable is defined, which takes precedence. In this way you can emulate the `System.get_env("PORT") || Application.get_env(:phoenix, :port)` behavior.

Thoughts everyone?

**Comment by guilleiguaran** [comment]
:+1: looks great for me

**Comment by tsloughter** [comment]
Note that the start scripts that relx generates will replace os vars in sys.config and vm.args if the env variable `RELX_REPLACE_OS_VARS` is set when run.

**Comment by felipesere** [comment]
Any update on this? I need to use the environment variables for Docker.
Let me know if there is anything I can do to help.

**Comment by edgurgel** [comment]
I'm using docker passing the .conf file as a volume

`docker run -v /var/myapp.conf:/app/releases/1.0.0/myapp.conf`

This way you can easily override the configuration file.

**Comment by felipesere** [comment]
@tsloughter can you explain how `RELX_REPLACE_OS_VARS` can be used here? I went through the code but I did not quite understand what to put where to allow it to be replaced...

**Comment by tsloughter** [comment]
It is part of the `extended_start_script`. It'll replace vars in `sys.config` and `vm.args` of the form `${VARIABLE}`.

**Comment by xtagon** [comment]
Since this method makes you declare it as `[port: "PORT"]` instead of as a custom expression (e.g. `System.get_env("PORT")`), how do we handle the case where one might wish to cast the ENV variable? All ENV variables are strings but some app configurations might want to parse them as integers, or lists of strings, etc.

**Comment by artburkart** [comment]
@edgurgel - would your solution work in production?

**Comment by edgurgel** [comment]
@artburkart, yes it does! It's simply mounting the file where the configuration is and where exrm will read the.

**Comment by shadabahmed** [comment]
I was looking for exactly the same thing. :+1:  Will wait for the release :smile:

**Comment by emilsoman** [comment]
@xtagon What I would do is, make everything strings , so that all configuration happens using strings - whether they are in environment variables or in the config file. I would add a wrapper module that parses these strings into appropriate types.

**Comment by emilsoman** [comment]
@bitwalker I like your idea :+1: . Have you been able to add support for this yet ?

**Comment by bitwalker** [comment]
Just an update for those watching, I haven't had a chance to tackle this yet, but I'm planning on doing so before releasing 1.0 proper.

**Comment by emilsoman** [comment]
Thanks for the update

**Comment by edevil** [comment]
Was this included? It is not in the changelog.

**Comment by bitwalker** [comment]
@edevil No it wasn't, I needed to bump the version to 1.0 before making any further changes, because I couldn't justify calling further releases "release candidates" for 1.0.

**Comment by werbitzky** [comment]
+1!! :)

**Comment by tslater** [comment]
+1

**Comment by BryanJBryce** [comment]
+1

**Comment by denisw** [comment]
Any progress on this? I know that there are workarounds, but having a direct solution for boot-time environment variables would remove one roadblock for creating cobfigurable Docker images.
