### ISSUE TITLE
Could not generate relup for umbrella project

### ISSUE THREAD

**Issue by zztczcx** [bitwalker/exrm#91]
I test in your git repository exrm-umbrella-test .
and change the master_app version to 0.0.2 
then mix release 

Errors generating relup 
  Could not open file  exrm-umbrella-test/apps/master_app/rel/master_app/lib/master_app-0.0.2/ebin/master_app.appup

**Comment by bitwalker** [comment]
I'll take a look, this may be related to another issue I'm currently investigating. Thanks for reporting!

**Comment by zztczcx** [comment]
now I changed the v2_path = "#{File.cwd!}/_build/#{env}/lib/#{app}" like this . and fixed the problem .
but I donot think this is a good solution .
I am not very familiar of the  Mix.Project.compile_path method.

**Comment by zztczcx** [comment]
or delete config = [build_path: Mix.Project.build_path, umbrella?: true] the build_path?
