### ISSUE TITLE
Allow auto confirm for implode

### ISSUE THREAD

**Issue by cjimison** [bitwalker/exrm#95]
It would be great if there was a flag I could set to auto confirm a Mix release.clean --implode.  While this is not something I would use in my day to day work, asking for a confirmation from my Jenkins build machine ( or any cl system) is difficult to work around.

Thanks for the awesomeness that is exrm!!!

**Comment by bitwalker** [comment]
Should be fairly trivial to add this as an enhancement. I'll add it to the TODO list!

**Comment by bitwalker** [comment]
This is now in master :)
