### ISSUE TITLE
Deplying a Phoenix app : start command is successful but foreground command is not

### ISSUE THREAD

**Issue by raw1z** [bitwalker/exrm#98]
I'm deploying a phoenix (0.8.0) app with exrm (0.14.17). The process runs successfully and the release is generated as expected. When I run it using the __start__ command everything works fine. I can ping the node and the website is accessible too. But when I run it using the __foreground__ command, the app crashes issuing the following error:

    {"Kernel pid terminated",
        application_controller,
        "{application_start_failure,
            phoenix,
            {bad_return,
                {{'Elixir.Phoenix',start,[normal,[]]},
                    {'EXIT',
                        {undef,
                            [
                                {'Elixir.Collectable',into,[#{}],[]},
                                {'Elixir.Enum',into,3,[{file,\"lib/enum.ex\"},{line,907}]},
                                {'Elixir.Phoenix.Template',compiled_format_encoders,0,[{file,\"lib/phoenix/template.ex\"},{line,170}]},
                                {'Elixir.Phoenix.Template',format_encoder,1,[{file,\"lib/phoenix/template.ex\"},{line,158}]},
                                {'Elixir.Phoenix',start,2,[{file,\"lib/phoenix.ex\"},{line,13}]},
                                {application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,272}]}
                            ]
                        }}}}}"}

The code which is crashing in the phoenix code is the following:

```elixir
    encoders =
       @encoders
        |> Keyword.merge(raw_config(:format_encoders))
        |> Enum.filter(fn {_, v} -> v end)
        |> Enum.into(%{}, fn {k, v} -> {".#{k}", v} end)
```

I debugged in order to understand what's happening:

```elixir
    encoders =
       @encoders
        |> Keyword.merge(raw_config(:format_encoders))
        |> Enum.filter(fn {_, v} -> v end)
        |> IO.inspect
        |> Enum.into(%{}, fn {k, v} -> {".#{k}", v} end)
```

The result of __IO.inspect__ is:

```elixir
    [html: Phoenix.HTML.Engine, json: Poison]
```

Do you have any idea why this code works perfectly fine when the release runs with the __start__ command but fails when the release runs with the __foreground__ command ?

I'm using elixir 1.0.2 and erlang 17.4 on OS X Yosemite 10.10.2. Notice that I tried with the master branch of the github repo and had the same issue.

**Comment by raw1z** [comment]
Found the solution ! In fact, it was my fault. I was using the master branch of the phoenix github repo instead of the 0.8.0 version. Sorry :-)

**Comment by bitwalker** [comment]
@raw1z This might be the shortest lived ticket in exrm history haha, but I'm glad you were able to find the solution! Good to have stuff like this in the history too in case others run into the same thing.
